### ISSUE TITLE
Don't override manually set link targets in dataset descriptions

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1039]
Currently we make all links `target="_blank"` in places like `initialMessage`, but if a configuration has markdown with `target="_self"` we should respect that.

**Comment by stevage** [comment]
This line in KnockoutMarkdownBinding needs to change:

```
function setAnchorTargets(element) {
    if (element instanceof HTMLAnchorElement) {
        element.target = '_blank';
    }
```

**Comment by kring** [comment]
IMO it's bad when TerriaJS opens a link in the same window, because the user loses the state of their map.  And it's more likely that a target was set incorrectly than with the actual intention of opening a link in the same window that is running TerriaJS.  So I'm closing this, but feel free to reopen with a concrete use case if you have one.
