### ISSUE TITLE
Let the init file specify features' name field

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1041]
As per #1018, csv and geojson features are named in the feature info panel according to this rule: in this order, match:
- title
- title (case insensitive)
- name (case insensitive)
- containing title (case insensitive)
- containing name (case insensitive) 
- if none are found, csv falls back to "Site Data"'; I haven't checked what happens with geoJson.

It would be nice if we could specify the name field in the init file, so the info box doesn't fill up with lots of sections all called `Site Data`.

We could either add a new property, eg. `featureNameField` (alongside `featureInfoTemplate`), or else we could allow `featureInfoTemplate`, which can already be a json object with a `template` key (see #1027), to also take a `nameField` key.

I haven't thought yet about whether this has applicability beyond csv and geoJson datatypes.

**Comment by meh9** [comment]
It definitely is applicable for all layer types, not just CSV and GeoJSON. 

It would be great to be able to template it as well, since things like when region matching a Postcode CSV the name of the feature info panel is just the postcode name so it reads like "Solar PV 2880", which isn't really clear what it means. Is it the number of panels? Number of kW in that postcode? People will not often know the postcode number they just clicked on so the number that comes up could be anything to them, so if we could make it something like "Solar PV Postcode: {{Postcode}}" would work better.

Another example is the AREMI Distance to Transmission Lines WMS layer. It shows contours with km distances and is currently not matched by the magic name rules. When clicked it just gives a number and doesn't say that it's km, so if we could template it to show "{{Contour}}km" would be super awesome.

**Comment by RacingTadpole** [comment]
I like it. In that case, how about a format like this (we already have the template and partial keys as an option, so I'm just making the "name" key special):

```
      "featureInfoTemplate" : {
          "name": "{{Contour}}km",
          "template": "<div>Pixel colour: {{>foobar}}</div>",
          "foobar": "<b>Red={{Red}} Blue={{Blue}} Green={{Green}}</b>"
      }
```

**Comment by kring** [comment]
@RacingTadpole do you think we should move partials to their own key, like:

```
      "featureInfoTemplate" : {
          "name": "{{Contour}}km",
          "template": "<div>Pixel colour: {{>foobar}}</div>",
          "partials": {
              "foobar": "<b>Red={{Red}} Blue={{Blue}} Green={{Green}}</b>"
          }        
      }
```

As we add more stuff to `featureInfoTemplate`, it gets a bit more awkward to resolve the partials.

**Comment by RacingTadpole** [comment]
Yes, that sounds like an improvement!

**Comment by meh9** [comment]
So, I knew about the templates, but what are partials?

**Comment by RacingTadpole** [comment]
Check it out - https://github.com/janl/mustache.js#partials - we allowed for them so that you can have recursive templates, so that you can show tree structures.

**Comment by meh9** [comment]
@RacingTadpole since we can use the template to set the name, is this issue finished now?

**Comment by RacingTadpole** [comment]
yes, thanks.
