### ISSUE TITLE
Make URL in feature info into clickable link

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#1045]
I previously raised a narrower version of this as #316 which Keith closed (I think incorrectly).  Rather than reopen that, I'm creating a broader one that doesn't just relate to WMS services (eg this should be done for CSVs as well).

**Comment by axman6** [comment]
This should probably also work in the auto populated layer info dialog.

Also, this is probably easier said than done, I'll just leave this here: https://mathiasbynens.be/demo/url-regex

**Comment by kring** [comment]
For what it's worth, an actual link tag _will_ work.  For example, if the value of the CSV column is `<a href="http://nationalmap.gov.au">nationalmap.gov.au</a>`, it will be a working link that opens a new window when clicked.

We also attempt to linkify normal text using (linkify-it)[https://github.com/markdown-it/linkify-it], but it doesn't work well in the feature info table because the library assumes that text inside a `<td>` is HTML and if it was supposed to be a link, it would be a link already.  We might have to linkify earlier, prior to building the table.

**Comment by stevage** [comment]
Well, I've made a [really simple change](https://github.com/TerriaJS/terriajs/commit/bc502f4654b86486849ec7b6426b30519a7558e8) that fixes this in TableDataSource.

I don't think a fancy regex is needed. If someone has a value like "http://something that isn't a URL", then linking to it really isn't terrible, and is pretty understandable from the user's perspective.

**Comment by RacingTadpole** [comment]
@stevage, I've just submitted a PR which follows your approach, but I've used markdown instead of a regexp, and applies it to csv, geojson and WMS.

**Comment by stevage** [comment]
OIC, URL-like things are automatically linked in markdown, hence no need for specific behaviour?

**Comment by RacingTadpole** [comment]
Yep! I have a slight worry that there might be some data with *'s or _'s in it in markdown-like ways that now gets interpreted by markdown.  But hopefully, if it's meant to be interpretable by humans, it shouldn't.

**Comment by stevage** [comment]
Yeah. I don't think markdown is at all common in government data sources. I'm starting to realise we probably need ways to disable a lot of this magic behaviour.
