### ISSUE TITLE
specifying "zoomTo" for a catalog item in json

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1064]
I'd like to be able to give a URL to folks like:
http://dev.tampabaymap.org:9000/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/mwra.json
and have it zoom to the bounding rectangle of a specific catalog item.

I tried to enable this by setting `"zoomTo": "true"`, but this didn't seem to have any effect:

```
{
    "catalog": [
        {
            "name": "MWRA Datasets",
            "isOpen": true,
            "type": "group",
            "items": [
                {
                    "name": "MWRA WQ-FVCOM",
                    "isEnabled": true,
                    "type": "wms",
                    "zoomTo": "true",
                    "url": "http://sci-wms.whoi.edu/wms/datasets/smast_wq",
                    "layers": "DO",
                    "parameters": {
                        "COLORSCALERANGE": "6.00,12.00",
                        "NUMCONTOURS": "50",
                        "styles": "filledcontours_jet",
                        "TIME": "2015-10-20T00:00:00.000Z",
                        "VERSION": "1.1.1"
                    }
                }
            ]
        }
    ],
    "isOpen": true
}
```

Is there a way?

**Comment by meh9** [comment]
I set the `homeCamera` to do this. Unfortunately, it has the drawback that since the `homeCamera` is updated when you click the Reset View button the new `homeCamera` is where it resets to:

http://nationalmap.gov.au/renewables/#http://static.aremi.nicta.com.au/init/NemSolarFarms.json

Another way of doing it is to use a full Share URL to do what you want, since they can include an `initialCamera` key, but unless you write a URL shortener you can't update the target.

You could do a combination of a shortened Share URL that has your layer as an `initSources`, this way you can still update the `mwra.json` file, but unfortunately you cannot update the `initialCamera`:

```
{
  "version": "0.0.05",
  "initSources": [
    "init/aremi.json",
    "http://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/mwra.json",
    {
      "initialCamera": {
        "west": -72.07692081488644,
        "south": 41.201720345027695,
        "east": -68.93917805338461,
        "north": 43.00426508306371,
        "position": {
          "x": 1636339.4547570471,
          "y": -4623083.313913917,
          "z": 4402249.458678148
        },
        "direction": {
          "x": -0.24911388762933206,
          "y": 0.7044187158602867,
          "z": -0.6646326381814158
        },
        "up": {
          "x": -0.17931080992313356,
          "y": 0.6408552643208887,
          "z": 0.7464262613653552
        }
      },
      "homeCamera": {
        "west": 112,
        "south": -48.00000000000001,
        "east": 155,
        "north": -5
      },
      "baseMapName": "Positron (Light)",
      "viewerMode": "3d"
    }
  ]
}
```

The URL becomes this unshortened:

http://dev.tampabaymap.org:9000/#start=%7B%22version%22%3A%20%220.0.05%22%2C%20%22initSources%22%3A%20%5B%22init%2Fehzrap.json%22%2C%20%22http%3A%2F%2Fraw.githubusercontent.com%2Frsignell-usgs%2Fehzrap%2Fmaster%2Ftesting%2Fmwra.json%22%2C%20%7B%22initialCamera%22%3A%20%7B%22west%22%3A%20-72.07692081488644%2C%20%22south%22%3A%2041.201720345027695%2C%20%22east%22%3A%20-68.93917805338461%2C%20%22north%22%3A%2043.00426508306371%2C%20%22position%22%3A%20%7B%22x%22%3A%201636339.4547570471%2C%20%22y%22%3A%20-4623083.313913917%2C%20%22z%22%3A%204402249.458678148%20%7D%2C%20%22direction%22%3A%20%7B%22x%22%3A%20-0.24911388762933206%2C%20%22y%22%3A%200.7044187158602867%2C%20%22z%22%3A%20-0.6646326381814158%20%7D%2C%20%22up%22%3A%20%7B%22x%22%3A%20-0.17931080992313356%2C%20%22y%22%3A%200.6408552643208887%2C%20%22z%22%3A%200.7464262613653552%20%7D%20%7D%2C%20%22homeCamera%22%3A%20%7B%22west%22%3A%20112%2C%20%22south%22%3A%20-48.00000000000001%2C%20%22east%22%3A%20155%2C%20%22north%22%3A%20-5%20%7D%2C%20%22baseMapName%22%3A%20%22Positron%20%28Light%29%22%2C%20%22viewerMode%22%3A%20%223d%22%7D%20%5D%20%7D

**Comment by kring** [comment]
> Another way of doing it is to use a full Share URL to do what you want, since they can include an initialCamera key, but unless you write a URL shortener you can't update the target.

@meh9 I'm not completely following you here.  You should be able to set `initialCamera` in a JSON file the same way you can set `homeCamera`.  Is it not working?

**Comment by meh9** [comment]
@rsignell-usgs Kevin has actually just showed me that `homeCamera` and `initialCamera` can be used at the same level, so I will be changing mine to say `initialCamera`. You should be able to just put this at the top of your init file to have it "zoom to" the extents of your layer:

```
{
        "initialCamera": {
            "west": -72.07692081488644,
            "south": 41.201720345027695,
            "east": -68.93917805338461,
            "north": 43.00426508306371
        },
        "catalog": [
...
```

Kevin also pointed out that I may have misunderstood, and you actually just want it to zoom to the bounding box given in the layer metadata. We have no way of doing that at the moment, but it sounds like a reasonable feature to have.

**Comment by rsignell-usgs** [comment]
Yes, I was hoping that specifying "zoomTo: True" in the item jzon would invoke the same behavior as clicking on the "zoom to" in the "Legends" panel:
![2015-11-11_18-50-03](https://cloud.githubusercontent.com/assets/1872600/11106990/814234dc-88a7-11e5-9002-6e8d3c0fd4c0.jpg)

And if that isn't yet possible, then yes, I think it would be a nice feature to have!

But I certainly appreciate the info you provided about how to fix the view to wherever you want.  That will be super useful also.

**Comment by rsignell-usgs** [comment]
But just report back that setting `initialCamera` in the json:
https://github.com/rsignell-usgs/ehzrap/blob/master/testing/mwra.json

works great:

http://dev.tampabaymap.org:9000/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/mwra.json

Producing:
![2015-11-13_11-51-24](https://cloud.githubusercontent.com/assets/1872600/11151800/0afbf766-89fd-11e5-84e0-1c3e52a5b3c4.png)

**Comment by stevage** [comment]
Fixed then?
