### ISSUE TITLE
CSV column type detection is not robust and not coercive

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1081]
I ran into an issue today with the SEIFA test dataset. A single row out of 2483 had the value "-" instead of a number, which broke a new choroplething function I'm using. `DataTable` had happily marked the column as `VarType.SCALAR` because it passed this trivial test:

```
    if (this.varType === VarType.SCALAR && this.minVal > this.maxVal) {
        this.varType = VarType.ENUM;
    }
```

It would be pretty easy to more robustly check that every value is actually a number, but:
1. That would seriously slow down the loading of large datasets
2. In cases like this, it would throw out the baby with the bathwater, by treating 2482 rows as enums instead of scalars, because of one bad egg.

I guess the solution is to somehow combine type detection with type coercion: once a column has been marked as `VarType.SCALAR` it should never return non-scalars. But since code tends to access the raw array (`DataVariable.vals`) I'm not sure how one can practically implement that without a serious performance penalty.

Thoughts?

**Comment by stevage** [comment]
A lot of this stuff was rewritten recently and may no longer be an issue. Any idea, @RacingTadpole ?

**Comment by RacingTadpole** [comment]
Yes, this should just work now. By default "-" is replaced with 0 in a numerical column; this can be controlled using `tableStyle.replaceWithZeroValues`. Definitely let me know if you still see it happening though.

**Comment by axman6** [comment]
I'm not sure replacing `-` with `0` is the right default, a `-` is an intentional signal that there is no data, at least in our data and in other data we've seen. There is usually a big difference between no data and 0 (for our power generation data, no data means the plant didn't report anything/wasn't online, where as 0 means it was reporting that is was not producing any power.

**Comment by stevage** [comment]
Yeah, it should be replaced with `null`, assuming that we can handle nulls elsewhere?

**Comment by RacingTadpole** [comment]
Yep, that makes perfect sense - will do. I originally thought 0 looked better, because the null color did not appear the legend, so it looked a bit weird to have lots of points in an unidentified color. But now the color is in the legend, it will work fine.
As an aside, one of Excel's number formatting options shows zeros as "-", so "-" is potentially ambiguous.

**Comment by RacingTadpole** [comment]
I assume a completely missing number should also default to no data, rather than 0?

**Comment by axman6** [comment]
Yeah that seems like a reasonable assumption to me, until we find something which that isn't true for.

**Comment by RacingTadpole** [comment]
:-)  I won't change this default for this AREMI release, but if you want, to achieve this you could add this to the relevant catalog items' `tableStyle`:

```
"replaceWithZeroValues": [],
"replaceWithNullValues": ["-"],
```

This will override the existing default `['-', null]`, which turns null and "-" into 0 values; and instead convert "-"s to nulls. (I haven't rigorously tested this yet...)
