### ISSUE TITLE
Changing CSV display variable also changes layer order

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1099]
Changing the "display variable" of a `CsvCatalogItem` via the UI makes that layer pop on top of all the other layers on the map.  The UI still displays the original order.  This is in Cesium only, Leaflet is unaffected.

**Comment by kring** [comment]
Possibly related: Add a region-mapped dataset to the map, then add a non-region-mapped dataset on top of it.  When you share that and open the shared link a new window, the region-mapped dataset will be on top.

**Comment by tephenavies** [comment]
Working on this.

**Comment by tephenavies** [comment]
@kring Also likely related: While testing the bug I made a new map with 2 layers from National Data Sets:
1. Framework -> Australian Mainland (region-mapped)
2. Land -> Land Cover (non-region-mapped)

Then I clicked share and copied the URL into a new window and pressed enter. I got the message:

> TypeError: undefined is not a function

Investigating further using the Javascript debugger, I found that the exception is caused by [NowViewing.js:178](https://github.com/TerriaJS/terriajs/blob/7318a1391d386ad8489ab649f2faeab317a5a617/lib/Models/NowViewing.js#L178) which tries to call `raise` on a `NoViewer`.

I've done some testing of including 1 of the layers, then the other, then both in the opposite order and sharing and the only situation that this exception occurs in is when the 2 layers are added in the order mentioned above. This is regardless of the type of map (Leaflet or Cesium)

Here's are examples on [Leaflet](http://nationalmap.gov.au/#share=kV2Aty) and [Cesium](http://nationalmap.gov.au/#share=bypZCi)

**Comment by kring** [comment]
Yeah thanks @steve9164, good detective work!  I just opened a pull request to fix that yesterday, though, #1112.

**Comment by kring** [comment]
Sorry, the PR was #1114.

**Comment by tephenavies** [comment]
@kring Does the original problem still exist or was that fixed too?

**Comment by kring** [comment]
The original problem described in this issue still exists.

**Comment by tephenavies** [comment]
@kring I think I might have found the cause of the problem. It took me a while to find, but for region-mapped csv datasets, changing the selected variable calls the following functions:

```
-> CsvDataset.setSelected (CsvDataset.js:77)
  -> updateFunction (CsvCatalogItem.js:580)
    -> updateTableStyle (CsvCatalogItem.js:715)
      -> CsvCatalogItem._redisplay (CsvCatalogItem.js:500)
        -> CsvCatalogItem._disable (CsvCatalogItem.js:391)
          -> ImageryLayerCatalogItem.disableLayer (ImageryLayerCatalogItem.js:517)
            -> scene.imageryLayers.remove(layer); (ImageryLayerCatalogItem.js:524)
               (which removes the ImageryLayer from the ImageryLayerCollection)
        -> CsvCatalogItem._enable (CsvCatalogItem.js:381)
            -> ImageryLayerCatalogItem.enableLayer (ImageryLayerCatalogItem.js:417)
              -> scene.imageryLayers.add(result); (ImageryLayerCatalogItem.js:481)
                 (which adds the imagery layer back in at the top)
```

A possible fix could be to use [the version of `ImageryLayerCollection.add()` that takes an index](https://cesiumjs.org/Cesium/Build/Documentation/ImageryLayerCollection.html#add) or to check afterwards that nothing needs to be raised or lowered (I'm still not 100% sure how the raise and lower works, when things are redrawn or cached etc.)

**Comment by tephenavies** [comment]
Also the documentation on `Cesium.prototype.updateLayerOrderToKeepOnTop` is not quite correct. It says that the function `Updates the order of layers to match the order in the Now Viewing pane.` but it only makes sure that layers that are marked to be on top are kept on top, the rest of the layers are not reorganised.

Should I raise an issue and put in a pull request to change the wording of the documentation, or is there an easier way to do it?
