### ISSUE TITLE
Picking problem in 2D after unchecking data variable in CSV catalog item

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1121]
In NationalMap, visit `#test` and then:
1. Switch to 2D.
2. Enable `National Data Sets -> Statistical Boundaries -> Statistical Area Level 3 (SA3)`.
3. Enable `Test Data -> Miscellaneous Files -> Auto Incidents No Time (CSV)`.
4. Switch to the Now Viewing tab and uncheck `id` under `Display Variable`.
5. Click within one of the SA3 regions.

TerriaJS reports "No features found" instead of reporting the SA3 region you clicked in.

**Comment by chloeleichen** [comment]
@steve9164 maybe you can have a look at this one?

**Comment by tephenavies** [comment]
@kring After testing this a few times, I only got the described behaviour once, and I could not reproduce this again. All other times I was able to select features from both the SA3 and Auto Incidents layers.

What is the expected behaviour when all CSV variables are deselected? Should it be the same as the layer being hidden? If you deselect `id`, the layer stays and the features (which relate to `id`) are still clickable, but on `Test Data -> Region Mapping (CSV) -> 2011 Census AUST (CED)` deselecting the current variable redraws the layer as 1 colour for all of Australia because it is no longer mapping data.

**Comment by kring** [comment]
Strange you could only reproduce it once.  I've been able to do it pretty consistently with the procedure above.  Don't forget to switch to 2D!

When you de-select the display variable, the points / regions should still show, but with a default color.  It's not the same as the layer being hidden.

**Comment by tephenavies** [comment]
Yep, I forgot to switch to 2D. Just figured that out before you wrote a reply.

So the layers are working fine, it's just feature selection that's not working.

**Comment by kring** [comment]
Yep, that's right.  The picking is pretty complicated in Leaflet, so it's not surprising there's a bug there.  I've also seen picking-related problems when using versions of Leaflet after 0.7.3 in a different app, so it may be worth trying to downgrade first just to see if that fixes it.

**Comment by tephenavies** [comment]
@kring No problems in Leaflet 0.7.2 using 2D base maps. I confirmed that I was running 0.7.2 by putting a breakpoint into the Leaflet constructor in Leaflet.js and checking L.version.

**Comment by tephenavies** [comment]
@kring Trying to test with version 0.7.3 now, but my leaflet still reports that it's version 0.7.2. How do I change it? My package.json for Terria has "0.7.3" and my package.json for nationalmap has "^0.7.3" and I've run npm install in both Terria and nationalmap and gulp in nationalmap.
