### ISSUE TITLE
Item shows up multiple times in search

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1131]
Searching for "cfa" shows up 4 identical entries "Country Fire Authority (CFA) Total Fire Ban Districts - Vicmap Admin". Selecting 1 of these selects all 4 of them (since they are the same item).

I think the search feature should only show each item once.

**Comment by tephenavies** [comment]
Currently, hovering over an item in the search gives the item's location in the catalogue as a tooltip. If duplicate results are not displayed, some of these locations will not be displayed.

As I see it, there are 2 options:
1. Modify the tooltip slightly for duplicates (something like: `In n places including` or `... and n-1 others`), or
2. Don't notify the user that the catalogue item exists in multiple places

However, I think the first option is better

**Comment by stevage** [comment]
Thanks for fixing this.

Before:

![screenshot 2015-12-07 15 57 21](https://cloud.githubusercontent.com/assets/678344/11619375/55fc15b4-9cfb-11e5-8f73-b9f7ea399323.png)

After:

![screenshot 2015-12-07 15 57 16](https://cloud.githubusercontent.com/assets/678344/11619376/55fe897a-9cfb-11e5-875b-1acf67a5849b.png)

The tooltip thing is a little bit suboptimal, because once the box is checked it switches to "Change the map view to show the full extent of this data item."

Ideally we'd have a cute little indicator like "x4" or something in a different font, but maybe that'd be overkill?

**Comment by tephenavies** [comment]
Once the box for an item is checked, there is a new tooltip that appears while hovering over the name of the item, however the original location tooltip still displays if you hover over either the checkbox or the info button.

Tooltip:
![1](https://cloud.githubusercontent.com/assets/13863530/11620452/2733c586-9d07-11e5-8026-61afe7ea0738.png)

Checked item tooltip:
![2](https://cloud.githubusercontent.com/assets/13863530/11620439/05eba290-9d07-11e5-89ee-4e99982e587e.png)

Original tooltip showing when hovering over checkbox (or info button):
![3](https://cloud.githubusercontent.com/assets/13863530/11620440/0608b146-9d07-11e5-9cdb-56fc323d1c78.png)

It seems that the original tooltip still applies to the whole item within the list and then as soon as an item is selected, a tooltip is attached to the label of the item, which means the original tooltip can be seen by hovering over parts of the item that aren't the label (i.e. the checkbox and item button).

**Comment by stevage** [comment]
Ah - pretty crappy UX, but not your fault of course.

**Comment by stevage** [comment]
Hmm, another issue I see is that although it collapses duplicate results, the total number of results is limited to 10 (by default):

![screenshot 2015-12-08 12 35 39](https://cloud.githubusercontent.com/assets/678344/11645391/365ec5b4-9da8-11e5-821c-df7bcf0ad11f.png)
