### ISSUE TITLE
Tutorial for CORS issues on the Wiki?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1175]
I get CORS errors all the time, but I'm not sure what the procedure is exactly to work around them with the whitelist stuff.  

It would be great to have a `CORS Issues` entry in the wiki that would allow users to answers such as:

If I try to add a WMS service `http://www.smast.umassd.edu:7002/wms/datasets/ugridtest?REQUEST=GetCapabilities` and have a CORS issue, do I need to add something to  the `proxyDomains` in `wwwroot\config.json` like these:
https://github.com/TerriaJS/NorthernAustralia/blob/master/wwwroot/config.json#L2-L16
and also in `corsDomain` in the `wwwroot\init\xxx.json` files, like:
https://github.com/TerriaJS/NorthernAustralia/blob/master/wwwroot/init/ga.json#L2-L4
or is just one of them okay?

Do I need the whitelist entry to contain the port, like `www.smast.umassd.edu:7002`?

What is the drawback to specifying the whole `umass.edu` domain, or just `.edu` for that matter?

Are there performance factors at play here?

**Comment by kring** [comment]
I agree a tutorial would be good, but I'll answer your questions here first.

You should add _all_ servers you intend to access to `proxyDomains`.  This list authorizes the proxy to work with those servers.  Even servers that support CORS should be in that list because IE9 doesn't support CORS, so it needs the proxy for _all_ cross-origin requests.

Then, you should add servers that do support CORS to the `corsDomains` list.  In browsers that support CORS (all except IE9), servers in this list are contacted directly instead of going through the proxy.  One exception to this (just added in the latest version of TerriaJS) is that an HTTPS web page will access http severs via the proxy in order to avoid a mixed content warning from the browser.  A side effect of using the proxy is that data gets cached by it, so we sometimes exclude CORS-supporting servers from the `corsDomains` list in order to improve their performance by caching them.

In both lists, a server name `foo.org` can be interpreted as `*.foo.org`.  The port must match exactly. It's not very smart, so if you specify port 80 that won't match a server without a port specified, and vice-versa.

The only downside to a permissive whitelist is that you'll then proxy for more servers.  People could use your proxy to make their (malicious?) traffic look like it's coming from your server instead of from them.

**Comment by rsignell-usgs** [comment]
Fantastic, @kring.   You could just cut-and-paste that onto the wiki, as far as I'm concerned!  ;-)  
Thanks so much.

**Comment by rsignell-usgs** [comment]
One more questions on CORS:   

We were trying to add this WMS endpoint:
http://ecowatch.ncddc.noaa.gov/thredds/wms/ncom/ncom_reg1_agg/NCOM_Region_1_Aggregation_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

and got the all-too-familiar CORS error.    We added `ecowatch.ncddc.noaa.gov` to the [config file](https://github.com/rsignell-usgs/map/blob/rich/wwwroot/config.json#L6), and then we created a JSON on github with `ecowatch.ncddc.noaa.gov` in the [`corsDomains` list](https://github.com/rsignell-usgs/ehzrap/blob/master/testing/nfwf.json#L4), but that didn't work until we modified the WMS endpoint in this JSON to have the [proxy prefix](https://github.com/rsignell-usgs/ehzrap/blob/master/testing/nfwf.json#L33).

Does that make sense to you?

So with all this, we can get this to work:
http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/nfwf.json

**Comment by kring** [comment]
Yes, that makes sense.  By adding it to `corsDomains`, you told TerriaJS that the server supports CORS, so it connected to it directly without going through the proxy.  Remove it from `corsDomains` (but leave it in `proxyDomains`) and it should work.

**Comment by RacingTadpole** [comment]
I've added @kring's comments above to a link near the end of the wiki https://github.com/NICTA/nationalmap/wiki, Handling issues with Cross Origin Resource Sharing (CORS).
