### ISSUE TITLE
Lots of test failures in IE9

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1193]
Even though TerriaJS works reasonably well in IE9, the test suite shows over 50 test failures.

Some problems I can see at a glance:
- We use `console.warn`, but in IE9 no console methods are available unless the debugger is open.  We work around this for `console.log` by adding it in `Terria.js` if it doesn't already exist.  We should do the same for `warn`.
- The tests for `EarthGravityModel1996` are timing out, probably because that class uses `ArrayBuffer`, which is not supported in IE9.  But since that class is only used with Cesium anyway, we should probably just exclude these tests in IE9.
- A bunch of "access denied" errors in `CsvCatalogItem` tests.  I'm not sure what we're being denied access to.
- And more...

**Comment by kring** [comment]
There are also four test failures in IE10 and three in IE11.

**Comment by kring** [comment]
All tests pass in MS Edge, FWIW.

**Comment by tephenavies** [comment]
I just tested on IE11 and only got 2 errors:
- CsvCatalogItem respects tableStyle color ramping for regions
- KmlCatalogItem error handling fails gracefully when the provided string is not XML

I tried to look further into the second with IE's debugger, but the debugger just decided to take 3 GB of RAM and then crash rather than stop at a breakpoint. The failure is probably because the [error is not of type `ModelError`](https://github.com/TerriaJS/terriajs/blob/5949a5c05a0c43e3a8c75c4493859b70caff42dc/test/Models/KmlCatalogItemSpec.js#L122).
