### ISSUE TITLE
Region mapped csv with no values column should use the same color for every region

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1356]
Similar to #791, but for region mapped CSVs. Currently, adding a region mapped csv with no values crashes Terria with the error: `TypeError: Cannot read property 'getColorArrayFromValue' of undefined`.

Every region should be the same colour for parity with lat-lon csv & GeoJSON and also to differentiate between user data being displayed and regions being displayed. The colour should be determined from `lib/Core/colorPalette.js`

**Comment by RacingTadpole** [comment]
From @steve9164:
There's a test in `CsvCatalogItemSpec` that tests region mapped CSVs with no data variable. The test passes, but dragging and dropping the exact file onto the map fails.

Paraphrasing - the reason is that it only reads the data from csv and checks the table is correct. To check the whole load process, we'd also need to check that legends work, which requires `csvItem.regionMapping.enable()` (which only some specs do).

Should this be called in each test just in case there is a problem creating the legend or something else past loading the data into a table?

**Comment by RacingTadpole** [comment]
In fact it might be nicer to replace all the calls:

```
csvItem.regionMapping.enable();
```

with

```
csvItem.isEnabled = true;
```

which has the same effect.

I think if there's any possibility of the legend stuff failing for a spec, we should add that line into it. Certainly adding it to the spec `handles region-mapped CSVs with no data variable` makes it fail, which is what we want.

**Comment by tephenavies** [comment]
This issue it not fixed. #1338 makes csvs with at least 1 numerical values column work, such as lat/lon:

```
Lat,Lon
-30,151
-28,150
```

where `"Lat"` is used as the values column, or region mapped where the regions happen to be referenced numerically such as SA4 codes:

```
SA4
101
102
103
104
```

But a csv file with no numerical columns still doesn't work such as:

```
State
NSW
Victoria
Queensland
South Australia
```

`ckmeans` is called on the numerical column, but (I'm pretty sure) the outcome of the colour binning isn't used. `ckmeans` should not be called at all (nor any other statistical methods) when a csv with no values column is displayed.

**Comment by stevage** [comment]
[Test case](http://nationalmap.gov.au/#clean&https://gist.githubusercontent.com/stevage/057f91ea30019cc7a1f74a215e9bc71c/raw/9982b3120fd824853ffc9e63eebe06594b83a2e6/bug1356.json)

**Comment by RacingTadpole** [comment]
That test case works ok in the latest version, so I'll close this issue. 
![image](https://cloud.githubusercontent.com/assets/1757858/22962735/ffc7e768-f3a2-11e6-9425-6cc24035a83a.png)
Though we should get rid of the unused "Display Variable" text on the left.
