### ISSUE TITLE
Missing list of catalog items that will not be shared

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1367]
I find it very easy to miss the warning that you actually will not be sharing your data here:

![image](https://cloud.githubusercontent.com/assets/1757858/13482538/067271a6-e142-11e5-8c96-80414e40c75d.png)

Can we make it stand out more, perhaps show it in red? I'd also suggest adding some space before the dot point.

**Comment by kring** [comment]
Looks like we don't show the list of catalog items that won't be shared _at all_ anymore. 😬 I updated the issue description accordingly.

**Comment by philipgrimmett** [comment]
ping @reginapramesti 

![terria - share note](https://user-images.githubusercontent.com/5292858/59587774-6541ab80-9129-11e9-918c-6b31f655bfce.jpg)

**Comment by reginapramesti** [comment]
![](https://user-images.githubusercontent.com/16102484/59983745-aaecff80-9666-11e9-8670-3ba1c2da9e7f.png)


Done the implementation but still requires reviewing. Some things to note:

* The list of CSVs that won't be shared currently just lists a bunch of `Unnamed Item`s. This should in theory be fixed by fixing #3399 
* Clicking `Remove` from the workbench doesn't get rid of the warning as it doesn't actually remove the data from the catalogue but simply removes it from the map. Though removing it from the `My Data` tab would get rid of the warning
