### ISSUE TITLE
Add Data uses WMS even when given a WFS URL

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1449]
From #1442.

Enter this URL in Add Data:
https://www.sciencebase.gov/catalogMaps/mapping/ows/5342c5fce4b0aa151574a8ed?service=WFS&version=1.1.0&request=GetCapabilities

And TerriaJS chooses to access it via WMS instead of WFS as expected.  Even though the base URL (`https://www.sciencebase.gov/catalogMaps/mapping/ows/5342c5fce4b0aa151574a8ed`) supports both WMS and WFS, the user's clear intention here is to use WFS and we should honor this.  I'm fairly sure this used to work, not sure when it broke.

**Comment by stevage** [comment]
Ok, I probably broke that when I simplified some of the add data code. The explicit detection of WFS in the URL was a behaviour I didn't notice (and hence retain). 

To spell out what's happening, our process is just "throw every catalog type at the URL and see if any of them work". Since WmsCatalogItem drops all URL parameters, it is able to use the base of the given URL as a WMS endpoint.

Two options here:

1) WmsCatalogItem could refuse to open a URL that contains a `service=` which is not WMS. (Which would make it fall through to WFS...)
2) We could re-add the explicit detection of WFS.

I think I prefer option 1.

**Comment by nf-s** [comment]
This is now working
