### ISSUE TITLE
Is there a way to add/configure terrain in TerriaJS?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1465]
We are experimenting with the AGI cloud-hosted terrain services, and this code works in the Sandbox at http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases:

```
var viewer = new Cesium.Viewer('cesiumContainer');

var layers = viewer.imageryLayers;
layers.addImageryProvider(Cesium.createTileMapServiceImageryProvider({
    url : 'http://agi-tas-demo.s3-website-us-east-1.amazonaws.com/SandwichOrtho/TILES/caco_f1_rgb1_v4_ortho_TILES/',
    credit : 'USGS'}));

var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : 'http://stkdesktop.agi.com/stk-terrain/v1/tilesets/CacoSample/tiles',
    requestWaterMask : true,
    requestVertexNormals : true
});
viewer.terrainProvider = cesiumTerrainProviderMeshes;
```

but how would I configure this to view in TerriaJS?

BTW, this terrain and orthophoto were both collected by a drone flying over the National Seashore on Cape Cod, Massachusetts:
![2016-04-22_10-30-31](https://cloud.githubusercontent.com/assets/1872600/14744701/d8e9fb86-0875-11e6-95d3-014327d8f3a3.jpg)
![2016-04-22_10-31-06](https://cloud.githubusercontent.com/assets/1872600/14744703/db0e4570-0875-11e6-9fb7-bbe235b9b4d6.jpg)
![2016-04-22_10-23-28](https://cloud.githubusercontent.com/assets/1872600/14744704/dcbaaae4-0875-11e6-9fd9-cb3a9086a837.jpg)

**Comment by kring** [comment]
@keattang opened a pull request awhile ago to add a `TerrainCatalogItem` to TerriaJS (#826).  It's a bit different from other catalog items in that only one can be active at a time (because Cesium only allows one terrain provider at a time).  I'll tweak that PR a bit and merge it and it should work pretty well in this scenario.

**Comment by rsignell-usgs** [comment]
Todd at AGI made us a simple Cesium app:
http://agi-tas-demo.s3-website-us-east-1.amazonaws.com/USGS/

@kring, should we go ahead and share that app with folks, or should we hold off a bit and see if we can give them a TerriaJS link?

**Comment by kring** [comment]
@rsignell-usgs you can check out the [terrain-item](https://github.com/TerriaJS/terriajs/tree/terrain-item) branch to see where I am so far.  Build it with NationalMap's master branch and then visit `http://localhost:3001/#build/TerriaJS/test/init/terrain.json` and look for the Terrain group at the bottom.

The performance is still much worse than pure Cesium when zoomed in close, and I'm trying to figure out why.  All of the time is spent inside Cesium, so I don't think it's that TerriaJS is doing something extra.  Most likely the cause is that we don't (currently) remove Cesium's debug code when we build it for TerriaJS, and it seems to make a big difference in this case.  I expect to have this worked out in the next day or two, but I certainly don't mind if you want to pass around Todd's sample app in the meantime.

**Comment by kring** [comment]
Turns out the performance problem was mostly a false alarm.  It was caused by the particular way we build when using `gulp watch`: in order to get faster builds in this development-only mode, all the code is loaded into the browser via `eval` calls, which disables some critical optimizations.  A regular `gulp` or a `gulp release` produces a build that is just as fast as Cesium alone.

**Comment by rsignell-usgs** [comment]
Phew!

**Comment by stevage** [comment]
Anyway, the answer to the question is yes: https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CesiumTerrainCatalogItem.js
