### ISSUE TITLE
Touchpad panning lost after using touchscreen pinch zoom or pan, in 3d mode

### ISSUE THREAD

**Issue by antrinna** [TerriaJS/terriajs#1508]
Panning around using laptop touchpad works well in 3D View (Smooth or Terrain) at the initial page load.
Once a touchscreen is used for panning or pinch zoom on the same map - panning via touchpad no longer works. Other navigation via touchpad doesn't seem to change: double-tap zoom or double-finger slide zoom work before and after; pinch zoom does not work either before or after.
In 2D View both touchpad and touchscreen work for panning, zooming, etc, including pinch-zoom.
System specs: Chrome 50.0.2661.94 m, Windows 10 Home, HP Spectre.

**Comment by kring** [comment]
This is a Cesium problem, sort of.  Cesium has logic that purposely stops listening to mouse input events as soon as a touch event is received.  It does this because touch devices typically send mouse events too, and if Cesium listened to both it would have to filter out the duplicates.

The recommendation I've previously seen is to use a [Pointer Events polyfill](https://github.com/jquery/PEP) in your application.  With this installed, Cesium will only handle Pointer Events and the polyfill will generate them in a sensible way for both mouse and touch events, solving the problem.

If you try it, let me know how it goes and we made add the polyfill to NationalMap and our other TerriaJS apps.

**Comment by kring** [comment]
This issue has been fixed in Cesium.
