### ISSUE TITLE
Picking the first legend for WMS isn't always right

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1513]
Sometimes this happens:
1. Layer has a default style, which is not the first in the list
2. When we load GetCaps, we get the legend from the first style (which includes a PALETTE parameter)
3. When we request tiles, we don't pass that parameter, and get the first style.

Hence: a legend that doesn't match the tile style.

http://nationalmap.research.nicta.com.au/#share=CAot5S

**Comment by rdengate** [comment]
This might be fixed with https://github.com/TerriaJS/terriajs/pull/1619? It no longer picks the first style if style is specified in the config file. For example, GEOGLAM now specifies 

```
"parameters": {
   "styles": "boxfill/csiro_anomaly"
},
```

and picks up the correct legend graphic.

**Comment by stevage** [comment]
Are you able to test the share link above?

**Comment by rdengate** [comment]
Yeah, that's the same problem I was seeing in GEOGLAM.

**Comment by rsignell-usgs** [comment]
Unfortunately, yes, TerriaJS still has this problem.    Here's [a "share" URL example](http://tinyurl.com/ktffyq5) that demonstrates TerriaJS incorrectly picking the first legend on the `getCapabilities` list, which is `boxfilll/spectral` , while the right legend for the WMS image being displayed is clearly `boxfill/rainbow`, as shown below. 

Incorrect automatic selection of legend by TerriaJS:
![2017-03-31_10-44-25](https://cloud.githubusercontent.com/assets/1872600/24587458/1a40e54e-1785-11e7-88d1-50582ece8bbd.jpg)


Correct legend, obtained by *user selecting* `boxfill/rainbow`:
![2017-03-31_10-45-20](https://cloud.githubusercontent.com/assets/1872600/24587460/202fa026-1785-11e7-9736-68af2a130653.jpg)

@kring, Can this please be added to https://github.com/TerriaJS/terriajs/milestone/22 ?

**Comment by kring** [comment]
The deal here is:
1. The WMS spec says that `style` is optional, and, if it's not specified, the server will use a default style.
2. The WMS spec doesn't state which style is the default, nor does it provide a way to ask the server. In fact, it explicitly says not to assume that the first style is the default style.
3. Most WMS servers use the first style as the default style, so if you must make an assumption about which style is the default, it's reasonable to choose the first one, in spite of what the spec says.
4. When the style hasn't been explicitly selected in the init file or in the UI, TerriaJS currently does not specify a style at all, leaving the server to choose its default.
5. In order to show a legend at all in this scenario, TerriaJS must make an assumption about which style is the default style.

As far as I can see, the only way we can avoid this "bug" (other than changing the WMS spec to allow a client to determine which style is the default one) is by attacking it at point 4. If TerriaJS always specified a style in calls to both `GetMap` and `GetLegendGraphic`, then we could be sure they'd always be in sync without the need to make an assumption about which style is the default one.

**Comment by nf-s** [comment]
I think I have sorted this issue by just requesting `GetLegendGraphic` without the `style` parameter.

From OGC &mdash; about `style` property for `GetLegendGraphic` request:

> Style of layer for which to produce legend graphic. **If not present, the default style is selected.** The style may be any valid style available for a layer, including non-SLD internally-defined styles.

See PR https://github.com/TerriaJS/terriajs/pull/4923

**Comment by nf-s** [comment]
This has been fixed in v8
