### ISSUE TITLE
Legend and coloring of ENUM columns improvements reduce functionality

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/terriajs#1538]
The fixes implemented in https://github.com/TerriaJS/terriajs/pull/1384 have removed the ability to distinguish more than 8 string encoded variables.  Eg in the attached file, the column RDA_NAME is the display column for colouring (unsophisticated and n-color unaware as it is), and only displaying 8 of the 55 regions isn't sufficient.  Maybe we need to think harder about the algorithm to choose bins - perhaps {colorBins: 9} is overly prescriptive, and maybe should only be applied when row-count = unique-values?

Can we discuss, in light of requirements for ABR, as I've now run into this problem too!!

![image](https://cloud.githubusercontent.com/assets/4373945/15288265/a0f32816-1bac-11e6-9756-4ddd7b89830e.png)

[RDA_LGA_2015_16.txt](https://github.com/TerriaJS/terriajs/files/266007/RDA_LGA_2015_16.txt)

**Comment by RacingTadpole** [comment]
Yes, let's discuss. What do you think should happen in this case?
@stevage and I have laid out some options and their pros and cons in https://github.com/TerriaJS/terriajs/issues/1374.
Rereading that, I see we planned to colour the first 20 differently, but I actually implemented only 8 colours (plus "other").
That's a mistake. Would bringing it up to 20 solve the problem?

**Comment by tobybellwood** [comment]
In these cases, 20 wouldn't solve it either.  I think setting an arbitrary limit when one isn't strictly needed limits the functionality.  Obv when uniquevalues=rows there is no point in differentiating them (at all?) but how hard computationally would it to be check for this edge case to avoid the overhead of colouring?

I'm fine with limiting the legend display to 8/x values with an "others", but think the polygons need colouring.

**Comment by RacingTadpole** [comment]
Thanks Toby. Am I right that you're recommending using as many distinct colours as we need to show every RDA_NAME with a different colour, without limit? But how do we show that on the legend (do we just list out the first X and have a blank box next to Others)? I'm also not sure where we'd find a suitable colour palette - I found one [here](http://www.iscc.org/pdf/PC54_1724_001.pdf) for about 20 high-contrast colours. Or we could interpolate a ColorBrewer palette, but it will be hard to distinguish the fine grades of colours.

Or, are you recommending cycling through our list of 8 (or 20) colours once we run out? ... which means the legend will not be right (eg. in the example above, the legend will still say red = wheatbelt, but on the map, red will be used for other RDA_NAMES too)?

@philipgrimmett do you have any thoughts from a design perspective?

**Comment by stevage** [comment]
I think we need to handle two cases separately:
- When there are more than X rows with the most common value (eg, when every value is unique), then we should colour them all the same
- When there are many values, but some are more common than others, we can colour the top X individually, and colour the rest the same. (Our current behaviour, X=8)

**Comment by tobybellwood** [comment]
Where x(unique rows) = n(total rows), color all the same

The exception is the crux of the issue - I don't think we can place an arbitrary value on coloring x, when it isn't customisable by the end user.  My view is that as long as x<n, all x groups should be colored independently.

If the quantity is greater than say 12 (upper limit of colorbrewer qualitative), the legend is most likely unimportant/not needed for identification, and those colors can be cycled through - we shouldn't be displaying a 500 item legend if it's not helpful.

**Comment by kring** [comment]
@tobybellwood if I'm understanding you correctly, we want this:
1. If _every_ row has a unique value, color all regions the same and display a legend with just one row indicating that that color belongs to that dataset.
2. If the number of unique values is less than or equal to the maximum number of unique qualitative colors we have available (12 I think), color each unique value and show it in the legend.
3. If the number of unique values is less than the number of rows but is more than the number of colors available, give every value a (non-unique) color by cycling through the palette, and make the legend a box with the whole palette draped through it and a label saying "Various values".

Does that sound ok?

**Comment by kring** [comment]
Would it be sensible to use the behavior in 3 above when every row has a unique value, too?

**Comment by tobybellwood** [comment]
Agree with that proposal and as for merging 1 and 3, I'd say so - that'll reduce the amount of exceptions to handle.

**Comment by kring** [comment]
How's this look:
![image](https://cloud.githubusercontent.com/assets/924374/15886169/cae0ffe6-2d9e-11e6-881c-b2e88a8dfb43.png)

Totally useless legend, but that's the way it goes I think.

**Comment by tobybellwood** [comment]
looks good - (well, looks similar to how it's supposed to...)
![image](https://cloud.githubusercontent.com/assets/4373945/15888488/668ecc38-2daa-11e6-8ed4-1139a79a1c7f.png)

**Comment by kring** [comment]
Better legend?

![image](https://cloud.githubusercontent.com/assets/924374/15919590/2560a1ee-2e56-11e6-9c90-3d69ba728c76.png)

**Comment by tobybellwood** [comment]
looks really good!

**Comment by stevage** [comment]
> If the number of unique values is less than the number of rows but is more than the number of colors available, give every value a (non-unique) color by cycling through the palette, and make the legend a box with the whole palette draped through it and a label saying "Various values".

I don't understand the thinking here. Basically, it means randomly assigning the same color to different values. This is maybe ok in specific cases where you're essentially faking a 6-color algorithim, but has the potential to be horribly misleading, since it's totally possible that neighbouring regions will get the same colour. It will also give really bad results when the number of unique values is only slightly greater than the number of colours, so one color will apply to both the most frequent value and the least frequent value, for instance (if 13 unique values).

IMHO our current approach in this situation is correct: assign unique colors to the most frequent values, and assign a single, distinctive (probably grey) color to all other values.

Perhaps for cases where people actually want the random cycling behaviour, that should be set as a `tableStyle` flag.

**Comment by kring** [comment]
Ok just about wrapping this thing up, here's the last question.  Is it ok with you if this is _not_ the default behavior?    By default you'll get the `Other` item in the legend when there are more unique values than legend colors available (the number of legend colors available has been increased to 21).  However, if you put `"colorBinMethod": "cycle"` in the init file, AND have more unique values than colors, you'll get a legend like the one above and we'll cycle through the colors.

Two reasons:
1. backward compatibility, and
2. because we feel like this cycling behavior is a bit weird.  It creates a pretty useless legend, of course, but it also creates kind of a weird map.  It's almost like the goal is a [4-color map](https://en.wikipedia.org/wiki/Four_color_theorem) but it doesn't actually achieve that.  Adjacent regions with different values may have the same color.

**Comment by kring** [comment]
@stevage you just said what I tried to say, only you did it much more eloquently.  Thanks.

**Comment by stevage** [comment]
Great minds :) I suggest a new attribute though, as this is independent of the color bin method. Maybe `reuseColors: true` ?

**Comment by kring** [comment]
yeah I had that originally, and then saw internally that there's a `colorBinMethod` called `top` which is our current method for enums.  So I kind of just exposed that publicly and added another for enums.

```
    /**
     * The method for quantising colors:
     *  * For numeric columns: "auto" (default), "ckmeans", "quantile" or "none" (equivalent to colorBins: 0).
     *  * For enumerated columns: "auto" (default), "top", or "cycle"
     * @type {String}
     */
    this.colorBinMethod = defaultValue(options.colorBinMethod, 'auto');
```

`auto` is always `top` at the moment, but we might do smarter things in the future.

**Comment by tobybellwood** [comment]
IMHO, having a case where the colouring is totally useless (with a vast swathe of "other") is more misleading than the potential for neighbouring attributes to be coloured the same.  I agree that it is a bit weird, but it's something that's been stumbled across twice now.

So with these changes as is, would the default behaviour for enum columns (in drag and drop & CKAN csv's) to cycle or to colour N only? My preference would be to cycle, and have the option to auto or top in catalogs, where the user has more control?

**Comment by kring** [comment]
@tobybellwood I don't agree that "Other" is more misleading.  You can argue it's not useful perhaps, but I think it's quite a lot less misleading.  We can make it even less misleading by display "15 other values" rather than just "Other" in the legend, maybe.

My proposal is that a drag/dropped CSV will default to coloring the most common 21 only.  We could eventually add UI to let the user change this, but for now it would have to be done via an init file.

**Comment by tobybellwood** [comment]
Thanks for the input as always! I'm happy to have the code in place, if not the default, but I'll have a chat with the org that requested it initially - they should be able to use their catalog to implement the cycle option, and we'll just put up with it in drag'n'drop until we can UI the solution.  Having a "colour all" option  on these specific legend items would obviously fix this on the spot for people that needed it.

**Comment by kring** [comment]
Yeah I think that other org should be fine either way because they're driving NM via an init file pushed in with `postMessage`.  I'll write an issue for the UI.
