### ISSUE TITLE
Newui: Safari 6.1.6 doesn't display map

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1565]
On my home Mac, which is running an old OS, 10.7.5, which is no longer supported, and therefore an old Safari, 6.1.6, the new UI (terriamap tag 2016-05-18) falls back to 2D and then does not display a map at all - only grey.
There is one exception before it presents the alert saying it will fall back to 2D, in events.js here:

```
console.error('(node) warning: possible EventEmitter memory ' +
                    'leak detected. %d listeners added. ' +
                    'Use emitter.setMaxListeners() to increase limit.',
                    this._events[type].length);
```

The 2D map appears fine on the old UI national map 2016-05-13c.
It also appears fine on the new UI in Firefox 46.0.1.

**Comment by kring** [comment]
With any luck, @AlexGilleran's recent changes to make it work in IE9 will make it work on this old Safari version too.

**Comment by chloeleichen** [comment]
Still no map on Safari 6,
![bs_maclion_safari_6 0 1](https://cloud.githubusercontent.com/assets/7508939/17046731/d2d7d8f8-5019-11e6-8bc7-62471e8004df.jpg)

and it is because the height of the map is 0

Also there are so many other styling problems in Safari 6, should we try to fix everything? @kring

**Comment by kring** [comment]
Looks like Safari 6 last got a security patch in 2015, so I think we can safely drop support for it.
