### ISSUE TITLE
IE11 squashes map

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1603]
@tobybellwood commented on [Fri Jun 03 2016](https://github.com/TerriaJS/NationalMap-Feedback/issues/42)

Reported by ABS(FontAwesome issues too) and AFSA:
![image](https://cloud.githubusercontent.com/assets/4373945/15773452/462e402a-29ba-11e6-8337-ad4861f19ace.jpeg)
![image](https://cloud.githubusercontent.com/assets/4373945/15773454/46897d5a-29ba-11e6-8379-941a9122b1de.gif)

---

@kring commented on [Tue Jun 07 2016](https://github.com/TerriaJS/NationalMap-Feedback/issues/42#issuecomment-224203294)

@chloeleichen can you take a look at this one?  I've determined that the problem is that IE11 (but not IE9!) is ignoring the `height: 100%` in this style in `standard-user-interface.scss`:

``` css
.map__row {
  display: table-row;

  &:first-child {
    height: 100%;
  }
}
```

But I'm at a loss as to how to fix / work around it.

**Comment by AlexGilleran** [comment]
I'll take it!

**Comment by kring** [comment]
@chloeleichen was looking at it earlier this morning and suggested using `100vh` instead of `100%`.  I'm happy for you to take it from there @AlexGilleran. :)

**Comment by AlexGilleran** [comment]
Yeah that solves it up until you want the chart/timeline to pop in at the bottom :(. Gonna investigate writing some javascript to bring IE9-11 into line with how it works everywhere else.

**Comment by chloeleichen** [comment]
```
display: inline-block;
position: absolute;
```

Also work

**Comment by AlexGilleran** [comment]
On which element? 😬

**Comment by chloeleichen** [comment]
`map-cell`

**Comment by AlexGilleran** [comment]
I found that that got very close but the bottom of the map would still come up underneath the timeline rather than resizing, although I might have messed something else up at the time 😬 .

Anyway I've committed a fix to newui that involves polyfilling the right CSS behaviour into IE9-11 with JS but leaving it out for Chrome/FF/Safari/Edge which handle it properly without CSS.

Feel free to have a crack at doing it without JS Chloe but it's pretty annoying :(.
