### ISSUE TITLE
Provide some common data formatting functions for use in mustache templates

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1606]
There are some common formatting functions which would be useful from within mustache templates, such as the ability to format numbers with commas as a thousands separator, adding decimal places, etc. Currently it is possible to format some values via the init.json file, but this becomes complicated quickly when you have json data being passed to the mustache template (for example, an object with an array of objects where a certain key in each of these objects is a number doesn't have a clear path to all of these numbers).

After speaking with @RacingTadpole,it seems the easiest things to do is provide some functions under the `terria` which is already being used for `lat/lon` data, for example `{{#terria.numberWithThouComma}}{{myNum}}{{/terria.numberWithThouComma}}` (see https://github.com/janl/mustache.js#functions). I'm not sure what other formatting functions would be useful, but hopefully they can be added as needed once the functionality is there.

The major benefit of having these functions available in the mustache template is that we can work with raw data which can be charted, but also provide, for example, tables with the data formatted nicely. Currently by the time a value is passed to the template it has been formatted via the init.json, meaning it cannot be used to produce a chart inline.

**Comment by RacingTadpole** [comment]
Note we discussed (and dismissed) extending the existing formatting ability, which uses a json init file like so:
`"formats": {
      "something": {"useGrouping": true}
    }`
This has the advantage of applying to templates and to legends. But Alex wants to apply formatting to the innards of arrays and objects, which will never appear in a legend.

If we wanted to extend the current `formats` approach to work with arrays and objects, we could go with something like this:
- Extending to arrays of numbers  (if `something` is an array of numbers in the above example, it applies the format to its elements). 
- Objects could work with dot-notation, eg. `"something.rgb": { "useGrouping": true}`.
- Arrays of objects… could work with the two above ideas, ie. `something.rgb` would apply to the `rgb` property of every element in the array `something`...

But this looks hard to implement and ambiguous to interpret. Hence the pre-packaged formatting function idea looks better. Especially since we have already got a special `terria` property we can add it to.

**Comment by RacingTadpole** [comment]
Just thinking about this some more. Two subtleties:
- How to provide the argument (eg. 3) to `maximumFractionDigits`?
- What if you want to specify a few formatting options at once, eg. `useGrouping` and `maximumFractionDigits: 3`; and maybe `"style": "percent"`. Nesting these functions may not do the same thing.

(Btw I don't like these names, but it's what JS's [Number class](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) uses, and we're already using them in `formats`, so I think it makes sense to reuse them rather than invent new ones.)

The first could be handled easily enough by including it inside the tag body, with a suitable delimiter eg.
`{{#terria.format.maximumFractionDigits}}3:{{myNum}}{{/terria.format.maximumFractionDigits}}`.

But maybe a more general solution to both problems would be to put all the options in the body, eg.
`{{#terria.formatNumber}}{"useGrouping": true, "maximumFractionDigits": 3}{{myNum}}{{/terria.formatNumber}}`

Is that too unwieldy? JSON's awesome requirement for quotes makes this worse than I imagined. Maybe that could be optional, at risk of further potential confusion.

**Comment by axman6** [comment]
yeah this is tough, I'd thought about the case where you'd want commas and two decimal places, without having a specific function for each. The text passed to the function need not actually be JSON though, since the function only gets passed the string between, so we could come up with whatever syntax we'd like: `{{#terria.formatNumber}}useGrouping=true,maximumFractionDigits=3:{{myNum}}{{/terria.formatNumber}}` might be pretty easy to parse (I assume we can do something better than using regexes in JS right? writing a parser combinator library would make this possible in a few lines in other (unnamed) languages)
