### ISSUE TITLE
Move catalog search to webworker (maybe)

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1688]
This was listed under #1427, which we are closing.

**Comment by kring** [comment]
I don't think this will help us much, because:
* passing complicated data structures (e.g. catalog items) between workers and the main thread is pretty slow
* most of the slowness of the search comes from loading and parsing data from remote servers, and I can't think of how to use web workers to make this faster.
So I'm going to close this, but of course re-open if there's something here I've missed.
