### ISSUE TITLE
Truncated charts for some data

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1890]
Some charts that are generated for a GEOGLAM WPS process are displaying only a subset. If expand is pressed, the whole chart can be viewed.

To reproduce:
1. Go to http://newui.map.geo-rapp.org/
2. Add data
3. In point location enter: 22.851562500000004,-8.407168163601076
4. Select 'modis-fractcover-global-monthly-files' in the dropdown (even if it's already selected. This is a bug. Working on it)
5. Run Analysis
6. When the analysis returns, note the strangely truncated chart in the workbench.

**Comment by kring** [comment]
@meh9 do you know if this is still an issue?  I can't follow the procedure above exactly anymore (there's no dropdown, and I can't enter coordinates directly), but clicking a random point seems to work ok, at least. I'm going to close this because it's old and hopefully no longer relevant, but please re-open if I'm wrong.

**Comment by meh9** [comment]
No I don't think it's a problem any more.
