### ISSUE TITLE
WPS point selection broken in terriajs#master

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1933]
When trying to use WPS with a point location parameter, clicking `Select location` and then clicking a point on the globe returns you to the WPS function screen but no point lat/lon is entered in the location text field.

In addition, the `contextItem` for the WPS function is displayed when viewing the function in the catalogue window, but when clicking `Select location` it is turned off, and only reappears when the catalogue window returns.

**Comment by RacingTadpole** [comment]
Yes, for me the analysis study area also flickers but then disappears during the selection now too (unless I explicitly select it first, but even then its opacity changes).

**Comment by RacingTadpole** [comment]
When I click Select Locaation and then click on a point on the map, I get a caught exception:

> warning.js:44 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the PointParameterEditor component.

It's happening because `PointParameterEditor.selectPointOnMap` sets the state [here](https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViews/Analytics/PointParameterEditor.jsx#L74), and in the meantime it has been unmounted.

**Comment by RacingTadpole** [comment]
Ah, `PointParameterEditor` is unmounted because of [this recent change to `ExplorerWindow.jsx`](https://github.com/TerriaJS/terriajs/commit/9b95887659047d6f3224f19bc2b0aa6f1f6e9382#diff-63b19ca1771d2ea0afe4b845a9bdfe63R72).

A solution is to take responsibility for `parameterValues` off `InvokeFunction` and give it to `WebProcessingServiceCatalogFunction`.
