### ISSUE TITLE
Proxying tile requests that start with // doesn't work right

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1964]
In Parlmap, I'm seeing this error browser-side when switching to Positron:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2016-08-18 10:48:36.887 http://localhost:3005/proxy///cartodb-basemaps-d.global.ssl.fastly.net/light_all/3/0/0.png 
```

Notice the URL it tries to resolve starts with `//` which doesn't really make sense outside the browser context, I believe.

The server complains:

```
Error: Invalid URI "http:///cartodb-basemaps-b.global.ssl.fastly.net/light_all/3/0/0.png"
    at Request.init (/Users/stevebennett/odev/nicta/nationalmap/parlmap/node_modules/request/request.js:288:31)
```

The workaround is to add fastly.net to `corsDomains` so it doesn't get proxied at all. (For that matter, do we actually need to proxy these tile requests? They don't seem to be XHRs.)

**Comment by stevage** [comment]
(Ok, the actual cause of me seeing this was failing to pass the config file to terriajs-server, so it was trying and failing to act as an open proxy. So, there's no actual impact here at the moment, but it's still a bug I think.)

**Comment by kring** [comment]
`CorsProxy` should probably swap in an `https` when the protocol is unspecified. It's a pretty minor issue, though, because the world is moving toward just always using https rather than the `//` trick. So I think I'll close this, it's a quick thing to add if we ever have a real reason to do so and we won't need this issue to remind us to do so.
