### ISSUE TITLE
XSS Prevention (Don't Do the Harlem Shake)

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1968]
So the Troy Hunt course introduced us to a bunch of cutting edge XSS-prevention techniques like HSTS - we should look into adding some, especially given that we've got some pretty wide potential XSS vectors (literally allowing users to embed their own HTML into the page).

**Comment by AlexGilleran** [comment]
Relevant: https://www.youtube.com/watch?v=K0noqLisW_c

**Comment by RacingTadpole** [comment]
Yes, and a Content-Security-Policy header.

**Comment by nahidakbar** [comment]
why =( what do you have against the harlem shake?

**Comment by kring** [comment]
I'm closing this because:
*  HTTP Strict-Transport-Security is sensible for any site supporting HTTPS, but does not require a change to TerriaJS itself.
* A Content-Security-Policy header is fairly unworkable, considering that a Terria Map commonly talks to geospatial servers running on all sorts of domains, some of them (e.g. ArcGIS servers) using JSONP. If someone wants a high-security TerriaJS map that limits access to a specific list of servers, they can configure their web server accordingly. No change to TerriaJS is required.
* We take pains to sanitize any untrusted HTML that we display, so a XSS attack should be difficult or (hopefully) impossible even without HSTS or CSP.
