### ISSUE TITLE
Choose vectors as default style from ncWMS group layer endpoints

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1977]
For ncWMS2 endpoints, the default style should be `default-vector/default` for any layer with a name that ends with `face-group`, for example:  

http://geoport.whoi.edu/ncWMS2/wms?FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=default-vector%2Fdefault&LAYERS=COAWST-Forecast%2Fu%3Aface%3Av%3Aface-group&TIME=2016-08-22T14%3A00%3A00.000Z&ELEVATION=-0.03125&COLORSCALERANGE=0%2C0.5&NUMCOLORBANDS=250&ABOVEMAXCOLOR=0x000000&BELOWMINCOLOR=0x000000&BGCOLOR=transparent&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=-73.353765186635,38.410772530379,-71.177311414933,40.58722630208&WIDTH=256&HEIGHT=256

@guygriffiths, this is correct, right?

**Comment by guygriffiths** [comment]
I think I would use either the first style advertised in the capabilities document (which should be `default-vector/default` for vector styles), or just `default/default` for a fallback which will always work (although it is never advertised in the capabilities document).  That way it's not tied to the layer name at all (which should work, but is a consequence of the design, rather than a deliberate part of the design).

**Comment by rsignell-usgs** [comment]
@guygriffiths , ah, got it, thanks!  That will be better indeed.

**Comment by kring** [comment]
@rsignell-usgs @guygriffiths TerriaJS currently does not specify the style at all, by default.  i.e. it adds `styles=` to the URL.  On an ncWMS2 server, is that different from explicitly specifying the first style?

**Comment by guygriffiths** [comment]
@kring - That's also fine, and will choose the default style on ncWMS2

**Comment by rsignell-usgs** [comment]
Well, I guess this is a non-issue then!    Closing!
