### ISSUE TITLE
Zoom Rectangle and WPS Rectangle parameter: rectangle entity doesn't display in cesium viewer

### ISSUE THREAD

**Issue by sppigot** [TerriaJS/terriajs#2084]
Works ok in Leaflet but the rectangle entity doesn't display in Cesium. 

To test: try and draw a rectangle on the globe using left-mouse+shift and drag. After you start, the rectangle doesn't appear though if you continue and let the left-mouse button up, a zoom to the rectangle you have defined does takes place. 

Seems to be a problem after the code changed to use entity in terria.dataSources instead of adding a rectangle primitive directly to the scene in lib/Map/DrawExtentHelper.js ?

Using 4.2.0 tag of terriajs with aremi.

**Comment by sppigot** [comment]
This is kind of bugging me - have tried different entities, even went back to creating primitives and adding them to the scene directly - nothing seems to work here (although with a GroundPrimitive I could get part of the rectangle to draw the first time I attempt to draw a rectangle as part of an extent or a bounding box wps parameter). Also puzzling is that other code using terria.dataSources (eg. UserDrawing.js) does work just fine?! For now, we're using the 2D Leaflet viewer (on awavea.csiro.au) as the default as that works well for those wanting to the test rectangle extraction for wave data.

**Comment by rdengate** [comment]
@sppigot thanks for the report. This relates to https://github.com/TerriaJS/terriajs/issues/1928 also. It turns out it is due to a bug in Cesium, but it's fixed in Cesium 1.25. I have published a new version of terriajs-cesium (v1.25.0) which terriajs will be upgraded to soon. A workaround is to set parameter height 0.0 when creating the rectangle, but once terriajs-cesium is upgraded that won't be needed.

**Comment by rdengate** [comment]
This is fixed now.
