### ISSUE TITLE
Share button generates a URL with invalid URL contains: CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by sppigot** [TerriaJS/terriajs#2102]
eg. {site_url}#share=s-CredentialsError: Missing credentials in config

Not sure why this is the case? Is this a local config problem? If so, why would credentials be needed. Will check further......

AREMI with TerriaJS 4.2.0

**Comment by sppigot** [comment]
Ah now I understand - by default the URL is shortened, unclicking the Shorten the share URL using a web service checkbox generated a useable URL. Makes sense that a web service might require credentials too. But perhaps the "Shorten the share URL using a web service" checkbox should be unchecked by default or missing if no credentials are supplied in the config.

**Comment by kring** [comment]
@sppigot that shorten checkbox should only be available if you have a share service configured in your devserverconfig.json (or similar file).  What map (e.g. nationalmap, TerriaMap, aremi-natmap) are you working from?

**Comment by kring** [comment]
Oh, I see, aremi-natmap has it configured in its serverconfig.json for some reason:
https://github.com/TerriaJS/aremi-natmap/blob/master/serverconfig.json#L33

The other maps generally add that at deploy time.  You can either remove all that `shareUrlPrefixes` stuff, or you can set up an S3 bucket and AWS access key and configure it accordingly.  Doc here:
https://github.com/TerriaJS/terriajs-server/blob/master/serverconfig.json.example#L63

I'm closing this because it's AREMI specific, not a TerriaJS problem.

**Comment by sppigot** [comment]
Thanks very much @kring - appreciate the help!
