### ISSUE TITLE
support for CARTO visualisations in NationalMap

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/terriajs#2144]
I've just been talking with CARTO here in Madrid.  Can we see how easy it is to add a visualisation to NationalMap - this may present users with a low-cost option for styling their data nicely, and us just connecting to it?

I've seen the reverse done (adding cesium as a basemap to CARTO) - https://cesium.cartodb.io/queensland.html, and they provide a Leaflet library (https://github.com/CartoDB/cartodb.js)

**Comment by kring** [comment]
@tobybellwood do you mean you want to show CARTO layers in TerriaJS?  If so, that should already be possible.  For example, we have CARTO's Positron and Dark Matter base maps in NationalMap.  Assuming other CARTO maps work the same way as Positron, you should also be able to add one through the NationalMap UI by selecting Open Street Map Server on the Add Web Data panel.

**Comment by tobybellwood** [comment]
That works for WMS/WMTS sources (available on the enterprise plans).  This would be to get the vector data, similar to the way it is handled in Leaflet. The wms methods https://carto.com/blog/wms-support/ are a little outdated I think

**Comment by kring** [comment]
I thiink I'm talking about connecting to the Maps API, not the WMS/WMTS service:
https://carto.com/docs/carto-engine/maps-api/

I'm not quite sure what to make of carto.js (based on only a quick review).  If it's just a javascript API to request tiles from the Maps API, we don't need it because TerriaJS can already do this natively.  If it's something more complicated (like client-side vector tile rendering like MapBox does), it will be more complicated.
