### ISSUE TITLE
Can't load sci-wms WMS endpoint

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2184]
I tried loading this sci-wms WMS endpoint:
http://sci-wms.whoi.edu/wms/datasets/necofs_gom3_forecast?service=WMS&request=GetCapabilities&version=1.3.0&tiled=true
into TerriaJS via "Add Data=>My Data=>Web Data=>WMS Server", and it balked with a "Group not Available" error:
![2016-10-20_13-15-56](https://cloud.githubusercontent.com/assets/1872600/19570389/c9e78226-96c7-11e6-9355-b4393b9207fd.png)

I have tested that CORS is enabled on the endpoint, so that's not the problem.  

Is this a bug, or is there is something non-standard in the sci-wms endpoint that terriaJS doesn't like?

**Comment by kring** [comment]
TerriaJS is failing to load this because the GetCapabilities has `LegendURL` elements without an actual URL:

```
<LegendURL height="500" width="100">
  <Format>image/png</Format>
</LegendURL>
```

I don't understand the DTD used by the spec well enough to say whether `OnlineResource` is actually required in a `LegendURL`, or if TerriaJS is wrong to expect that.  Here's the relevant part:

![image](https://cloud.githubusercontent.com/assets/924374/19581136/b4a98c42-9776-11e6-8361-a54acb30d288.png)

In any case, it's an easy change to make TerriaJS tolerant of this, so I'll do that.

**Comment by kring** [comment]
Once that's fixed, it next complains that there's a `Dimension` without any values:

```
<Dimension name="elevation" units="EPSG:5030" postive="up"/>
```

I'll change it to tolerate that, too.

**Comment by rsignell-usgs** [comment]
@kwilcox, would this also be relatively easy to add to the sci-wms getCaps?

**Comment by rsignell-usgs** [comment]
So turns out that the problem is that sci-wms only currently supports WMS 1.1.1 GetCaps.  
But when I tried adding the WMS 1.1.1 GetCaps to TerriaJS:
http://sci-wms.whoi.edu/wms/datasets?service=WMS&request=GetCapabilities&version=1.1.1
but I still get errors.   Should this work?

**Comment by kring** [comment]
You can't force WMS 1.1.1 just by putting that URL in Add Data.  You can set the `getCapabilitiesUrl` property of a WMS catalog item in the JSON init file, though.

But it shouldn't really matter.  WMS does version negotation.  So TerriaJS requests 1.3.0, and the server responds with "sorry, I can only do 1.1.1" and TerriaJS should either deal with that.  After my pull request (#2185) it seems to be working.
