### ISSUE TITLE
Issue loading Flynn from com_elb_name_2016 and com_elb_name_2011 layers

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/terriajs#2330]
Tried to load elb file - all load ok, except Flynn, and this happens in 2011 and 2016?

[test.csv.txt](https://github.com/TerriaJS/terriajs/files/706445/test.csv.txt)
[HouseTppByDivisionDownload-20499.csv.txt](https://github.com/TerriaJS/terriajs/files/706446/HouseTppByDivisionDownload-20499.csv.txt)

**Comment by tephenavies** [comment]
The issue was polygon self-intersections with the provided shapefiles when the layers were added. I've added a step to the vector tile generation process to make geometries valid (using Spatialite `MakeValid`) that should fix this issue for any future layers added.

Test for new vector tile server at: http://nationalmap-regionmapping-test.terria.io/

**Comment by tephenavies** [comment]
Fixed for production nationalmap by updating alias to new vector tile server.
