### ISSUE TITLE
Problem getting maps from this WMS endpoint

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2371]
When I try to add this WMS endpoint:

https://coastwatch.pfeg.noaa.gov/erddap/wms/jplMURSST41anommday/request?VERSION=1.3.0&request=GetCapabilities

I can select the dataset and layer to plot, but then when the getMap request is issued, I get:
```
TileProviderError: Failed to obtain image tile X: 5 Y: 6 Level: 4.
```
This is an example of a query that does work:

https://coastwatch.pfeg.noaa.gov/erddap/wms/jplMURSST41anommday/request?EXCEPTIONS=INIMAGE&VERSION=1.3.0&SRS=EPSG%3A4326&LAYERS=jplMURSST41anommday%3AsstAnom&TIME=2016-12-16T00%3A00%3A00Z&TRANSPARENT=true&BGCOLOR=0x808080&FORMAT=image%2Fpng&SERVICE=WMS&REQUEST=GetMap&STYLES=&BBOX=-180,-90,-26.4,63.6&WIDTH=256&HEIGHT=256

returning
![request](https://cloud.githubusercontent.com/assets/1872600/22898314/caa06eac-f1f4-11e6-9372-32a0b13bd135.png)

The screen grab shows the TerriaJS error:
![2017-02-13_13-54-17](https://cloud.githubusercontent.com/assets/1872600/22898200/5eaccbbe-f1f4-11e6-9402-ece1f410ed99.jpg)

**Comment by tephenavies** [comment]
I couldn't even add the WMS group. Looks like CORS is not enabled:
```
XMLHttpRequest cannot load [URL]. No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by kring** [comment]
Maybe try adding it to the proxy whitelist to confirm it works once that problem is out of the way?

**Comment by tephenavies** [comment]
After adding `"gov"` to my local proxy whitelist, I can add any of the coastline/land layers, but I get the same error for the "MUR" layers. This is because the WMS server is returning this error on tile requests:

```
<?xml version='1.0' encoding="UTF-8"?>
<ServiceExceptionReport version="1.3.0"
  xmlns="http://www.opengis.net/ogc"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
  <ServiceException>Query error: SRS=EPSG:3857 must be EPSG:4326.</ServiceException>
</ServiceExceptionReport>
```

The problem is that the WMS server doesn't support Web Mercator.

@kring Is there any way to add EPSG:4326 WMS layers?

**Comment by kring** [comment]
> Is there any way to add EPSG:4326 WMS layers?

Yes, but it will only work in 3D, not 2D, because Leaflet only supports Web Mercator.  Set `"tilingScheme": "geographic"` in an init file or `item.tilingScheme = new GeographicTilingScheme()` in code.

TerriaJS is also supposed to automatically use geographic (4326) if GetCapabilities reports that Web Mercator isn't supported.  Could be worth looking into why that isn't happening here.

**Comment by tephenavies** [comment]
The GetCapabilities doesn't mention EPSG:3857 at all, so the other layers must (?) be using EPSG 4326, and they're working. I'll look into it further.

**Comment by tephenavies** [comment]
USGS sure has some pretty datasets
![image](https://cloud.githubusercontent.com/assets/13863530/23006649/4d4c55f0-f457-11e6-9c6f-94128f404d3e.png)

**Comment by rsignell-usgs** [comment]
@steve9164 , I'm doing something wrong here, can you see the error?
https://github.com/USGS-CMG/terriajs-dive/blob/master/examples/erddap.json#L8-L15

http://gamone.whoi.edu/terriajs/#https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/erddap.json

**Comment by tephenavies** [comment]
The problem code is [here](https://github.com/TerriaJS/terriajs/blob/615721d/lib/Models/WebMapServiceCatalogItem.js#L797-L802). This is fixed in #2380.

**Comment by rsignell-usgs** [comment]
I tried to test this by editing my `package.json` to contain:
```
    "terriajs": "git://github.com/TerriaJS/terriajs.git#fix_WMS_CRS_inheritance",
```
and then did:
```
 1009  npm stop
 1010  killall node
 1011  history
 1012  rm -rf node_modules/terriajs
 1013  npm install
 1014  gulp
 1015  npm start
```
but this seemed to do things I didn't expect, like not loading my local config:
```
(ioos) usgs@gamone:~/github/TerriaMap> npm start

> terriajs-map@0.0.1 start /home/usgs/github/TerriaMap
> bash ./node_modules/terriajs-server/run_server.sh --config-file devserverconfig.json

TerriaJS Server 2.6.2
Using config file "/home/usgs/github/TerriaMap/devserverconfig.json".
Serving directory "/home/usgs/github/TerriaMap/wwwroot" on port 3001 to the world.
(TerriaJS-Server running with pid 7396)
Launching 40 worker processes.
```
I know my problem here doesn't belong in this thread, but it's 4:30pm on Friday afternoon.... :stuck_out_tongue_closed_eyes:

**Comment by kring** [comment]
That looks like it should work, I'm not sure why it wouldn't load the local config.  Any errors in the browser's console?  In case it helps, there are detailed instructions for setting up a TerriaJS development environment using npmgitdev here:
http://terria.io/Documentation/guide/contributing/development-environment/

Your approach should work too if you just want to use a branch of TerriaJS (instead of being able to modify it), but it's something else to try.
