### ISSUE TITLE
Legends on esri-mapServer items

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2410]
I'm struggling a bit with legends for `esri-mapServer` items.  

If I add the endpoint https://www.sciencebase.gov/arcgis/rest/services/Catalog/58c22bbbe4b014cc3a3da30b/MapServer
via `Add data`, I get nice legends, but if I try to specify layers in JSON, like
https://github.com/USGS-CMG/terriajs-dive/blob/master/examples/alaska_geology.json
I get "open legend in a separate tab":

![2017-03-10_17-19-40](https://cloud.githubusercontent.com/assets/1872600/23815766/8275b0ca-05b7-11e7-9c8a-f46df08940ea.jpg)

http://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/alaska_geology.json

I thought from reading this https://github.com/TerriaJS/terriajs/issues/1168#issuecomment-164650379 that if I specified the layers separately, I'd get the full legends. 

What do I need to do differently?

**Comment by rsignell-usgs** [comment]
Okay, I think the answer to this is: don't specify the layers individually from an ESRI MapServer  using `esri-mapServer`, but specify the MapServer endpoint as `esri-mapServer-group`  instead, and then `blacklist` layers if you don't want all of them. So instead of this:

```
      "items": [
        {
          "name": "Generalized Geology",
          "type": "esri-mapServer",
          "url": "https://www.sciencebase.gov/arcgis/rest/services/Catalog/58c22bbbe4b014cc3a3da30b/MapServer",
          "layers": "8",
          "isEnabled": true
        },
```
just do this:
```
      "items": [
        {
          "name": "Alaska Geology",
          "type": "esri-mapServer-group",
          "url": "https://www.sciencebase.gov/arcgis/rest/services/Catalog/58c22bbbe4b014cc3a3da30b/MapServer",
        }
```

**Comment by kring** [comment]
I think your original code should work; I'm not sure why it's not.  I'll check it out soon.

**Comment by kring** [comment]
Ok, here's what's happening.  Your JSON file specifies layers `8` and `17`.  Neither of those have a legend themselves.  Notice that they're not listed here:
https://www.sciencebase.gov/arcgis/rest/services/Catalog/58c22bbbe4b014cc3a3da30b/MapServer/legend

Failing to find the layer in the legend description above, TerriaJS falls back on linking to that page instead of generating a nice legend.

While those layers don't have legends themselves, they are both parent layers that contain other layers, and those other layers _do_ have legends.  So TerriaJS could be smarter and include all child legends for parent layers, it would just take a bit of work.

But if you're happy with the group approach above, you can probably just change the `8` and `17` in your JSON to one of the sub-layers, and that will give you the same thing (without the group).

**Comment by rsignell-usgs** [comment]
@kring, thanks for the ESRI MapServer lesson.  :blush: 

Yes, legends work fine when you specify layers that *do* have legends, as you suggest:
![2017-03-13_7-52-32](https://cloud.githubusercontent.com/assets/1872600/23853269/2deac182-07c2-11e7-9fcc-98dca9c5f75c.jpg)
