### ISSUE TITLE
share link not including time in multi-date raster layers

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#2438]
When viewing a particular layer with several dates and creating a link to share, the link doesn't include that info and opens in most recent ate available. 

Example, this view (showing FC October 2013) #
![image](https://cloud.githubusercontent.com/assets/8801702/24086450/b9e822be-0d63-11e7-954d-81679d81a04c.png)

creates this link : http://map.geo-rapp.org/#share=s-1KqThlpjDqUPUbzHwABnxGA6Hpe

**Comment by a-stacey** [comment]
A follow up question what is the expected behavior of the play state? Are we expecting to store this information too? do we default to playing or do we default to stopped?

Some thoughts:
It seems if the originator of the link is trying to send data at a specific time they (irrespective of whether they want to the viewer to be playing or not) they will almost certainly have the player stopped so that they can select the correct time.

**Comment by juan-guerschman** [comment]
My preference would be that the player is in stopped. In GEOGLAM I don't think users would be using te player that much but rather manually going to specific times in the past, e.g. the user wants to check a particular time when there was a drought, fire, etc.

**Comment by a-stacey** [comment]
Have created a PR for this issue:
https://github.com/TerriaJS/terriajs/pull/2572
