### ISSUE TITLE
Rounding issue with large "maxRefreshIntervals"

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2452]
I increased the value of `maxRefreshIntervals` from 1,000 to 10,000 and it worked fine, but I realized I had 35,000 time steps in the model run.  So I increased the value to 40,000, but then I get an error in the WMS request, because it is asking for a time value of `2017-03-30T00:59:58Z`, but there is no actual data at that time (since the data is actually at `2017-03-30T01:00:00Z`):

http://gamone.whoi.edu/terriajs/proxy/http://tds.marine.rutgers.edu/thredds/wms/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best?time=2017-03-30T00%3A59%3A58Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&colorscalerange=-50%2C50&service=WMS&version=1.1.1&request=GetMap&layers=salt&bbox=-10018754.171394622%2C0%2C0%2C10018754.171394622&width=256&height=256

Here's the "share" url for this test case: https://tinyurl.com/lcdoy7y

**Comment by kring** [comment]
This is almost certainly caused by repeatedly adding the interval, introducing rounding errors, rather than multiplying and adding.

**Comment by kring** [comment]
Actually, I just realized I'm wrong.  This isn't caused by rounding, it's caused by [leap seconds](https://en.wikipedia.org/wiki/Leap_second).  Two leap seconds were inserted between 2015 and 2017, which is why the final date falls two seconds short.

TerriaJS is using Cesium's JulianDate type for arithmetic, which means that the arithmetic happens in the TAI time standard (which doesn't have leap seconds), because leap seconds make UTC a disaster for arithmetic.  Adding a day always means adding 86400 seconds, even though on a day with a leap second there are 86401 seconds in that day.  Then when we convert to UTC for display, the displayed time is earlier than expected.

I could argue that TerriaJS is doing the right thing, depending on how you define a day (is it 24 hours, or is it a variable amount of time depending on whether the day had a leap second?), but of course pretty much everyone ignores the inconvenient fact that UTC has leap seconds, so the behavior here is unexpected.  See the crazy stuff Linux goes through to pretend leap seconds don't exist: https://access.redhat.com/articles/15145

Anyway, an easy solution here is to just do our interval arithmetic using something that ignores leap seconds, meaning pretty much anything other than Cesium's JulianDate.

**Comment by rsignell-usgs** [comment]
@kring, hoyo tanada, I missed this before.  Thanks for the education on leap seconds!  First web rabbit hole of the day!  :smile_cat:
