### ISSUE TITLE
Predefined Color Scale Range for Thredds overrides workbench controls

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2560]
When you predefine the Color Scale Range for a Thredds server, you then cannot use the workbench controls to change it dynamically.

In AREMI we specify it like:

https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/custodian/Bureau_of_Meteorology/Solar_Climatology.ejs#L64

However, when enabling the layer in AREMI those values do not feed through into the workbench controls, and subsequently changing them has no effect:

http://nationalmap.gov.au/renewables/#share=s-SAUAVUA2yUTC2TXp

<img width="321" alt="screen shot 2017-06-14 at 17 07 32" src="https://user-images.githubusercontent.com/5283003/27119639-fdaf6bde-5123-11e7-99fa-a48eef0d637b.png">

**Comment by kring** [comment]
You need to set `colorScaleMaximum` and `colorScaleMinimum` rather than setting `parameters.colorscalerange`.  Properties in `parameters` clobber any values that come from elsewhere.  It just sets those parameters in the URL - replacing whatever may have been there previously - as the very last step in building the URL.

**Comment by kring** [comment]
Just to be clear, `colorScaleMaximum` and `colorScaleMinimum` are top-level properties of the WMS catalog item.  That is, don't put them inside `parameters`.  Doc here: http://terria.io/Documentation/guide/connecting-to-data/catalog-type-details/wms/
