### ISSUE TITLE
Time UI control to select a specific time instant

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2608]
See the middle part of #2557 for the early discussion on this.

**Comment by RacingTadpole** [comment]
Summary of discussion with @kring:
- if the datetime picker is displayed in the workbench, and there are no other time-varying items, no time slider is shown
- if the user selects a datetime with the datetime picker, it "freezes" the datetime for that item, disconnecting it from the time slider (if there is one).
- there could/should(?) be a "use timeline" option associated with the picker that lets you "unfreeze" the datetime and use the time slider instead (should this be only if there is already timeslider?)

I think this should be available on all catalog items via a flag on the item (eg. `item.showDatetimePicker`, default false).

**Comment by kring** [comment]
> should this be only if there is already timeslider?

No, this should always be an option.  This is how you "explore" the layer across time.  Also, it's the current behavior.  So if we have this option and default to it, we don't necessarily even need a `showDateTimePicker` property, cause it's just a new capability that doesn't break anything existing.

**Comment by philipgrimmett** [comment]
@kring So, is the decision to default to a workbench date picker instead of the timeline up to the developer or data custodian? Just wondering how this might affect the discoverability of the timeline in the long run.

**Comment by kring** [comment]
IMO the default is to show the timeline and to show "Time: Use timeline" in the workbench.  So basically you get the current behavior by default.  But you'll also be able to add something to the catalog item JSON to make it start with a time selected (and thus no timeline visible) instead.  It'll be up to the catalog maintainer to choose to do that instead of using the default behavior.  Does that sound reasonable?

**Comment by RacingTadpole** [comment]
Here's a first pass at the datetime-picker-from-the-timeline:
![image](https://user-images.githubusercontent.com/1757858/28764769-a35b11a4-760a-11e7-9dbf-e3257dbb6b04.png)
It simply provides another way to select a datetime from the timeline.

**Comment by AnaBelgun** [comment]
Terria Cube project meeting 2 August 17
Suggestion was made on showing (somehow) the time intervals the data would be available for (e.g. minutes, hours, days etc) when dates are selected and action repeated; there are many different intervals data would be available and clicking the arrows for going forward or backward without specifying what is the next/previous interval would be confusing

**Comment by philipgrimmett** [comment]
@AnaBelgun I'm a little lost. Was the suggestion just to explicitly state the temporal granularity of an active dataset, or to give users the option of loading data at different levels of granularity? (cc @meh9 @RacingTadpole @kring)

Progress with visualising year/month/day/... granularity: https://invis.io/VKCVJFXWX#/246863061_map-DatePicker1

- Use the workbench date picker to get to **Thursday 10th December 2001 @ 05:42:00**
- Click the timeline button next to the workbench item to, y'know, launch the timeline
- Click timeline to toggle between zoomIn/zoomOut state. I'm using a zoom-dependent blue-dot bucketing system atm, but not sure it's super clear. Keen to get feedback.

**Comment by AnaBelgun** [comment]
@philipgrimmett The issue discussed was that when choosing a date initially there will be no way for the user to know what is the date intervals the information would be available. I see in the demo above that problem is solved, by highlighting the year, months and dates when data is present. To me that seems fine, although the only very small issue I see now is the number of clicks you need to have to get to the most granular time with data available.
One idea was to have a short explanation when hoovering over the arrow: e.g next data available on X date; but that would make the UI too busy.

**Comment by kring** [comment]
Here's a WMS server with two centuries of data:
http://tds.gisclimatechange.ucar.edu/thredds/wms/products/products_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities
(mostly putting this here for my future reference)

**Comment by kring** [comment]
Here's another WMS with monthly data for over 100 years:
http://geoport.whoi.edu/thredds/wms/prism3/monthly?service=WMS&version=1.3.0&request=GetCapabilities
(thanks to @rsignell-usgs for this one)

**Comment by kring** [comment]
And here's another one from @rsignell-usgs that covers a shorter period of time, but with over 28k different values:
http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities
