### ISSUE TITLE
Splitter control to compare data

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2609]
See the latter part of #2557 for our discussion so far.

**Comment by kring** [comment]
Quick suggestion while I'm thinking of it: make the vertical splitter line thinner.  It's currently 4 pixels, which is wide enough to make it a bit hard to see subtle changes at the transition.  1 pixel is sufficient IMO (don't worry, it'll be 2 physical pixels on high DPI displays).

Also, it would be awesome if we could use the basemap highlight color as the divider line color, instead of always using white.  This is the color we use to highlight selected polygons, for example, and is more likely to stand out agains the base map.

**Comment by meh9** [comment]
Done! Good work! :D
