### ISSUE TITLE
Back/Forward functions for the new Date Picker

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2748]
As we are starting to use the new Date Picker for things like temporally granular satellite image passes we are finding that it needs Back/Forward functions to step the the previous or next available imagery.

E.g., we are looking at satellite imagery for an area in Tasmania over the winter, and many of the images consists mainly of cloud. When this happens we start skipping backwards or forwards in the timeseries of the available imagery until we find one that is free of cloud. 

Note that using the time slider at the bottom isn't appropriate because we can't see when the previous/next time is.

Repeatedly opening the new Date Picker and navigating through the list of imagery is time consuming, and it would be better to have "step" buttons, maybe something like this (but please use better arrows):

<img width="469" alt="screen shot 2017-11-16 at 18 30 25" src="https://user-images.githubusercontent.com/5283003/32879093-b5af50ee-cafc-11e7-99e2-0c2f82e2f49c.png">

**Comment by philipgrimmett** [comment]
@meh9 sorry, I meant to include this functionality earlier (just wasn't sure whether to duplicate in the timeline UI)

Invision: https://invis.io/7BEIQJGD3#/264552860_with_Clouds
Screen capture: https://drive.google.com/a/csiro.it/file/d/0B4THi7uv4XkIZmt6d2w4RTFHa28/view?usp=sharing

I'll add whoever is implementing the feature to the invision doc so that they can get assets/specs.

**Comment by meh9** [comment]
@philipgrimmett looks great!

**Comment by kring** [comment]
Fixed by #2815
