### ISSUE TITLE
When going to a share URL, do not enable "isEnabled" layers from the standard catalogue

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2758]
When you go to a share URL to see the previously configured layers from a user, if the standard catalogue has a set of layers turned on by default with `"isEnabled": true` that have been disabled in the share URL, then these are again enabled and interfere with the configuration of the share URL.

We should not allow layers in the standard catalogue to turn on by default when visiting a share URL.

**Comment by kring** [comment]
Ooh this is an interesting one.  It basically comes down to the fact that our share feature decides what to share using some faulty heuristics.  What we really want is "share all the things the user changed", but we don't have a way to keep track of what changed.

**Comment by meh9** [comment]
@kring so, I'm not sure I agree, but maybe I'm misunderstanding.

I think when we share, we should share whatever is active on the users screen regardless of how it was turned on. 

However, IMHO, in the case where we are going to a share url, we should not enable any `isEnabled` layers in the standard set of the catalogue init data, and only enable those in the init data for the particular share URL.

**Comment by kring** [comment]
> I think when we share, we should share whatever is active on the users screen regardless of how it was turned on.

Sure, but serializing the entire application state would be huge, and would cause all kinds of problems when, for example, the catalog gets updated. So we want to only serialize the _relevant_ state, but our current mechanism for deciding what is relevant is not very good. It's basically "share a specific set of properties for all groups that are open and all items that are enabled."

> However, IMHO, in the case where we are going to a share url, we should not enable any isEnabled layers in the standard set of the catalogue init data, and only enable those in the init data for the particular share URL.

Yes, this is a way to hack around the fundamental problem. It's a bit ugly because TerriaJS doesn't distinguish between "standard set of the catalogue init data" and "other changes resulting from other init files, share data, etc."

I agree with the effect you're trying to achieve, though!

**Comment by kring** [comment]
The same thing happens with groups that are open by default (sharing will lose the fact that they were closed).

**Comment by a-stacey** [comment]
So are we thinking here that whilst not perfect that the most clean practical way to address this is to add a flag to the "share data" that is "disableAllOtherEnabled" which when hit in the initalisation causes all layers that or otherwise enabled to be disabled (i.e. its like a master disable flag that we add to the share link as a property)?

This hack possibly causes more problems then it solves, in that without looking at the code its not clear what the initalisation order of intialisation sources is and so what if that is in a source and then other initalisation sources are encountered after it. But this could be possibly worked around by either making it so that share URLs are done late in the piece or in a way that it keeps resolveing for all future initalisation sources (and specifically only for initalisation sources not manual user enables) that are loaded (then only problem is what if two different initalisation sources both specify it..but possibly you either take union in that case or either the first of last set encountered with the flag).

Would have to look into the code in more detail for further insight, but thought if we could agree on a proposed solution in the first instance to guide what I attempt to fix and then we can deal with any fallout on the fly as we learn more during implementation.

I don;t understand the nuance of the groups @kring is this as significant as the original problem and is there any similar solution that could be applied here?

**Comment by kring** [comment]
@a-stacey this is one of the many things driving the need for refactoring of the model layer. I think it would be extremely difficult (or at least extremely hacky) to solve without major changes.

**Comment by nf-s** [comment]
Not relevant in v8.

Share URLs won't include `isEnabled` layers from catalog
