### ISSUE TITLE
Date picker doesn't work when layer is hidden

### ISSUE THREAD

**Issue by SpacemanPaul** [TerriaJS/terriajs#2760]
Observed on http://terria-cube.terria.io/

If you change the date of a layer with the date picker while the layer is not visible, nothing happens.  E.g.

1. Layer is visible and set to date A.
2. Hide layer.
3. Set date to date B.
4. Un-hide layer.
5. Layer is now visible, says it is date B, but is actually still displaying date A.

**Comment by a-stacey** [comment]
Able to reproduce, using layer "Landsat 8 Water Observations from Space (WOfS)" on terria-cube using the date picker on the layer in the workbench. Will look into this.

**Comment by a-stacey** [comment]
Here is a patch that fixes this specific issue...
```
@@ -487,10 +487,12 @@ ImageryLayerCatalogItem.prototype._disable = function() {
     ImageryLayerCatalogItem.disableLayer(this, this._nextLayer);
     this._nextLayer = undefined;
 };
 
 ImageryLayerCatalogItem.prototype._show = function() {
+    this.showDataForTime(this.currentTime);
     ImageryLayerCatalogItem.showLayer(this, this._imageryLayer);
     ImageryLayerCatalogItem.showLayer(this, this._nextLayer);
 };
```

...but my feeling here is that this doesn't fix the real underlying issue...the question that I think is the real underlying issue is what does it mean when a layer is not shown...should the whole workbench item appear disabled? (my feeling - based on experiences through other similar UI's) or are there use cases that modifications to the layer state should be allowed when its not shown but are only apparent when the layer becomes visible again?

@philipgrimmett do you have any input on what should happen to the workbench item when the layer is not shown? Should modification of the other properties of the item be allowed or not or is it a don't care from the UX perspective and just implement whats easiest.
