### ISSUE TITLE
White box around My Data tabs

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#2825]
Maybe caused by a change of order within css.

Problem: 
![image](https://user-images.githubusercontent.com/13863530/36242917-b2f43d70-1272-11e8-9139-67e556fd9cd8.png)

Current CSS:
![image](https://user-images.githubusercontent.com/13863530/36242931-c4449782-1272-11e8-89c0-8bf094cdd406.png)

Before:
![image](https://user-images.githubusercontent.com/13863530/36242909-aad8ccbe-1272-11e8-855d-83e8f4464b06.png)

Old CSS:
![image](https://user-images.githubusercontent.com/13863530/36242939-da2272ea-1272-11e8-9448-21f6bfc06572.png)

**Comment by chloeleichen** [comment]
So the problem is in how the css-modules compile and load the code. on staging this line `composes: tab-list from '../../tabs.scss';` is compiled twice, once before the rest of the code, once after. A quick and dirty way to fix is to force the order of cascading by adding `! important` to the style we want. as in https://github.com/TerriaJS/terriajs/pull/2835

**Comment by chloeleichen** [comment]
This is already fixed, no?
