### ISSUE TITLE
Fix printing in terria apps 

### ISSUE THREAD

**Issue by reinaldocruz** [TerriaJS/terriajs#2828]
When National Maps operates in 2D Mode, a map is split into two pages when trying to print a map.
Screenshots were provided to the National Maps support team of this issue in browsers Mozilla and Chrome. 
The NM support team has acknowledged that there is an issue in 2D mode and provided a work around. 
However, I highlighted to the NM support team, that given that 95% of our maps are rendered in 2D mode, this is a critical problem for us.  
The NM support team advised to write a GitHub issue for the printing problem in 2D in the hope this problem is addressed soon by NM and a solution is found.

**Comment by kring** [comment]
Remaining issues:
* [x] Make the splitter work in 2D
* [x] Show layer time near legend
* [x] Make print-in-iframe work (override `window.print`?)
* [x] Add dataset details
* [x] Add feature info details

**Comment by AnaBelgun** [comment]
Initial ACT -CSD client comments:

- Ability to print the displayed maps showing, legends, scale, timeline information (if available)
etc. just like if we do a screen shot but without actually doing a screen shot, more like printing
from the browser
- Current issue is the share link does not provide legend or scale or any other
information, it only display the point on a map
- Printing using browser does not render correctly and does not show complete
information
- Screen shot might not be user friendly for the intended user group

**Comment by AnaBelgun** [comment]
UX designs:
Concept video:
https://drive.google.com/file/d/1KA0dU4X_SkCOp4nftdVIYfbDIORfCPeC/view?usp=sharing

Invision prototype:
https://invis.io/JXHUPS925QT#/294502269_shareable_Map

**Comment by kring** [comment]
More issues remaining:
* [x] Splitter shows up as a white line in print view in 2D, but not in 3D. (the map is still split, there's just no separator line)
* [x] IE9 is totally broken, app doesn't start up at all. I had to upgrade to React 16, and React 16 requires some polyfills to work in IE9.
* [x] We should remove all the old print styles, because they're not doing anything useful anymore.
* [x] We're using a bunch of stuff was deprected in React 16.3, which, if nothing else, is freaking out eslint.

**Comment by kring** [comment]
@reinaldocruz do you have a moment to try this out and make sure it satisfies your use-case as well?  You can test it at http://ci.terria.io/print/.
