### ISSUE TITLE
Service to convert WFS / GML into csv 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2913]
Most users of the maps and the raw data would find difficult to use the GML format, and prefer csv. 
It would be great to have a service that makes that conversion automatically and show that on the About This Data page.

**Comment by kring** [comment]
GML is a huge standard that can represent all kinds of things that a CSV can only dream of. We could maybe do this in the specific case of the GML simple features profile and when the simple features are all points.

Also, many WFS servers can provide data in GeoJSON, KML, and other formats, not just GML. GeoServer can even provide CSV!
http://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html#wfs-output-formats

Generally the server-provided conversion is going to be better because it's closer to the data. Unfortunately, the Esri server in the (private) feedback issue above can only provide GML.
http://services.ga.gov.au/site_9/services/Oil_Gas_Infrastructure/MapServer/WFSServer?service=WFS&version=1.1.0&request=GetFeature&typeName=Oil_Gas_Infrastructure%3ANational_Onshore_Gas_Pipelines&srsName=EPSG%3A4326&maxFeatures=100000

Anyway, I think doing conversions of geospatial data like this would be pretty interesting, and at one point ages ago I thought it was going to be one of the major features of [Magda](https://github.com/TerriaJS/magda). But it's also well outside the scope of TerriaJS, so I'm going to close this.
