### ISSUE TITLE
Increase file size for format conversion service

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2922]
Based on user feedback: 
"The only pity is the uploaded file size has a limit ( must less than 1 MB), hopefully the file size could be increased in the future."

**Comment by meh9** [comment]
It is already possible to change the conversion file size in the site config. The question is just what to set it to that is reasonable, because somebody is always going to want a higher limit.

Geoglam has been running with 20mb max file size for 8 months and has been working ok, AREMI for 2 months.

@kring thoughts?

**Comment by kring** [comment]
20mb sounds ok with me for now.

**Comment by stevage** [comment]
Also see #2907 which would remove the need altogether for Shapefiles.

**Comment by zoran995** [comment]
conversion service is deprecated
