### ISSUE TITLE
Endless tile requests on certain kinds of errors

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2928]
Certain types of server errors may cause TerriaJS to repeatedly request the same (failing) tiles over and over again, wasting bandwidth and potentially starving other requests. Specifically, if an error occurs while loading an image but then an XMLHttpRequest to the same URL succeeds, TerriaJS will retry the image and repeat this process endlessly. 

Here's an example of a WMTS server that triggers the problem (at least until we address #2927):
https://tiles.openaerialmap.org/5abae68e65bd8f00110f3e42/0/5abae68e65bd8f00110f3e43/wmts

TerriaJS should limit the number of times it is willing to retry image loads. It should also more carefully validate the XMLHttpRequest response. For example, it should set the `Accepts` header and it should verify that the response is actually an image.

**Comment by meh9** [comment]
This is preventing GEOGLAM from starting in 3D mode because we default two WMTS layers to on.

**Comment by meh9** [comment]
I'm also seeing this behaviour for a CSV region mapping file using LGA. In this case the CSV had a column name that included the word "time" but did not contain parseable dates. Setting `timeColumn: null` resolved the problem.

**Comment by kring** [comment]
Unless the region definition itself is broken, that sounds like a different problem. Can you attach/send me the CSV?

**Comment by meh9** [comment]
@kring this one:

http://calculators.sustainability.vic.gov.au/biomass2018/Almond_HusksShells.csv

**Comment by stevage** [comment]
Wow, that CSV does really nasty things to Firefox. It seems to go into this immediate vector tile fetching death spiral. I suspect the cause is quite different though: something about that date parsing problem is causing constant fetches, as opposed to fetches being caused by fetch failures.

**Comment by stevage** [comment]
Eep, ok I've spent a while on this and I'm struggling to come up with a graceful solution. Because there's no context maintained for an individual tile request (or not that I could see), it's hard to distinguish between these two situations:

1. A bunch of tiles have failed, we've re-requested them via XHR, and they're about to come back as 404s, which is not an error for this particular layer.
2. A bunch of tiles have failed, we've re-requested them via XHR, and they're failing in the same non-specific way. (That is, an XML page is being sent back instead of an image, but we don't know that).

All I can think of is trying to count the number of outstanding requests and aborting when it hits a threshold, but it feels like a game of balancing false positives and false negatives.

My branch is at https://github.com/TerriaJS/terriajs/tree/2928-wmts-error-handling

**Comment by stevage** [comment]
As for intercepting the XHR response and ensuring it's actually an image, that seems tricky to me - or at least, figuring out where the right place to do that is. 

In Cesium's "Resource", `loadWithXhr() ...onLoad()` can inspect the response headers, and check whether they match the request ("Accept: ") headers, and then...throw a different kind of error? We also need, on the Terria side, to make sure we set that header. A little bit unsure whether Resource should really be enforcing this checking in all cases - could easily have some unwanted side effects.

**Comment by stevage** [comment]
The Cesium bit at https://github.com/TerriaJS/cesium/pull/37

**Comment by stevage** [comment]
Ok, I think this is ready for review, or at least feedback on my approach here.

**Comment by stevage** [comment]
Handing over to @kring now. Error handling is hard!
