### ISSUE TITLE
errors displaying layers from https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#2930]
from https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi I import Reference Labels and Reference features and get an error message: 

![image](https://user-images.githubusercontent.com/8801702/38340051-bf1133b6-38b4-11e8-9640-07459ed5e59a.png)

As we use those layers in the GEOGLAM RAPP instance I would like to understand if the issue is with Terriajs and if so if it can be fixed. 

direct link to layers loades: http://nationalmap.gov.au/#share=s-9hLHAGAaZtz0wNr4g5ztaVgAA8d

**Comment by kring** [comment]
That server is returning heaps of 404 errors, and it's returning them without a CORS header, so TerriaJS isn't even allowed to look at the response. But if you add the server to the proxy whitelist, TerriaJS will start seeing the 404 and, by default, it won't treat that as an error that should disable the layer. Alternatively, you can set `ignoreUnknownTileErrors` in the init file. I'm closing this because I don't think it's something we can address in TerriaJS.

**Comment by juan-guerschman** [comment]
Thanks @kring .

I know how to add a `ignoreUnknownTileErrors` in the init file. If this solves the problem then great. 
But I have no idea about adding the server to the proxy whitelist.

**Comment by kring** [comment]
It's in `devserverconfig.json`. I'm not sure if that's something you maintain in GEOGLAM or not. But @meh9 or whoever should be able to add it in any case.
