### ISSUE TITLE
Enable users to create stories using TerriaJS maps

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3013]
We are starting to get more examples which validate this functionality; this ticket is to start gathering those use cases in one place. Once design & development starts, it will be broken down in more specific issues. 

Example 1: 
- Compliance officers and other gov reps would like to communicate policies or decisions in general (e.g. water usage restrictions in MDB) using an user friendly mapping interface ("improved ability to communicate impacts of events to the general public")

**Comment by tephenavies** [comment]
@philipgrimmett @chloeleichen Can you update this ticket or link to other tickets/PRs related to building of stories?

**Comment by tephenavies** [comment]
Affected by this bug https://github.com/TerriaJS/terriajs/issues/3239 when using stories to compare imagery of one at different dates (e.g. a story using different dates of Sentinel/Landsat).

The above bug is fixed in branch `3009-sos-imagery`. Branch `stories-with-3009-sos-imagery` thus also doesn't suffer from this bug.

**Comment by AnaBelgun** [comment]
connected with this https://github.com/TerriaJS/terrace/issues/19 (closed) for clarity

**Comment by AnaBelgun** [comment]
@philipgrimmett and @chloeleichen please keep this one as reference until we finish the stories work

**Comment by AnaBelgun** [comment]
connected to this PR: https://github.com/TerriaJS/terriajs/pull/3228
