### ISSUE TITLE
Include map scale in the Print preview

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3040]
Based on user feedback regarding scale and errors with map locations / placenames / addresses.

**Comment by kring** [comment]
config.json has a `printDisclaimer` property that is shown at the bottom of the print view if it's configured. Here's what NationalMap's looks like:
![image](https://user-images.githubusercontent.com/924374/44194557-b5528900-a179-11e8-992b-3ed9e6adcf4a.png)

Do we just need to add a suitable disclaimer to another app?

**Comment by kring** [comment]
I'll change this issue to only cover adding the scale to the print view.

**Comment by kring** [comment]
Showing a scale bar is easy enough, but making it accurate when the map automatically sizes to fit the page will be the challenge. Easiest approach I can think of off the top of my head is to bake the scale into the map image itself, which means we'll need a separate render-scale-to-canvas thing because our current scale bar is rendered via the DOM.

**Comment by nf-s** [comment]
We now have a scale

<img width="203" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/2b354be6-a0f8-4b1b-923c-14e27ce39497">
