### ISSUE TITLE
NaN values in timeseries

### ISSUE THREAD

**Issue by hmedrano** [TerriaJS/terriajs#3042]
Hello, 
I'm trying to add multiple buoy stations with the csv catalog type, and each individual buoy points to another csv with multiple variables time series. The issue here is that some of the variables in the csv file with the time series have NaN values, and those variables are not being shown in the workbench.

The setting "replaceWithNullValues" is not working for me in the tableStyle section.
Which is the right way to threat this "NaN" values (or any other string for this matter) in the csv as nulls?  

**My csv item looks like this:**

```
            {            
              "name" : "Buoy data",
              "type" : "csv",
              "url" : "my-data/csv/bouy-stations02.csv",
              "idColumns" : ["lat", "lon"],
              "tableStyle" : {
                "columns" : {          
                  "data_1day" : { 
                    "type" : "hidden",  "replaceWithNullValues" : ["NaN"]
                    } , 
                  "data_1month" : { 
                    "type" : "hidden", "replaceWithNullValues" : ["NaN"],
                  }
                }
              },
              "featureInfoTemplate" : "<table><tbody><tr><td>Station</td><td>{{name}}</td></tr><tr><td>wind_dir</td><td><chart sources='{{data_1day}},{{data_1month}}' source-names='1Day, 1Month' preview-x-label='1 Day data' column-names='Time,wind_dir,wind_spd,gust,wave_height,dominant_wpd,average_wpd,mean_wave_dir,air_pressure,air_temperature,sea_surface_temperature,dewpt_temperature,visibility,water_level' column-units='Date,degrees_true,meters/second,meters/second,meters,seconds,seconds,degrees_true,hPa,degree_Celsius,degree_Celsius,degree_Celsius,US_statute_miles,meters' y-column='1'></chart></td></tr></tbody></table>"          
            }  
```

**bouy-stations02.csv**
```
lat,lon,name,data_1day,data_1month
25.897,-89.668,Estación 42001,station-42001-1day.csv , station-42001-1month.csv
26.091,-93.758,Estación 42002,station-42002-1day.csv , station-42002-1month.csv
```
**station-42001-1day.csv**
```
time (UTC),wind_dir (degrees_true),wind_spd (meters/second),gust (meters/second),wave_height (meters),dominant_wpd (seconds),average_wpd (seconds),mean_wave_dir (degrees_true),air_pressure (hPa),air_temperature (degree_Celsius),sea_surface_temperature (degree_Celsius),dewpt_temperature (degree_Celsius),visibility (US_statute_miles),water_level (m)
2018-08-08T12:50:00Z,140,3.0,4.0,0.5,6.0,NaN,NaN,1017.1,29.2,29.6,23.9,NaN,NaN
2018-08-08T13:00:00Z,150,3.0,3.0,NaN,NaN,NaN,NaN,1017.4,29.2,NaN,23.9,NaN,NaN
2018-08-08T13:10:00Z,150,2.0,3.0,NaN,NaN,NaN,NaN,1017.5,29.2,29.6,24.0,NaN,NaN
2018-08-08T13:20:00Z,160,2.0,3.0,NaN,NaN,NaN,NaN,1017.6,29.2,29.5,24.0,NaN,NaN
...
..
```

Thanks in advance

**Comment by kring** [comment]
Hi @hmedrano,
The `replaceWithNullValues` only applies to the mapped CSV file (i.e. `bouy-stations02.csv`), not the CSV embedded in the chart. We don't currently have support for missing values in charts. To implement it, we'd first have to decide how to represent the missing values. This issue is not exactly the same, but raises some of the same issues:
https://github.com/TerriaJS/terriajs/issues/2113

If you're up for it, we'd be very happy to see a pull request for this. You can find the D3 code to produce the line chart here:
https://github.com/TerriaJS/terriajs/blob/master/lib/Charts/LineChart.js

The `<Chart>` tag in a `featureInfoTemplate` is handled by the code here:
https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViews/Custom/registerCustomComponentTypes.js
