### ISSUE TITLE
Search location is broken 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3064]
Following the switch to new Cesium ION for the NatMap, NA Map and AREMI apps, the locations search seems to be broken. 

There’s a couple of bugs. The file `loadJsonp` exports an empty object instead of the function defined in it, and then there’s something wrong with the request building for the Locations query (it’s missing query parameters)

**Comment by tephenavies** [comment]
Apart from the `loadJsonp.js` not exporting the correct thing, there's also a problem in all `load...` functions. A change in Cesium from v1.43->1.44 removed the `options` parameter from `Resource.createIfNeeded(resource, options)`. JS just ignores this. Many other requests using these helper functions in TerriaJS could be affected by this bug. Not sure how we can avoid these bugs caused by breaking Cesium changes in the future.

[Cesium 1.43 -> 1.44 diff](https://github.com/AnalyticalGraphicsInc/cesium/compare/1.43...1.44)

Looks like the Cesium-preferred way to upgrade is to create a resource in the caller when you want to use specific options.
