### ISSUE TITLE
LGA with State column disambiguation doesn't work

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3081]
Using a State column to disambiguate LGA areas does not work, see attached example.

[LGA_State.csv.txt](https://github.com/TerriaJS/terriajs/files/2387440/LGA_State.csv.txt)

**Comment by stevage** [comment]
I think the cause here is a slight misconfiguration of the regionMapping.json.

Basically, "lga_name" is being picked up by lga_name_2011, which disambiguates with ste_name_2011, which expects a column called "ste_name_2011". When it doesn't find one (because the column in this table is called State), it gives up.

The easy solution is that lga_name should be an alias for lga_name_2016 not lga_name_2011, then the rest fixes itself.

I think. :)
