### ISSUE TITLE
how to select default basemap

### ISSUE THREAD

**Issue by zdefne-usgs** [TerriaJS/terriajs#3124]
Following the documentation it should be possible to set a default base map in the init files with
``    "baseMapName": "Positron (Light)",
``
but it doesn't work. Also tried to set this in index.js with 
``
        selectBaseMap(terria, allBaseMaps, 'Positron (Light)', false);
``
https://github.com/TerriaJS/terriajs/blob/bf73f6fab0018fd1ec9cc636ebfa2af1d38609a5/lib/ViewModels/selectBaseMap.js#L20

But no luck. It always defaults to the last one or the first in the list (Bing Aerial in this case). Am I missing something? 
Thanks

**Comment by kring** [comment]
@zdefne-usgs either of those should work, but Terria gives precedence to explicit basemap choices by the user, which are remembered across sessions. So if you've changed your basemap explicitly through the UI, you'll get your last choice instead of the default. You can use your browser's dev tools to remove the setting from local storage. Delete keys like this:

![image](https://user-images.githubusercontent.com/924374/47052799-aaf25100-d1f5-11e8-89ee-297142cf7c55.png)

**Comment by kring** [comment]
I just tried it and it seemed to work ok. My init file looked like this:

```
{
  "baseMapName": "Positron (Light)",
  "services": [],
  "homeCamera": {
    "north": -8,
    "east": 158,
    "south": -45,
    "west": 109
  },
  "corsDomains": [
    ...
  ],
  "catalog": [
    {
      "name": "National Datasets",
      ...
    }
  ]
}

**Comment by zdefne-usgs** [comment]
Okay that seems to work on mine too now. I switch computers so I imagine somehow it was still being cached in the other one. Or maybe I was making changes at too many locations at the same time. Thank you, Kevin.
