### ISSUE TITLE
WFS coordinate lat/lon lon/lat confusion

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3165]
Seems we have been bitten by the lat/lon lon/lat parameter order confusion.

These points should be in the UK:

https://map.terria.io/#share=s-qJjo8ydyMC4y8XNWhxGlG1Ch1Zl

These points and lines should be in Australia:

https://nationalmap.gov.au/renewables/#share=s-tGfzaWKetVwaNp9Y

This confusion is common, and there are various places documenting it:

https://docs.geoserver.org/latest/en/user/services/wfs/basics.html#axis-ordering

https://wiki.osgeo.org/wiki/Axis_Order_Confusion

Wy should try to solve this issue according to the spec, and then if that doesn't solve the issue then IMHO we should be pragmatic and solve it for the majority of data that we have seen. Perhaps we need a config option to switch order?

**Comment by stevage** [comment]
Just adding this reference as well: https://macwright.org/lonlat/

**Comment by rowanwins** [comment]
I'm seeing the first set of UK points in the correct location
![UkPoints](https://user-images.githubusercontent.com/6735870/56627944-483dae80-668b-11e9-9d99-6eec70147a82.png)
This WFS appears correctly on the AREMI viewer as well so I don't think it's viewer related. So perhaps something has been fixed since this issue was first raised?

I can however replicate the second case. However it's worth noting that when I pull the WFS National Power Stations layer into QGIS they also display in the incorrect location.
![WFS](https://user-images.githubusercontent.com/6735870/56628398-f4cc6000-668c-11e9-85e7-2d01376467c6.png)

Interestingly the Esri Feature Service and the WMS available from the same server work correctly and place the points in Aus 
http://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer

I'm tempted to chalk this down to something on the services end, another other thoughts @meh9?

**Comment by rowanwins** [comment]
Just to add some further research

This [WFS 1.1.0 request](http://services.ga.gov.au/gis/services/Electricity_Infrastructure/MapServer/WFSServer?service=WFS&version=1.1.0&request=GetFeature&typeName=Electricity_Infrastructure%3ANational_Major_Power_Stations&srsName=EPSG%3A4326&maxFeatures=1) (similar to what Terria would typically send) gets the first feature from the power stations layer, one of the layers above that is appearing in the wrong spot. The first feature has this geometry
````
<gml:Point>
     <gml:pos>143.112305479 -37.38927505999999</gml:pos>
</gml:Point>
````
With WFS 1.1.0 the order should be latitude followed by longitude. A valid range for latitude ought to be  -90 to 90, however in this case the latitude is shown as `143.112305479`

#### A layer from NSW gov which displays correctly in Terria
- [GetCapabilities](https://spatial.industry.nsw.gov.au/arcgis/services/Minerals/NSW_Major_Operating_Mines/MapServer/WFSServer?request=GetCapabilities&service=WFS)
- [Get 1 Feature via WFS 1.1.0](https://spatial.industry.nsw.gov.au/arcgis/services/Minerals/NSW_Major_Operating_Mines/MapServer/WFSServer?service=WFS&version=1.1.0&request=GetFeature&typeName=Minerals_NSW_Major_Operating_Mines%3ANSW_Major_Operating_Mines&srsName=EPSG%3A4326&maxFeatures=1)
````
<gml:Point srsName="EPSG:4326">
    <gml:coordinates>-37.38927505999999,143.112305479</gml:coordinates>
</gml:Point>
````
Note that the coords appear as expected.

#### Another example from WA which displays correctly in Terria
- [GetCapabilities](https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Infrastructure_and_Utilities_WFS/MapServer/WFSServer?request=GetCapabilities&service=WFS)
- [Get 1 Feature via WFS 1.1.0](https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Infrastructure_and_Utilities_WFS/MapServer/WFSServer?service=WFS&request=GetFeature&typeName=SLIP_Public_Services_Infrastructure_and_Utilities_WFS%3AWater_Pump_Station__WCORP-077_&version=1.1.0&srsName=EPSG%3A4326&maxFeatures=1
)
````
<gml:Point>
     <gml:pos>-31.284509275764503 116.83940714617346</gml:pos>
</gml:Point>
````

From my look at the [Geoscience Aus web services page](http://services.ga.gov.au/) it appears that most (if not all) of the available WFS services suffer from the same issue. Both the NSW and WA examples above are coming from ArcGIS Server v10.31 so if there is something curious about ArcGIS Server 10.6.1 is configured....

Hope that helps :)

**Comment by rowanwins** [comment]
This has been confirmed as an issue with the web services.

**Comment by stevage** [comment]
Just noting that the original issue had:

> Perhaps we need a config option to switch order?

Which doesn't seem to have been discussed yet. Personally, I don't think allowing for this kind of working around misconfigured servers is a great idea, but worth debating perhaps.

**Comment by rowanwins** [comment]
Ah missed that note, good pickup @stevage... 

I guess I could see 4 approaches
1. Do nothing and display what we're given
2. Provide some part in a config file which flagged to flip the coordinates of service 'x'
3. Sniff the data for errors as it's coming in and attempt to rectify
4. Some sort of new UI component that allowed people to flip coords

My preference would be display the data as we're given it. Adding config around services with known issues gets dangerous because as soon as it is changed in the source then terria would start displaying the incorrect thing. Sniffing for errors would be tricky I imagine. And some sort of additional UI component is a potential path to confusion for users...

I think we're better off to get the problem resolved upstream properly

**Comment by stevage** [comment]
Yeah, 3 is kind of madness. 4 seems overkill. 

I can see 2 being useful in specific situations for particular people, where they need to use data from a third party that they don't control, and there is no hope of getting fixed. Probably wouldn't make sense for NationalMap though.

**Comment by kring** [comment]
I have no problem with 2. After all, one of our.. errr.. values?.. is "accommodation". We should try to accommodate all the crazy things geospatial services do _when it's reasonable to do so_. Sure, it might cause the service to break in the opposite direction in the future, but possibly broken in the future is better than definitely broken today.

That said, we should only go off and implement this if there's a clear need to do so, like a paying customer or important stakeholder is asking us to.
