### ISSUE TITLE
Protect access to cesiumIonAccessToken

### ISSUE THREAD

**Issue by urbanows** [TerriaJS/terriajs#3349]
I would like to know if there are best practices that should be followed regarding access to the cesiumIonAccessToken in the Config.json.  The config file containing this token is checked into our baseline and the config.json file is downloaded to the client when the page loads.  Is this key tied to a specific host/referrer and restricted access to the key is therefore not required?

**Comment by kring** [comment]
@urbanows someone asked this question awhile back on the Cesium forum (https://groups.google.com/d/topic/cesium-dev/PuhLa16Q6mo/discussion). Matt Amato from Cesium said:
> Domain restrictions are something we've thought about, but have not investigated thoroughly yet.  I'm dubious of their usefulness because it is easy for a bad actor to spoof the origin header and therefore completely negate the restriction.  I wrote up an issue in the ion-community repository so that we document best practices and investigate domain restrictions in the future: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/26

> As far as I know, the industry standard for dealing with "public" access tokens is token rotation.  Basically you create a new token and revoke the old one on some set schedule so that even if someone does steal it; it becomes useless.  Once a month is a good starting point for such practices.  In the future, we plan on having a documented REST API to manage tokens which would allow you to automate this as part of your deployment process.

A few specific suggestions:
* Avoid checking your key into public repos on github. For our apps, we pull the key in at deployment time. Obviously it's not hard to extract the key from a deployed app, but putting it on github makes it that much easier.
* Rotating your keys monthly or so is a good idea, though admittedly it's a hassle.
* Don't sweat it. If someone steals and uses your key, they are guilty of - at least - copyright violation. A major site with significant traffic is pretty unlikely to take such a risk. If it did happen, the Cesium ion folks would work with you to fix it, not punish you for it. This is an inherent problem with no complete solution for any authenticated services that are accessed directly from an in-browser app.

I'm closing this issue because I don't think there's any action required, but feel free to keep discussing here if you have followup questions.
