### ISSUE TITLE
Story v1.1 - no way to get back to story when in mobile

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3570]
Currently there's no clear way to get back to story when you're on mobile and closed a story. 

to reproduce: 
- check this test story on mobile on NatMap: https://nationalmap.gov.au/#share=s-fAFUIvmJbRrunjpsVTOQ6IpUbel
- close the story 
- try to go back to story 

It is particularly annoying if the story has a splitter https://nationalmap.gov.au/#share=s-5l6q7OgyHpMsFM3Jh7CmDKGZh7E and users want to interact with the splitter and have to close the story to get the full interaction.

**Comment by AnaBelgun** [comment]
@philipgrimmett please have a look and see if  this is a genuine issue

**Comment by chloeleichen** [comment]
This is because we basically don't have a story builder/editor on Mobile, therefore we only allow looking at story on mobile. 

1. A quick fix is to add a button on mobile that allow users to play stories again after they have previously closed stories.

2.  A better solution is to enable the story editing interface on mobile. This will require some new designs that fix the component into small screen. 

For the short term option 1 is probably enough, for story V2 we will need a proper mobile interface.
