### ISSUE TITLE
Model Architecture: Add catalog search provider and re-enable catalog search

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#3657]
Catalog search is currently hidden in mobx because it hasn't been implemented yet. Implement catalog search and unhide it from view.

**Comment by soyarsauce** [comment]
Port & generalise the approach used in https://github.com/TerriaJS/nsw-digital-twin/pull/220/files

**Comment by zoran995** [comment]
just one note, there will be one issue with WMS and WFS layers, this lines will throw an error on search https://github.com/TerriaJS/terriajs/blob/next/lib/Models/WebMapServiceCatalogItem.ts#L72-L78. 
Also just to mention #4723 adding another trait can enable the search of CatalogItems using description and other data properties.

**Comment by soyarsauce** [comment]
Hi @zoran995 
There's a basic (and admittedly buggy) implementation on `next` now, it won't call `load` so won't run into the wms/wfs layers problem (because the basic implementation only checks names/description), do you have a catalog search provider that calls `load` and looks at more traits?
http://ci.terria.io/next/

**Comment by zoran995** [comment]
I just found some time to port some of the things from our branch will start looking into it to create a PR so you can take a look. In our instance, I added a new definitionStratum for search, are you OK with that?
