### ISSUE TITLE
Bottom Dock remains off screen in Chrome

### ISSUE THREAD

**Issue by ebendennis** [TerriaJS/terriajs#3687]
Bottom Dock text row is appearing at the bottom of the page, but the timeline and charts remain off screen. Behavior is only seen in Chrome (Version 76.0.3809.132). Firefox and Safari are behaving as expected.

![image](https://user-images.githubusercontent.com/2745550/64733185-7f2d2900-d4a1-11e9-81e5-e003109e603d.png)

**Comment by ebendennis** [comment]
Reopening. I thought this might have just been an issue with my install, but was able to reproduce in a Windows version of Chrome. This issue does not appear in Chrome version 75, but is present in 76 and 77.

**Comment by kring** [comment]
Thanks for reporting it @ebendennis. This is a bug in Chrome's new layout engine, introduced in v76. There's a PR with a possible fix (we're verifying it) and some more details of the issue here:
https://github.com/TerriaJS/terriajs/pull/3686

As a temporary workaround, you can disable Chrome's new layout engine. Go to chrome://flags, search for `LayoutNG` and set it to Disabled.
