### ISSUE TITLE
What AWS instance type should TerriaJS run on?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#3713]
We would like to deploy a Terria endpoint on AWS, but we are not sure what instance type to use.    It seems that there isn't much memory or processing power needed, right?  

So would a `t2.nano` instance work? 

[This blog post ](https://www.concurrencylabs.com/blog/handle-thousands-of-users-with-a-t2-nano/) suggests that a `t2.nano` with CloudFront can work better than you might think!

Thoughts welcome!

**Comment by kring** [comment]
You're right, it doesn't need much memory or processing power. We often use t2.small for many of our deployments. The only reason we don't use t2.nano is because we like to run 4 terriajs-server processes in order to better parallelize requests, and t2.nano doesn't have enough memory for that. But you might very well be fine with running just two instances on a nano, or even adding a second nano in a different availability zone if you do need to scale it a bit.

**Comment by rsignell-usgs** [comment]
Well, I think we can probably afford a `t2.small`.   We'll probably just go that way then.  Thanks for the speedy response @kring!
