### ISSUE TITLE
Model Architecture: broken time series WMS

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#3715]
Steps to reproduce:
1. have a catalog with the item `https://gis.aremi.data61.io/bom/wms` as an item
2. open data catalog, open the wms group & add the `Solar_Satellite_DNI_2014` layer
3. observe crash

https://gis.aremi.data61.io/bom/wms
https://github.com/TerriaJS/TerriaMap/pull/387/files

<img width="466" alt="image" src="https://user-images.githubusercontent.com/9134432/66098842-9619f380-e5e7-11e9-99ac-de888b3bbff9.png">

**Comment by tephenavies** [comment]
Error is due to the WMS server using a not-yet-supported-in-mobx form of expressing the Extent of the time Dimension.
* WMS Spec:
![image](https://user-images.githubusercontent.com/13863530/66801969-a5455d80-ef66-11e9-8a58-1f30aa29f46e.png)

* See TerriaJS `master` WebMapServiceCatalogItem.js `updateIntervalsFromIsoSegments` (line 1583) for parsing and processing of syntaxes 3 & 4
- Work out if we can represent syntax 3 and 4 without splatting them into a huge list
	- What requires the list of intervals?

**Comment by tephenavies** [comment]
This issue still exists for WMS servers that use this form of interval specification, but is no longer a high priority.

**Comment by rowanwins** [comment]
No longer an issue. resolved by #3884
