### ISSUE TITLE
Story v2.0 - Story Mode - Add a "Play" button to the edge of the Story button when there is an active story

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3827]
If there is a Story in the session, and the user has closed it, it's not clear how to return to it.

We should display a highlighted "play" button when there is an active story, kinda like:

<img width="192" alt="Screen Shot 2019-11-29 at 11 30 33" src="https://user-images.githubusercontent.com/5283003/69833958-11bcb780-129c-11ea-8667-b1f55a0fde56.png">

Figma designs:
https://images.zenhubusercontent.com/17163720/3a9f7af1-422a-4e26-ab56-1ba80964d9fd/screen_recording_2022_02_11_at_3_43_59_pm.mov

**Comment by wibily** [comment]
refinement meeting: (Ana, Phi, Will)
- play story button in the bottom left corner (mobile only)
- play story button should only be visible in mobile view for share links with stories
- play story button should be hidden when playing the story
- play story button should start story from scene 0
Stretch goal: play story button should not be highlighted when the play/maybe layer modal is active and should be highlighted when that modal is dismissed

**Comment by wibily** [comment]
use story-20 button. Also update existing play story button in story builder to use the same icon.

**Comment by wibily** [comment]
@philipgrimmett 
Unable to complete prompts due to time constraints and I am worried about having enough time to do the story redesigns. Please see the below compromise:
![Screen Shot 2022-02-14 at 11.20.28 am.png](https://images.zenhubusercontent.com/60529acfe1747f58c17d9340/3d939c20-0428-4fc2-8626-d1e092d0da97)![Screen Shot 2022-02-14 at 11.20.34 am.png](https://images.zenhubusercontent.com/60529acfe1747f58c17d9340/6b31c5af-d679-4b9d-a331-397e766e98ee)

**Comment by philipgrimmett** [comment]
Thanks @wibily. I think this is something we'll need to complete in another ticket. Do mind creating one and adding @AnaBelgun and me?
