### ISSUE TITLE
Story v2.0 - Allow user to "reset" the scene after moving/adding/removing things

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4119]
When we are in a Story and the user has changed the view, added, or removed layers etc, allow the user to click on the currently selected Scene "dot" to reset the scene to what it is in the story. I.e. clicking on the dot will reset the view, the loaded layers, with the very same effect as if they had clicked Next and then Previous to return to the scene they are on.

**Comment by soyarsauce** [comment]
Feature for mats. (for demoing purposes)

**Comment by na9da** [comment]
I think we can break this down into a few things:
- [ ] The reset feature is currently broken in `main` branch. So we need to fix that.
- [x] If a user has removed an item from the workbench, then when resetting the story scene, the item should be added back into the workbench. This is the current behavior.
- [x] If a new item is added to the workbench while a story is playing and the user resets the scene, the item should be removed from the workbench. When a user tries to add a new item while the story is playing, we now close the story player, which means this requirement can no longer be met. 
- [ ] I also found a problem where when  switching between story scenes (or resetting a scene) we do not restore the traits exactly to what the scene describes. [For eg](http://ci.terria.io/main/#share=s-4m5v7sX3eEICQJFHHiI4ARFdp9s), if in a story, scene A has empty user traits and then scene B changes the opacity value to `0.42`, when switching from A -> B -> A, the opacity is not reset back to the default value. 
This happens because when switching between story scenes we [do not replace user stratum](https://github.com/TerriaJS/terriajs/blob/7c13c941fcce45f87c8dd597104154cb2429b7f8/lib/ReactViews/Story/StoryPanel.jsx#L40) so some state from the previous scene might carry over to the next scene. I think this was done to [prevent re-loading](https://github.com/TerriaJS/terriajs/pull/4063) the entire catalog item when switching between scenes. I think we need to figure out a way to reliably "sync" the traits when switching between two scenes without triggering unnecessary reloads.
One solution might be to add a new flag to `updateModelFromJson` called `syncStratum` which will do a nested "sync" of the model with new json data without replacing the stratum (and  without triggering a full reload).
