### ISSUE TITLE
Outstanding work on main UI tweaks

### ISSUE THREAD

**Issue by reginapramesti** [TerriaJS/terriajs#4294]
Copied over from https://github.com/TerriaJS/nsw-digital-twin/issues/353, this is the continuation of that issue (since the PR created for that issue had already been created and reviewed based on the initial requirements and the below are follow-up requirements)

> Hi @reginapramesti here are updates that are left to do for the UI tweaks. Let me know if one of these are out of scope for this issue:

- [x] 'Search for location' form field UI needs to be made to be dark
- [x] Helpful hints text in workbench has been updated
- [x] 'Explore map data’ & ‘Upload’ buttons should have rounded corners
- [x] Please update the upload button with the one attached. Ive made it slightly thinner to match the other icons
- [x] About icon is blue and it should be white
- [x] Measurement tool is missing. Re-insert and place in between location and compare icon (compare icon should be the last icon)
- [x] Resolve UI-related errors in console
- [x] Make help panel buttons 100% width even when no title is given

[upload.zip](https://github.com/TerriaJS/nsw-digital-twin/files/4442173/upload.zip)

**Comment by soyarsauce** [comment]
Hey @vicborgy I mentioned this somewhere but can't find it, for the location search box, you've got the magnifying icon on the right, but we've kept it on the left because we still don't know what to do for mobile, e.g.:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/9134432/82410011-54748500-9ab2-11ea-8713-95f6b7fec495.png">

Turns into this
<img width="458" alt="image" src="https://user-images.githubusercontent.com/9134432/82410036-622a0a80-9ab2-11ea-9dfe-c9e33cdc5250.png">

Can we have a "location search component" which accommodates whether there is a "X to close" or not?

**Comment by reginapramesti** [comment]
Measurement tool re-enabled here: https://github.com/TerriaJS/TerriaMap/pull/453

**Comment by vicborgy** [comment]
@soyarsauce sorry, I completely missed your message about search for mobile.

- I think the search icon can work exactly the same as desktop.
- Clicking the search icon would mean the field expands to the left and have the cursor active and the search icon would stay in place
- Once they start typing the search icon turns into a ‘X’ so clear the field
- Then clicking outside the field or on the search icon would close the search fie

**Comment by reginapramesti** [comment]
Note: after some discussions, we decided to keep the search box colour white.

**Comment by reginapramesti** [comment]
Resolved by #4332
