### ISSUE TITLE
MobX Change detection (Delta) - v3

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4390]
This epic reflects design and development post user testing done on 19-21 May 2020.

**Comment by soyarsauce** [comment]
Ana:
- add the dates as part of the input steps (right now it's 3 steps, 1. layer, 2. display style, 3. output style, (4) location). make location show by default instead of appearing(?), and some placemarker for date being part of the input.
- the dates remain at the bottom. Vic: but now there are labels to them. (Wing: Perhaps we put a date input in the steps that open the date picker?)

Nanda:
- clicking a point on a map is for filtering dates.
Ana: but by picking the point it lets you find the correct dates that apply to your region

Other feedback (marie/ana)
hard problem of "points representing a region":
- showing point as a point rather than updating a region. e.g. tip of the location selector, showing this is for a region rather than the specific point.
- for "filter by location", it's always for a region - the point is just to help filter for the region
- dates at the bottom.

Vic: wants to ensure any steps moving forward w/ Delta have long term planning of how they all fit together

**Comment by AnaBelgun** [comment]
19/06/2020
Latest Delta v3 design: https://projects.invisionapp.com/share/BXXRFD48YJ5#/screens

**Comment by soyarsauce** [comment]
~Wed morning @na9da to pass delta off to Wing & Regina

**Comment by soyarsauce** [comment]
@soyarsauce to clarify w/ @AnaBelgun on delta deliverables re: the two delta services, including the timeline for legend functionality

**Comment by AnaBelgun** [comment]
Considerations on legends' implementation. The challenge to tackle is to display 2 legends (legend 1 for initial imagery layer, and legend 2 for the result imagery layer). There are several options, depending on the service set up: 
1) show both legends separately as in Delta V3 design here https://projects.invisionapp.com/share/BXXRFD48YJ5#/screens; 
2) show one image with both legends: https://ows.dev.dea.ga.gov.au/legend/s2a_ard_granule_nbar_t/NBR/legend.png 

Method 1: Use the advertised style legend url and pass the undocumented ndates parameter:
https://ows.dev.dea.ga.gov.au/legend/s2a_ard_granule_nbar_t/NBR/legend.png?ndates=1
![image](https://user-images.githubusercontent.com/18452161/86861858-64503300-c10b-11ea-9fee-28a348243e01.png)

https://ows.dev.dea.ga.gov.au/legend/s2a_ard_granule_nbar_t/NBR/legend.png?ndates=2
![image](https://user-images.githubusercontent.com/18452161/86861879-6f0ac800-c10b-11ea-91ce-674c006e19d0.png)

Method 2: Use the GetLegendGraphic method and pass the styles and date parameters, as you would do with GSKY which doesn't advertise a style legend url.

![image](https://user-images.githubusercontent.com/18452161/86861840-5ac6cb00-c10b-11ea-919c-fb5dac4d9e1e.png)

**Comment by soyarsauce** [comment]
Critical thing left for this is the tangential relation of WMS legends in workbench
https://app.zenhub.com/workspaces/terria-frontend-ui-ux-5d802feb6b3dcf00019b6380/issues/terriajs/terriajs/4446

Nick is fixing

**Comment by soyarsauce** [comment]
Remaining backlogged items in v4 https://github.com/TerriaJS/terriajs/issues/4644, can confirm blocked issues are resolved
