### ISSUE TITLE
Related maps under workbench

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4566]
Related maps appears under the workbench in the `next` version 

![realated_maps_workbench](https://user-images.githubusercontent.com/19208948/88343227-368d0000-cd41-11ea-81f6-4b9fd91e5024.png)

**Comment by zoran995** [comment]
This seems to be related to changes in #4533, specifically after changes in https://github.com/TerriaJS/terriajs/commit/1df77cae30423ab6a8d9c1980c0b46a7867d4975

**Comment by reginapramesti** [comment]
I had a look at this and it seems to be because of the `overflow: hidden` property of `.tjs-standard-user-interface__map`, since the size of the related maps box goes beyond the bounds of the map section of the UI. If I remove that property it's displayed properly. Can you think of anything that would break if I fixed it by removing that property @soyarsauce?

**Comment by soyarsauce** [comment]
@reginapramesti 
`overflow: hidden` has been set on that class since 4 years ago - commit indicates it was for this:
> avoid indicator show up over side panel

So not sure what indicator blocks the side panel. Given anything in the right pane shouldn't spill out in the normal sense, it seems best to keep that style but revamp the side panel dropdowns to use `React.createPortal` in a similar sense to how the tooltipwrapper is done: https://github.com/TerriaJS/terriajs/blob/next/lib/ReactViews/Generic/TooltipWrapper.tsx#L161-L181

In the short term though, maybe we remove `overflow: hidden;` as we can't see any immediate adverse effects - and backlog the above suggestion. Sound good?

**Comment by reginapramesti** [comment]
Sounds good to me

**Comment by nf-s** [comment]
Closed by #4736
