### ISSUE TITLE
Show error message if Cesium Ion access token is invalid

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4739]

**Comment by wibily** [comment]
Pete: what is the purpose of showing the message if there's nothing the user can do about it?

**Comment by staffordsmith83** [comment]
> Pete: what is the purpose of showing the message if there's nothing the user can do about it?

There is still a purpose: It will notify the user why the map appears to be broken, so rather than think 'This is a terrible product' they realise that creds need to be updated. The use case is probably mostly for maps that we do not host - the users of those maps can then notify their admin. For example, getting a map that looks like this, there is nothing to indicate to non-technical users that there should be terrain underneath unless we show an error in the UI (not the console).
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7980991/211236841-66a6eb15-fcc4-4eea-b7c9-3b445db9c67d.png">

**Comment by staffordsmith83** [comment]
Found this in `Cesium.ts` - this appears to have been written to handle this situation and commented out at some point https://github.com/TerriaJS/terriajs/blob/7b67f0a17b40f0ff766e7c1a62034c645b6337bf/lib/Models/Cesium.ts#L233-L252

**Comment by staffordsmith83** [comment]
This is mostly working now, see linked draft PR: https://github.com/TerriaJS/terriajs/pull/6675
There are still a few errors that need fixing before merging
