### ISSUE TITLE
Story v2.0 - Better handling of popups 

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4793]
When the story is shared with the user that haven't dismissed the welcome message before, he will see the story prompt and welcome message at the same time. Just clean the local storage when opening this link https://nsw.digitaltwin.terria.io/#share=s-sJyPjY6UJ1bW6b0RWfV5zDl9xod
User can start the story while the welcome message stays open. Probably the better workflow would be to first show welcome message and after it is closed to show story prompt.

![story-welcome-message](https://user-images.githubusercontent.com/19208948/94364248-32c28480-00c8-11eb-8cc1-bb44909190b1.png)
![story-welcome-message-2](https://user-images.githubusercontent.com/19208948/94364267-4ff75300-00c8-11eb-8227-e09fc453ac1f.png)

**Comment by soyarsauce** [comment]
Related: https://github.com/TerriaJS/terriajs/issues/3958

**Comment by AnaBelgun** [comment]
More comments on same issue: 
1) One feature I would love is the ability to supress all Terria popups for specific stories (particularly those that are intended to be self-describing). For example, when visiting the DEA Coastlines story, first-time users are presented with the "Let's get you started" pop-up which appears on top of the story - we've had a few people come to us confused because pressing the big "Explore map data" button takes them away from the Coastlines story itself (if you're not familiar with Terria, this is enough to make you close the tab).

This could be solved by being able to toggle a "Suppress getting started" button when creating the story. Alternatively, perhaps that popup could be presented after the story is complete, not before?

2) Is there anything I can append to a story URL to supress the "Let's get you started" message on first load? Not a major issue, just looking to reduce confusion for new Coastlines users with lots of different popups (they potentially get up to three: get one for the disclaimer, one for the "get you started", one for "do you want to load the story" if they access without &playStory=1 included in the URL)

**Comment by wibily** [comment]
@AnaBelgun  
Should i simply disable the welcome popups for shared stories?
