### ISSUE TITLE
Consider behaviour of welcome modal when viewing share link

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4845]
From Robbi
> Is there anything I can append to a story URL to supress the "Let's get you started" message on first load? Not a major issue, just looking to reduce confusion for new Coastlines users with lots of different popups (they potentially get up to three: get one for the disclaimer, one for the "get you started", one for "do you want to load the story" if they access without &playStory=1 included in the URL)

**Comment by reginapramesti** [comment]
Also mentioned in https://github.com/TerriaJS/terriajs/issues/4793

**Comment by AnaBelgun** [comment]
One feature I would love is the ability to supress all Terria popups for specific stories (particularly those that are intended to be self-describing). For example, when visiting the DEA Coastlines story, first-time users are presented with the "Let's get you started" pop-up which appears on top of the story - we've had a few people come to us confused because pressing the big "Explore map data" button takes them away from the Coastlines story itself (if you're not familiar with Terria, this is enough to make you close the tab).

This could be solved by being able to toggle a "Suppress getting started" button when creating the story. Alternatively, perhaps that popup could be presented after the story is complete, not before?

**Comment by AnaBelgun** [comment]
Closing; superseded by https://github.com/terriajs/terriajs/issues/4793
