### ISSUE TITLE
Split screen feature not working (black and/or missing image)

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4858]
### Expected behavior
The split screen feature in V7 would allow you to compare two timesteps, by copying the satellite data layer and then allowing you to select the two dates you want to compare
see: http://maps.dea.ga.gov.au/#share=s-lNN2MOaUTQEfuygLdYZ4mbhqsn6 

### Actual behaviour
The split screen option is popping up a 'terrain position' legend item, and the map is missing data
![image](https://user-images.githubusercontent.com/19562367/95544804-ee2fd500-0a47-11eb-8bcc-5a1388436d9e.png)
see: https://de-australia.prod.saas.terria.io/#share=s-eY2BvDbgoA3D17Db6rYMFZdemb9 
(though it looks like the share link doesn't preserve my exact map set up)

### Steps to reproduce the behaviour
Load in 'daily Landsat and Sentinel-2 images', then select the 'compare' option for that layer from the legend panel.

**Comment by CEKrause** [comment]
Seems to only be an issue when the map settings are '3D terrain', which they are by default for me. It works as expected if I set the map settings to 2D.

**Comment by AnaBelgun** [comment]
@CEKrause hi. upon checking again if split behaves accordingly, I used 2 different dates and it looks like it return the results as expected (i.e. different imagery on left from right). 
![image](https://user-images.githubusercontent.com/18452161/95691767-5ad7e900-0c6d-11eb-9f41-dcb69b174180.png)
https://de-australia.prod.saas.terria.io/#share=s-dOGgOQ9qlhcfjkPlEkiuOS2HWgr
I suspect the actual problem is the confusion created by the additional legend item which asks the user to select the terrain position. That is set on "both" by default to overcome that issue. 
It is used only for cases when users have underground data, such as pipelines for example.

**Comment by robbibt** [comment]
@AnaBelgun Is that "Terrain position" option required when no layers added to the map contain underground data? Feels like that's a pretty niche case that might be better hidden unless required to avoid user confusion (especially as it's so prominently placed up the top)

**Comment by AnaBelgun** [comment]
yes, I agree @robbibt will feed that back to design and dev for further enhancements; we'll not hold the release on v8 on this issue 
will submit a specific issue for further developments

Here is the design issue ticket: https://github.com/TerriaJS/terriajs/issues/4863
