### ISSUE TITLE
TerriaJs doesn't accept config sent via `postMessage`  anymore

### ISSUE THREAD

**Issue by t83714** [TerriaJS/terriajs#4880]
### TerriaJs doesn't accept config sent via `postMessage`  anymore

TerriaJS used to accept config sent via `postMessage` --- see the document below:

https://docs.terria.io/guide/deploying/controlling-in-an-iframe-or-popup/

The relevant code is here:

https://github.com/TerriaJS/terriajs/blob/master/lib/ViewModels/updateApplicationOnMessageFromParentWindow.js

It seems this communication option doesn't work anymore.

#### How to re-produce
- Clone Magda repo
- Go into `magda-web-client` module
- Modify `magda-web-client/src/Components/Common/DataPreviewMapOpenInNationalMapButton.js` and update all `https://nationalmap.gov.au/` URLs  to `https://nationalmap.dev.saas.terria.io/`, and change catalog type from `type: "magda-item"` to `type: "magda"`.
- run `yarn dev`
- Search credit license dataset (please note our dev site is a bit slow if see an error please just re-search)
- Go to map preview
- Click open national map button

**Comment by mwu2018** [comment]
The v8 `terriajs` actually still supports `postMessage`. The `magda-web-client` fails to send message to v8 national map at https://nationalmap.dev.saas.terria.io/ because this line is commented out:
https://github.com/TerriaJS/terrace/blob/5850d850477b0b4369c7c10e3db107879d63b21c/index.js#L200

**Comment by soyarsauce** [comment]
Yep! When you confirm it is all working well, we should actually resolve this in upstream TerriaMap via https://github.com/TerriaJS/TerriaMap/blob/next/index.js#L95

**Comment by mwu2018** [comment]
After enabling post message in [TerriaMap](https://github.com/TerriaJS/TerriaMap/blob/c76159ddb7ef7326cb3f6a028f6322699eb4e3ea/index.js#L95), `magda-web-client/src/Components/Common/DataPreviewMapOpenInNationalMapButton.js` described in `How to re-produce` is able to post message to the map. The message looks like
![image](https://user-images.githubusercontent.com/41275384/96545230-b6504980-12f3-11eb-8da4-68c400d00592.png)

However, if the map is a production build, when parsing the received data, `Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build` occurs in function [interpretStartData](https://github.com/TerriaJS/terriajs/blob/552469ef588248dd0253f3b40791f4d037a7b34e/lib/Models/Terria.ts#L1190).

If the map is a dev build, the error will be 
```
Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action`
```

**Comment by tephenavies** [comment]
`interpretStartData` should be made into an action (by adding `@action`) since it modifies (`.push`) the observable `terria.initSources` @mwu2018

**Comment by nf-s** [comment]
I believe this is working now
