### ISSUE TITLE
Use NPM/Bower dependency instead of git submodule for Cesium

### ISSUE THREAD

**Issue by jfnavin** [TerriaJS/terriajs#503]
It would be good if the dependency on Cesium was managed via NPM/Bower along with the other dependencies instead of as a Git submodule.

That way we can be sure of which version of Cesium is being used at any given point in time and will be able to reproduce builds in the future. It also means we don't have to re-build Cesium with every build of National Map.

e.g. https://www.npmjs.com/package/cesiumjs

**Comment by kring** [comment]
Hi @jfnavin,thanks for the suggestion!

While I certainly see the appeal of managing Cesium as an NPM module, I don't think it is the right approach - at least currently - because:
- National Map uses Cesium's in-progress KML support, which isn't in an official release.
- National Map contains a number of customizations to Cesium.  Most of these will eventually be pushed back into Cesium, but we're not there yet.
- Work on National Map often involves making changes to Cesium.  Submodules make this easy, NPM modules do not.
- National Map builds against individual Cesium modules, so it only includes the Cesium code that it actually uses.  Pulling in cesium.js as an NPM module would make National Map's download size bigger.
- The Cesium NPM module is not officially supported by the Cesium developers.  A member of the community set it up.

And to address your concerns with the submodule approach:
- The submodule precisely specifies the Cesium code that we're using.  It's usually the "nm" branch in the main Cesium repo.  So determining what version of Cesium is being used and reproducing it should not be a problem.
- The initial 30 second build of National Map is a bit painful, but we don't need to wait that long very often.  We use the `gulp watch` task while working on National Map so that changes generally only trigger about a 2-3 second build.

**Comment by jfnavin** [comment]
Hi @kring - thanks for the reply.

I'm not very familiar with Git submodules, but it appears as though the .gitmodules configuration is just pointing to the head of Cesium master, which would mean that doing an update would update it to the latest in head. Or have I understood it wrong? The only way I can see that the submodule mechanism precisely specifies the Cesium code is if it references a particular commit or tag etc. and I can't see where that's being done in this case.

It also looks a bit odd to me to have a 'nm' branch in the main Cesium repo... that looks a bit like Cesium being dependent at least loosely on the National Map project, which seems odd. Was there a particular reason that the Cesium repo wasn't forked for the National Map project to handle these updates and then merged using PRs etc.?

**Comment by kring** [comment]
You're right that `.gitmodules` doesn't refer to a precise version, but there is one stored in the git metadata (sorry, I'm not sure of the exact mechanism).  For example, go here:
https://github.com/NICTA/nationalmap/tree/master/third_party

And notice that GitHub reports that the cesium directory is the Cesium repo at a particular hash, and provides a link to it.

> Was there a particular reason that the Cesium repo wasn't forked for the National Map project to handle these updates and then merged using PRs etc.?

Not a great one.  I have commit access to Cesium, the Cesium guys didn't mind, and I was lazy.  A fork would be a bit cleaner perhaps, but also create a bit more work for moving changes between the projects.

The overall goal is to make it easy to move changes made in National Map into Cesium proper via pull requests, and this approach does a fine job of that.

**Comment by kring** [comment]
Just to be clear, there's no National Map code in the `nm` branch of Cesium.  It's just changes to Cesium to support National Map.

**Comment by kring** [comment]
Despite all my arguing against it before, this is exactly what I did when we split out [terriajs](https://www.npmjs.com/package/terriajs) from National Map.  Cesium is now loaded from the [terriajs-cesium](https://www.npmjs.com/package/terriajs-cesium) npm module.
