### ISSUE TITLE
Add `itemProperties` to all CatalogGroups

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#5155]
`itemProperties` should be available for all CatalogGroups

**Comment by wibily** [comment]
nick: should be done at groupMixin level unless too hard

**Comment by wibily** [comment]
this property exists on a few random groups, figure out a way to make this sane

**Comment by wibily** [comment]
nanda: group can have different items and need to ensure that traits are applicable to all of htem

**Comment by tephenavies** [comment]
#### I've read through a lot of groups and my thoughts so far are:
Groups that implement `itemProperties` (mostly?) do it by setting properties from itemProperties on the underride stratum:
https://github.com/TerriaJS/terriajs/blob/b359a16cf18723516698ea969c593b1bc1b30820/lib/Models/Catalog/Esri/ArcGisMapServerCatalogGroup.ts#L253-L267

This works well on a per-group basis, but is hard to port to a Mixin (because each group sets not only the properties from `itemProperties`, but also additional properties that need to be passed down - note `name` & `url` above). Deleting and setting the underride stratum in GroupMixin as well as in the group would result in one of them being destructive to the other.

Thoughts/ideas:
* Have a new stratum for `itemProperties` separate to underride for other properties that are passed down
* I'll have to pass only properties that match the model down, or avoid errors with passing down non-matching properties

This is interesting, potentially useful for creating an `itemProperties` stratum:
https://github.com/TerriaJS/terriajs/blob/f809727b59bc955deb20545de67a6718791b069e/lib/Models/Catalog/Ckan/CkanCatalogGroup.ts#L27-L48

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6218
