### ISSUE TITLE
Fix AsyncLoader.isLoading + other loading issues

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#5233]
At the moment, we can't observe `isLoading` without cause these errors:

```
Error: [mobx] Computed values are not allowed to cause side effects by changing observables that are already being observed. Tried to modify...
```

**Comment by nf-s** [comment]
Might be able to do something with `fromPromise(this.loadKeepAlive).state`...

**Comment by tephenavies** [comment]
That actually might not work because I think observing `fromPromise(this.loadKeepAlive)` will cause the AsyncLoader to reload without `load` being called again.

**Comment by nf-s** [comment]
Yep! that is what happened when I tried it.
I think that approach may work as long as we wait until the first `load` is called before observing `this.loadKeepAlive`.

**Comment by tephenavies** [comment]
I think it'll still continue to reload in some circumstances without subsequent calls to `load`. It's important to the mechanics of AsyncLoader that `this.loadKeepAlive` is never observed. I think `.load` should even be an action so that calling `.load` from inside a computed doesn't end up with `this.loadKeepAlive` being observed.

**Comment by KeyboardSounds** [comment]
Also see https://github.com/TerriaJS/terriajs/issues/5324

**Comment by tephenavies** [comment]
Just talked to @nf-s about potential AsyncLoader improvements.

One thing we discussed is that AsyncLoder doesn't work when promises need to be chained. It's not possible to chain AsyncLoaders to do this. However you could apply the inner idea of AsyncLoader (which is to run parts where you decide/calculate how to load data/metadata etc. inside a keepAlive computed that's unobserved) and allow creating these keepAlives from promises. If you extend this to making your own `mobx.flow` function you could achieve something like this:
```js
const load = loaderFlow(function*() {
  const url = this.url;
  const res = yield loadFromJson(url);
  yield function() {
    this.setTrait(x, y, res.foo);
  };
  const url2 = `${this.url}/${res.path}`;
  const res2 = yield loadFromJson(url2);
  yield function() {
    this.setTrait(x2, y2, res2.bar);
  }
});
```
Note due to the computeds that will be applied to each synchronous part any actions that need to be performed need to be yielded as functions. These would be wrapped in `action`.

Potential difficulties:
* Avoiding reloading from secondary URLs when data from the first load is the same and it could be detected that loading from the secondary URL is not necessary
* Working out how to clean up the keepAlives. Hopefully `loaderFlow` could keep track of these

**Comment by nf-s** [comment]
Let us close this for the moment - this PR has been merged https://github.com/TerriaJS/terriajs/pull/5310
We can look at improvements later
