### ISSUE TITLE
Certain KML/KMZ files cause browser to stop responding

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#547]
Several of the files on http://breakingthesolargridlock.net/downloads.html when dragged onto the NM (including nm.research) cause the browser tab to stop responding; it cannot be refreshed and must be closed to continue. I have also tried extracting the kml file from the kmz and it also has the same effect.

Tested on Chrome for Mac Version 40.0.2214.115.

**Comment by kring** [comment]
We either need to wait for this to be fixed upstream in Cesium, or we need a reason to spend a lot of time on it, because it's very unlikely to be an easy fix.  Since it hasn't come up again in almost a year, I'm going to close this.  If there's a pressing need to make a certain KML file work better, please open a separate issue.
