### ISSUE TITLE
both v7 & v8 won't render CSV file has `id` column correctly

### ISSUE THREAD

**Issue by t83714** [TerriaJS/terriajs#5548]
# both v7 & v8 won't render CSV file has `id` column correctly

At this moment, both v7 & v8 terriajs won't render theCSV file has `id` column correctly.

e.g. the CSV file below:

[au-towns-sample-with-geo.csv](https://github.com/TerriaJS/terriajs/files/6652159/au-towns-sample-with-geo.csv)

It contains a `id` column.

Both [national map](https://nationalmap.gov.au/) (v7) or [NSW DT](https://nsw.digitaltwin.terria.io/) (v8) will not show the data points (as screenshot below) probably.
- National map will report an error message
- NSW DT will simply not show any data point on the map

**The correct render result should be:**

![image](https://user-images.githubusercontent.com/674387/121980140-ce1e9580-cdce-11eb-8d02-2a531ab045a3.png)

## Extra info:
Seems you can fix the issue with either of the following ways:
- remove the `id` column from the CSV file
- rename the `id` column to uppercase `ID`

**Comment by hardreddata** [comment]
This is by design.

I understand Terria csv handling is built to follow this specification https://github.com/TerriaJS/nationalmap/wiki/csv-geo-au which includes _MUST NOT contain a column with header name: id. Note: uppercase ID column is allowed._

That said, I am not sure why this should be the case.

**Comment by nf-s** [comment]
This case is now supported
