### ISSUE TITLE
Gazetteer search results should show more details of location

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#556]
Using the gazetteer search for a suburb or city name will almost always return multiple results (eg cities/suburbs with the same name in different areas).  It currently isn't possible to distinguish these results without clicking on it and seeing where it goes on the map.  The search results should show additional info about the location (eg one option would be to do: if suburb, show city and state - if city, show state) to allow the user to quickly get to the intended location

**Comment by hilarycinis** [comment]
@kgrochow @kring is this info held in the data? 
![placenames_locations](https://cloud.githubusercontent.com/assets/6046521/6471145/c2fb6100-c23c-11e4-8fdc-0e90f1f2466d.png)

**Comment by hilarycinis** [comment]
This came up a few times in usability testing. The lack of state or suburb level labelling reduced the trust in the results. (when asked how they felt about this content)

**Comment by stevage** [comment]
Adding states [was easy](https://github.com/NICTA/nationalmap/pull/652).

The change also ranks cities and suburbs above other kinds of places.

To list city names as shown in the UX mockup would be much more difficult, as that information is not immediately available.

Search terms that return many results are also harder to correctly handle, as the Gazetteer returns a subset of results in no useful order. "Park St" for instance returns 384 results, but even with my change, we only get the first 200. This particular query is particularly pathological because most of the results are actually parks, not streets.

@hilarycinis, to answer your question, here's what the Gazetteer returns:

```
_version_: 1487538539975409700
alias: ["See SA Gazetteer"]
authority_id: "SA"
class_code: "P"
feature_code: "RESV"
id: "SA0071780"
location: "-33.95462,139.54953"
map_100k: "6830"
name: "White Dam Conservation Park"
state_id: "SA"
status: "U"
```

`feature_code` is a controlled vocab of ~100 types ("RESV" is "Reserve"), and `class_code` (A-X) is a grouping of `feature_code`s. So we have `state_id` (in many, but not all, cases), but no city. To get a city name would require some additional reverse geocoding step (which I don't know if GA can do).

**Comment by hilarycinis** [comment]
Yep cool. Some kind of frame of reference is better than none. I'm happy with a state level reference. Thanks heaps

**Comment by stevage** [comment]
Whoops, minor correction, "Park St" actually returns 16,000 results. I can't think of any way to sensibly handle this query short of parsing query texts for terms like "St" and "Rd" and pre-filtering results for roads. Could be a fun rabbit hole :)

Or maybe location-sensitive searching (#657)
