### ISSUE TITLE
TerriaJS v7 to v8 - Jul 21 Release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5594]
By v8 release we understand taking the steps to switch current "master" https://github.com/TerriaJS/terriajs/tree/master to the "next" branch https://github.com/TerriaJS/terriajs/tree/next. Focus on critical / breaking changes, guides and communication to community. 

3 streams / Objectives: 
### **1) **Critical migrations/breaking changes**** 

**Error handling** - https://github.com/terriajs/terriajs/issues/3486
- [x] https://github.com/terriajs/terriajs/issues/5454 - high
- [x] ~https://github.com/TerriaJS/terriajs/issues/5459 - high~
- [x] https://github.com/terriajs/terriajs/issues/4898
- [x] https://github.com/terriajs/terriajs/issues/5416

**Deprecations**
- [x] https://github.com/TerriaJS/terriajs/issues/4212 - high

**Other**
- [x] https://github.com/TerriaJS/terriajs/pull/5611 - high
- [x] #5382 - high
- [x] https://github.com/terriajs/terriamap/issues/534

### **2) **Consistency** - Model Layer architecture and consistency**
- [x] https://github.com/TerriaJS/terriajs/issues/5641 - high 
- [x] https://github.com/TerriaJS/terriajs/issues/5599
- [x] https://github.com/TerriaJS/terriajs/issues/5600 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5492 - high
- [x] https://github.com/TerriaJS/terriajs/issues/3441 - high

### 3) Community - High priority
**Documentation, guides, warnings etc.**
- [x] https://github.com/TerriaJS/terriajs/issues/4212 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5031 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5637 - high
- [x] https://github.com/TerriaJS/terriajs/pull/5351 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5639 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5645 - high
- [x] https://github.com/TerriaJS/terriajs/pull/4688 - high
- [x] https://github.com/TerriaJS/product/issues/28 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5667 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5668 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5638 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5669 - high
- [x] https://github.com/TerriaJS/terriajs/issues/5670 - high

**Catalogue converter**
- [x] https://github.com/TerriaJS/catalog-converter/issues/3 - high
- [x] https://github.com/TerriaJS/catalog-converter/issues/44 - high
- [ ] https://github.com/TerriaJS/terriajs/issues/5467

**TerriaMap (fork) on v8**
- [x] https://github.com/TerriaJS/TerriaMap/issues/536 - high

Planning included: 
- [x] https://github.com/terriajs/product/issues/63 - Closed
- [x] https://github.com/TerriaJS/terriajs/issues?q=is%3Aopen+is%3Aissue+label%3AV8-release+label%3Av8-model-layer-consistency
- [x] https://github.com/TerriaJS/terriajs/issues?q=is%3Aopen+is%3Aissue+label%3AV8-release

**Comment by AnaBelgun** [comment]
Post launch tasks - to be refined and re-prioritised based on user feedback https://github.com/TerriaJS/terriajs/issues/5677

**Comment by AnaBelgun** [comment]
v8 draft launch checklist: 

On 9th of August, at 1:00pm AEST start: 

- rename next branch = main and set as default branch
- rename master branch = v7.x.x
- npm publish - remove alpha tag and start 8.0.0 tag
- modify CI script, github actions with new branch name
- swap terria map (used for forks) to v8.0.0
- npm release - attention to configuration 
- ReadME in TerriaJS (both main and v7.x.x) and Terria map (fork) - updated version of TerriaJS 
- ReadME - link to documentation https://docs-v8.terria.io/guide/ 
- helm chart terria map - attention to Bing key - include a link to Bing geocoder free key for developers and provide instruction in getting started on how to configure the key
- https://github.com/terriajs/terriamap/issues/538

**Comment by tephenavies** [comment]
### V8 release checklist
- [x] Merge https://github.com/TerriaJS/terriajs/pull/5454
- [x] https://github.com/TerriaJS/terriajs/pull/5717
- [x] https://github.com/TerriaJS/terriajs/pull/5626
- [x] https://github.com/TerriaJS/terriajs/pull/5712
- [x] https://github.com/TerriaJS/catalog-converter/pull/47
- [x] Add more PRs to the list here
- [x] PR & merge migration guide
- [x] Link to v7 docs from v8 docs

terriajs rollout:

- [x] PR to master: modify GH actions to branchname v7.x.x, update README, change npm publish bot script publish tag `terriajs7`
- [x] PR to next: merge in master (needs care for translations and weblate), modify GH actions to branchname main, update README, change npm publish bot script publish tag (merge PR - https://github.com/TerriaJS/terriajs/pull/5723 - other actions not done)
- [x] Rename next as main in GitHub (see [renaming a branch](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch))
- [x] Make a local commit to main that is a merge from main into master (to get normal git history while allowing us to rename branches so that PRs to next stay as PRs to main)
- [x] Check that this merge looks like PRing next to main, and then push this to main
- [x] Set main as default branch in terriajs repo settings
- [x] Rename master as `terriajs7` in GitHub
- [x] Update config of external services: netlify & weblate
- [x] Release 8.0.0
- [x] Release a new version of v7 with updated terriajs-server version
- [x] Switch TerriaMap branches (see below)
- [x] Switch over docs.terria.io to point to v8 docs
- [x] Fix the `ci-deploy.sh` scripts of `main` and `terriajs7`

TerriaMap rollout:

- [x] Merge this TerriaMap PR: https://github.com/TerriaJS/TerriaMap/pull/534
- [x] PR to master: modify GH actions branch names, update README, use latest terriajs@7
- [x] PR to next: modify GH actions branch names, update README, merge https://github.com/TerriaJS/TerriaMap/pull/542
- [x] Rename next as main in GitHub (see [renaming a branch](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch))
- [x] Make a local commit to main that is a merge from main into master (to get normal git history while allowing us to rename branches so that PRs to next stay as PRs to main)
- [x] Check that this merge looks like PRing next to main, and then push this to main
- [x] Set main as default branch in TerriaMap repo settings
- [x] Rename master as terriajs-v7 in GitHub
- [ ] Convert all catalogs in `main` to v8 - https://github.com/TerriaJS/terriajs/issues/5743

**Comment by AnaBelgun** [comment]
This https://github.com/TerriaJS/terriajs/issues/5743 will be worked on independently.
