### ISSUE TITLE
v7 - v8 migration: CatalogueGroup missing property - Custodian

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5746]
CatalogGroup: property missing - custodian

**Comment by wibily** [comment]
check that this hasn't been moved somewhere

**Comment by nf-s** [comment]
This is done, there is `dataCustodian` in `CatalogMemberMixin` (which is included in all groups)

https://github.com/TerriaJS/terriajs/blob/05029ed7b9a1fa7cd633f0265b5d221e6855fc7a/lib/Traits/TraitsClasses/CatalogMemberTraits.ts#L202-L208

I believe this issue was created due to an incorrect `custodian` property which should have been `dataCustodian` in `National Datasets/Water/Surface Water/Water Stations Data`. I will manually correct it

**Comment by nf-s** [comment]
https://github.com/TerriaJS/natmap-catalog-v8/pull/29
