### ISSUE TITLE
Mobile: Hide filter location option on Satellite Imagery 

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5789]
@AnaBelgun could you please add reproduction steps and screenshots to this ticket.

- Go to NationalMap 
- Select Satellite Imagery group 
- Select Satellite Images - 10m pixels - Sentinel 2 definitive - Sentinel 2A 
- Add to the map 
- Open the workbench view from the Eye button 
- Click "Filter by location" 
- A popup with "Select a point by clicking on the map" and "Cancel" appear
- You can only action the Cancellation because the map is obstructed by the workbench view 

![image](https://user-images.githubusercontent.com/18452161/131946692-09601846-ab65-4b6d-a41f-d6892023bf5c.png)

**Comment by na9da** [comment]
In this PR (https://github.com/TerriaJS/terriajs/pull/5800), instead of hiding the button altogether, I am hiding the mobile modal when a user interaction is happening. So if the user clicks filter-by-location, the modal window showing the workbench will be hidden so that the user can pick a location. Once the location is picked or the action is cancelled, the workbench re-appears. 

Link to test the behavior: TBD.

**Comment by AnaBelgun** [comment]
@na9da your suggestion sounds much better. cc: @philipgrimmett
