### ISSUE TITLE
[Styled Components] Structure to support RTL languages.

### ISSUE THREAD

**Issue by malnajdi** [TerriaJS/terriajs#6024]
Greetings, 

I have tried to use TerriaMap with dir='rtl' and it seems a lot of issues are showing. 
I looked into the current styled components and it seems there isn't a support for an RTL check within the components, there for adding such capability can be difficult. 

I have already implemented a way where i check for 
`const isRTL = i18next.dir() === 'rtl';`
and i pass this to all styled components to adjust the needful. 

If there is a better way kindly let me know so me and the team can start pushing for the pull-request for Full RTL & Arabic Support

**Comment by KeyboardSounds** [comment]
@malnajdi could you give us an example of what your ideal implementation of this would look like? The workaround you've provided doesn't seem too cumbersome to me, I'm not sure what I'm missing.

**Comment by malnajdi** [comment]
@KeyboardSounds So the problem is we will have to define 
`const isRTL = i18next.dir() === 'rtl';`
in every styled component to be able to support rtl. Or we can add it as a props and reuse it.
If you approve a way we can support all styled components to have RTL feature for languages that depends on RTL.

Example:
https://github.com/TerriaJS/terriajs/blob/14e5d039fc147e11fe473d72b3d368b0cae33ca7/lib/Styled/Text.tsx#L40
here we need to add `textAlignRight` and if dir is RTL we need to use the textAlignRight instead of left and respectfully for all styled components,

**Comment by KeyboardSounds** [comment]
We could use https://reactjs.org/docs/context.html to provide an isRTL prop, but I am not a huge fan of it. I actually prefer the explicitness of manually importing slices of global state in the places you need it (which is what you're dong at the moment by calling `i18next.dir()`) rather than doing it through props because:
- It’s more composition over inheritance compliant. Providers are somewhat hierarchical inheritance style
- It makes it easier to track what comes from where (although if you know that isRtl is always a context prop it’s not really a huge difference)

What do you think about just exporting a function like:
```
import i18next from "i18next";

export function isRTL() {
  return i18next.dir() === 'rtl';
```
and then calling that? I don't think it's any more verbose than a prop.

**Comment by zoran995** [comment]
@KeyboardSounds my 2 cents, if going function way should we also do something as proposed in #5706 for `useTranslationIfExists`?
I would consider context way only if there is a plan starting to use it more throughout the app in the future i.e. some of the `Terria.ts` and `ViewState` properties passed down through context, but using it only in this case would be overkill IMHO

**Comment by malnajdi** [comment]
Keep in mind that i have seen the a very difficult logic somewhere that i was not able to fix for RTL, this logic seems to determine the screen width etc..
https://github.com/TerriaJS/terriajs/blob/e83fe2b40926f7544fd10d7063a9c6bd4d715911/lib/ReactViews/Tour/TourPortal.jsx#L228
