### ISSUE TITLE
Add `&outputFormat=JSON` to WFS requests

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#621]
Perhaps this has already been raised. When clicking the "use the link below to download GeoJSON data" link, there isn't (always?) the necessary `format=geoJSON`.

For instance: [this](http://geoserver.nationalmap.nicta.com.au/geotopo_250k/ows?service=WFS&version=1.1.0&request=GetFeature&typeName=Hydrography:pondageareas&srsName=EPSG%3A4326&maxFeatures=1000) returns GML, it should be [this](http://geoserver.nationalmap.nicta.com.au/geotopo_250k/ows?service=WFS&version=1.1.0&request=GetFeature&typeName=Hydrography:pondageareas&srsName=EPSG%3A4326&maxFeatures=1000&outputFormat=JSON).

**Comment by kring** [comment]
One gotcha is that not all WFS servers support GeoJSON.

**Comment by stevage** [comment]
Ok, possible solutions to that:
1. Store a flag on the ones that do
2. Provide two links (one WFS default, one GeoJSON)
3. Try the GeoJSON link, and if the result is bad, fall back to GML? (But seriously, who ever wants GML)? Also, GeoServer seems to reply HTTP 200 even if outputFormat is not supported.

**Comment by kring** [comment]
Yep, we should be able to determine which formats are supported by querying `GetCapabilities`.

WMS servers always respond 200 I believe, even on error.  A nice example of late-90's / early 2000's, HTTP-ignoring web service design!

**Comment by kring** [comment]
We don't have too many datasets that use automatically-generated WFS URLs as the "Data URL" anymore.  But if you add a WMS URL like this from My Data:
http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows

You can see the generated Data URLs and observe that they return GML.  So, the thorough way to do this is: When loading a WMS layer that doesn't already have a `dataUrl`, do a WFS GetCapabilities request.  If that fails, the server doesn't support WFS so we shouldn't list that as the data URL at all.  If it works, look at the list of supported feature formats and choose one.  We'd probably prefer GeoJSON if it's available, but otherwise just leave it unspecified and let the server give us its default.

**Comment by rowanwins** [comment]
See https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebFeatureServiceCatalogItem.js#L46-L62

We currently attempt to load GeoJSON first, and if we can't we fall back to GML
