### ISSUE TITLE
Data URLs should point to a data.gov.au download page

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#624]
**Where data.gov.au is the custodian:** 
Data URLs (e.g. Taxation Statistics 2011-2012) should point to a data.gov.au download page.

**Options:**
By set: https://data.gov.au/dataset/taxation-statistics-2011-12
By file: WMS: https://data.gov.au/dataset/taxation-statistics-2011-12/resource/c1eeeb7d-797d-4a7f-80a1-dd45aedae459

**Comment by stevage** [comment]
Hmm. This dataset turns up twice, once under National Datasets, once under data.gov.au. In the first case, there is a direct download link (maybe added since you reported this?)

![taxation-national-datasets](https://cloud.githubusercontent.com/assets/678344/7312494/8d8fbafa-ea8e-11e4-9ae8-d6ab9cf4d8d0.png)

Under data.gov.au (that is, fetched automatically), it's ugly:

![taxation-data-gov-au](https://cloud.githubusercontent.com/assets/678344/7312500/96704a18-ea8e-11e4-95d2-a8da42ffbfc9.png)

This does raise a side issue: We don't (I think) have a way to set nice data URLs on automatically fetched layers

**Comment by kring** [comment]
`CkanCatalogGroup` should be smarter about setting the `dataUrl` of the catalog items it creates.  I thought it used to do this, but maybe it was lost somewhere along the way.
