### ISSUE TITLE
Empty category haiku formatting

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#633]
When there is an empty category the message shown is very haiku-like:

![screen shot 2015-04-16 at 12 07 58](https://cloud.githubusercontent.com/assets/5283003/7172869/d15521a2-e431-11e4-8e77-0bc6c57d55f3.png)

A free flowing message would be less endearing but more proper. :)

**Comment by stevage** [comment]
Or just a visual indication of emptiness like:

## Hybrid/Enabling:

Or better still, grey out (or even hide) the parent group?

**Comment by kring** [comment]
I don't think hiding the group would be wise because sometimes we don't know if a group has items until the user tries to open it (e.g. a `wms-getCapabilities` group).  It would be rude to make a group disappear upon opening.

IMO a dash or graying out the parent group would be too subtle, but I'll let @philipgrimmett weigh in on that.  For now I've just fixed the haiku-ness.

**Comment by stevage** [comment]
Good point.
