### ISSUE TITLE
TerriaJS release 8.2.10

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6385]
- [x] https://github.com/TerriaJS/terriajs/pull/6455/
- [x] https://github.com/TerriaJS/terriajs/pull/6459
- [x] https://github.com/TerriaJS/terriajs/pull/6460/
- [x] https://github.com/TerriaJS/terriajs/pull/6463
- [x] https://github.com/TerriaJS/terriajs/pull/6383
- [x] https://github.com/TerriaJS/terriajs/pull/6465
- [x] https://github.com/TerriaJS/terriajs/pull/6467/
________________________________________________________________________________________________________
- [x] https://github.com/terriajs/vic-digital-twin/issues/363
_________________________________________________________________________________________________________
- [ ] https://github.com/TerriaJS/terriajs/pull/6216

**Comment by MoRadwan74** [comment]
Hello @nf-s 

I'm one of the contributors to PR #6216. We noticed that this PR is always postponed to the next release (from 8.2.5 to 8.2.10) and I can't figure out why.

If anything we can do to help with the verification process, we're glad to help surely.

We're eager to have it on a terriaJS release instead of having an out-of-the-upgrade-loop custom terriaJS.

**Comment by tephenavies** [comment]
Hi @MoRadwan74. Review/merging the PR has been pushed back a few times because we've had pieces of work come up unexpectedly that left us without the capacity to properly review/test it. I have some time today to review the PR.

**Comment by AnaBelgun** [comment]
hi @MoRadwan74 just to let you know that we have paused a bit reviews atm to be able to work on unexpected issues. 
We're hoping to restart the review process after the 22nd of August. We will keep your PR in our pipeline so it gets attention first.
