### ISSUE TITLE
Create sharelink should use `baseUrl` instead of `window.location`

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6391]
- https://maps.dea.ga.gov.au/story/DEACoastlines
- Click Share
- https://maps.dea.ga.gov.au/story/DEACoastlines#share=s-usNBqERvxnRFzfjgf1G14W0ijSC
- **But should be** https://maps.dea.ga.gov.au/#share=s-usNBqERvxnRFzfjgf1G14W0ijSC

**Comment by robbibt** [comment]
Can confirm I have encountered this one using this workflow:

1. Load a "pretty" new-style story map link: https://maps.dea.ga.gov.au/story/DEACoastlines
2. Remove the story by clicking "Story > Remove all".
3. Zoom into a new location and create a new share link

The new share link will still point to the removed story, not the customised share link: https://maps.dea.ga.gov.au/story/DEACoastlines#share=s-tvmuSTDLg7IyoYs6wzzb0phXlND

Because we always share DEA Coastlines using the "pretty" URL, this bug effectively prevents users from using the share link functionality to share DEA Coastlines data for a specific location or view (unless they learn how to add DEA Coastlines manually from DEA Maps itself (instead of via the story)

**Comment by staffordsmith83** [comment]
Im not sure how to replace `window.location` with `terria.baseUrl`
`baseUrl` just points to "build/TerriaJS/"
Seeking clarification
