### ISSUE TITLE
Bing logo image link broken in attribution

### ISSUE THREAD

**Issue by staffordsmith83** [TerriaJS/terriajs#6473]
When clicking on the "Basemaps" attribution button in the footer, with Bing basemap selected, we get:

![image.png](https://images.zenhubusercontent.com/62673fa28d46e59cec18c8f1/157702ec-2e1e-415f-8712-647650ddb017
)

![image.png](https://images.zenhubusercontent.com/62673fa28d46e59cec18c8f1/e32ae4e7-93b4-4cf2-90e3-f1e0ecd433fa)

The request is being made to:
https://test.vic.digitaltwin.terria.io/undefined/Assets/Images/bing_maps_credit.png

But the asset is actually at:
TerriaMap/wwwroot/build/TerriaJS/build/Cesium/build/Assets/Images/bing_maps_credit.png

This is only for maps that use `Cesium.BingMapsImageryProvider` e.g. DTV.
Does not happen for National Map that uses a catalog item for Bing I think.

The issue may be related to:

`buildModuleUrl` in Cesium

We have some references to this in our `configureWebpack.js` that may need to be modified since a change to Cesium.

**Comment by na9da** [comment]
One solution might be to set `window.CESIUM_BASE_URL` to `"build/TerriaJS/build/Cesium/build"`. 

When it is set, `buildModuleUrl` uses `CESIUM_BASE_URL` instead of trying to guess the url path:

https://github.com/TerriaJS/cesium/blob/160d6f108c8bf606fd608df04d375fec5c3f7cb7/Source/Core/buildModuleUrl.js#L46-L48

Otherwise it tries to guess the cesium base path from the script file path:

https://github.com/TerriaJS/cesium/blob/160d6f108c8bf606fd608df04d375fec5c3f7cb7/Source/Core/buildModuleUrl.js#L9-L19

which fails in our case because it assumes cesium script is named `Cesium.js` but our webpack renames the bundle to something else.

I wonder if it used to work in v7 :thinking:

**Comment by na9da** [comment]
In `v7` we used to set cesium baseUrl here:

https://github.com/TerriaJS/terriajs/blob/e52db191b49833b9feacedb8ae706eb3762773f8/lib/Models/Terria.js#L100-L108

**Comment by na9da** [comment]
PR - https://github.com/TerriaJS/terriajs/pull/6475

**Comment by AnaBelgun** [comment]
PR merged; issue fixed and fix available after TerriaJS 8.2.11 release

**Comment by AnaBelgun** [comment]
Fixed
![image](https://user-images.githubusercontent.com/18452161/183385129-91e7e0a8-5c89-48ab-b629-0b338ab01a0a.png)
