### ISSUE TITLE
Change to search return order

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#649]
Margie from Dept of Comms wants search return order to change from 
1. locations, 2. official place names, 3. catalogue items 

to
1. catalogue items, 2. locations, 3. official place names

I agree that seems to make sense.  @hilarycinis @philipgrimmett  what do you think based on usability testing?  (even if there are suggestions for more major changes to search, this one is one we should make quickly and get into the May release.

**Comment by hilarycinis** [comment]
I am happy to look at it, discoverability of search is the main problem, but I dont see any real problems with the order of reaults changing.

On 24 Apr 2015 6:18 pm, Bill Simpson-Young notifications@github.com wrote:

Margie from Dept of Comms wants search return order to change from
1.  locations, 2. official place names, 3. catalogue items to
   -   catalogue items, 2. locations, 3. official place names

I agree that seems to make sense. @hilarycinishttps://github.com/hilarycinis @philipgrimmetthttps://github.com/philipgrimmett what do you think based on usability testing? (even if there are suggestions for more major changes to search, this one is one we should make quickly and get into the May release.

—
Reply to this email directly or view it on GitHubhttps://github.com/NICTA/nationalmap/issues/649.

---

The information in this e-mail may be confidential and subject to legal professional privilege and/or copyright. National ICT Australia Limited accepts no liability for any damage caused by this email or its attachments.
