### ISSUE TITLE
Investigate replacing Leaflet viewer with Cesium in 2D scene mode

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6550]
Example Cesium 2D map - https://sandcastle.cesium.com/?src=Rotatable%202D%20Map.html

Cesium can be put in 2D mode with one line of code (from a quick test).

This would greatly simplify some core code and reduce maintenance costs. 

While Leaflet is very light-weight - I'm not sure it makes sense when Terria is so heavy.
Leaflet (default) vector performance is also very poor.

Switching to cesium 2D mode would give us a few things for free
- Vector support/performance that is equal to 3D mode (probably better even)
- support for 4326 imagery services
- ...

Possible complications
- How does splitter work in 2D mode

**Comment by nf-s** [comment]
Which clients don't support WebGL - would these be impacted?

**Comment by glughi** [comment]
Hi, I have recently replaced Leaflet with Cesium 2D for the main map.
But I kept Leaflet for the preview map and pedestrian mode. 
It's all good, even from a smartphone. 

However you have to instantiate two Cesium, 2D and 3D, because "sceneMode" can be changed on the fly at runtime but you have to change also projection and "mapProjection" can only be indicated in the CesiumWidget constructor.

**Comment by nf-s** [comment]
We have decided against this for the following reasons

- Leaflet is useful to keep for low-performance devices
- We would need to replace the Leaflet preview map (for the catalog and pedestrian mode) with Cesium - which would have performance overhead
- Leaflet is more reliable and well-maintained than Cesium's 2D mode
