### ISSUE TITLE
Graph support

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#662]
We have a requirement for showing graphs of data.

In most cases this is for showing a timeseries of a value for a specific point or area. Initially the graph might be shown in the Info popup when a feature on the globe is clicked.

The kind of data we need to show may be something like power generation at a power station over time, or weather related data. For weather related data, it would be useful to show multiple values with different units at once, this way we could show wind speed, temperature, dew point and solar intensity on the same graph perhaps. Another interesting graph would be wind speed with increasing altitude.

@axman6 has done some prototypes for AREMI using [C3.js](http://c3js.org/) which work pretty well. We are also pre-generating some SVG graphs and serving them up.

**Comment by metanomy** [comment]
It might make sense to define the behavior of the graph as an option to the data source definition. This is especially important for data sources like NetCDF. The Godiva2 client of ncWMS has a nice approach to graphing data (http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/GodivaTwoUserGuide), and you can see one Cesium-based approach here: http://forecast.ewatercycle.org/

**Comment by meh9** [comment]
@metanomy, thanks for the links!

The Cesium solution looks great, and is intuitive, we will be going for something like that.

The Godiva2 graphing support appears be a front-end to getting the Thredds server to generate the graph. This is reasonably similar to how we generate graphs in AREMI, both just generate a static PNG. We're trying to have a more interactive graph solution. 

However, it did show me how we can get timeseries data to graph out of a Thredds server, which is something that we will need to support for the graph solution! So, here it is for our own future reference, for a service that we are using (sorry for the long URL):

http://neii.bom.gov.au/services/solarclim/wms/data/monClim_dirNorExp1Day.nc?time=1993-01-16T00:00:00.000Z/1993-12-16T00:00:00.000Z&tiled=true&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=mean_exposure&query_layers=mean_exposure&srs=EPSG%3A3857&bbox=15028131.257091936%2C-2504688.542848654%2C16280475.528516259%2C-1252344.271424327&x=237&y=147&width=256&height=256&info_format=text/xml

We've also discussed this at length internally, unfortunately this issue doesn't reflect that.

**Comment by metanomy** [comment]
@meh9 Implicit are some assumptions:
- Time series coverage of the data would be defined by a layer option.
- Interaction would be limited to the data returned by the original query (e.g., no follow-on queries for additional data).
  - Interaction might imply different functions for different types of data, which means layer options to further define the interaction functions or expected data types

Now, if we were _really_ clever, we'd dynamically present interaction functions based on the data types returned by the GetCapabilities :)

I plan on funding another Open Source bounty on this capability in the next month or so, so let's think what a minimum MVP might look like around this general idea..

**Comment by RacingTadpole** [comment]
Some notes, updated to reflect our team's design meeting on 12 Nov 2015:
- Time-series charts can be viewed in a new "Chart Panel".
- Feature info descriptions may contain `<chart>` tags with appropriate attributes. These tags are replaced with interactive time-series charts in the feature info panel. The charts can viewed in more detail in the Chart Panel.
- The Chart Panel has a time range selector across the bottom when it makes sense.
- The Chart Panel shows one chart at a time, but with multiple series possible (stacking y-axes if necessary).
- The "Now Viewing" Panel contains a new high-level classification: Maps (containing the existing Now Viewing items) and Charts. Charts lists all the charts, each of which further show its constituent series.  They can be drag-and-dropped to move them from one chart to another, or even into a new chart (which would appear above the existing charts during the drag-and-drop).
- Time-series csv files can be drag-and-dropped anywhere to display them in the Chart Panel.
- When a new series is to be shown in the Chart Panel, if it makes sense to appear on the current chart, do so; otherwise, open it in a new chart.
- A way to plot a series for all features at once (eg. wind speed at every station), eg. using styling like http://www.nytimes.com/interactive/2009/11/06/business/economy/unemployment-lines.html. Not sure how this is specified yet.
- So that the data doesn't _have_ to be marked up to show a chart, the init .json file can define a template with `<chart>` tags in it.
- Support several data formats: csv, json (see c3/d3), thredds data format. Zipped data files are ok too. (ie. an equivalent to the existing geospatial DataSources).
- Export charts as csv, png and/or svg.
- When you click on a point on the graph corresponding to time _t_, show the map at that time.
- What is a good api for requesting subsets of time-series data (eg. some of our services currently use ?offset=24h)

Further thoughts on the `<chart>` tag:
- If a data source has many columns, the `<chart>` tag attributes can limit the chart to particular columns.
- The `<chart>` tag can specify that the chart should not appear by default in the feature info panel, but can be opened in the Chart Panel.
- The `<chart>` tag may need a `type` attribute so that it can display time series, scatter plots, histograms, density plots, atmospheric balloon measurements, etc. It could default to time-series (or more generally a line chart).
- Generalize `<chart>` so that terria-based apps can define their own tags.

**Comment by metanomy** [comment]
I think we need to also have @rsignell-usgs on this thread.

Since we are talking about a generalized charting/graphing capability, perhaps we should consider the following three general types of data sources (and their MVP use cases):
- NetCDF/THREDDS/Godiva2: replicating Godiva2-like query/charting/animation capability, but also the possibility of 3D array and/or 4D array animation (https://github.com/makinux/GridVIz).
- Sensor Observation Service: as a catalog type for charts
- Web Coverage Service: as a catalog type for subset geo/chart.

**Comment by metanomy** [comment]
There is also some interesting work being done as part of the SUNSHINE project. This PDF (http://www.sunshineproject.eu/jsmallfib_top/SUNSHINE/Final%20Deliverables/D4.9%20Sunshine%20Energy%20Web%20Portal.pdf)  describes some interesting UI work related to graphing. Unfortunately, although there are references to the SUNSHINE toolkit being released as Open Source, I haven't been able to find it anywhere.

**Comment by stevage** [comment]
Should this be merged into #1278?

**Comment by RacingTadpole** [comment]
Basic line charts are in master now.  More potential features listed under #1652.
