### ISSUE TITLE
Work around network site blocks affecting config loading (and other issues)

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6635]
Occasionally (have probably seen it 5 times now) we have users reporting that NatMap (or some other Terria map) can't load the config, and so does not initialise. Usually this is because they have departmental IT blocks on the network location we load the configs from.

We should consider working around this. One way to deal with it in the short term would be to change the `clientConfigUrl` to load using the proxy (which would mean adding the storage bucket to the allowList):

https://nationalmap.gov.au/proxy/https://terria-catalogs-public.storage.googleapis.com/nationalmap/config/prod.json

Similarly, if there are other critical resources that need to be loaded these should likely also be loaded via the proxy.

The experience for the users who have this issue looks like this:
![thumbnail_image001](https://user-images.githubusercontent.com/5283003/204184023-5931e32b-4f62-4a20-b528-4573561d617f.png)

And when they access the config directly they get a variation of this:
![thumbnail_image007](https://user-images.githubusercontent.com/5283003/204184067-50f4de2e-57aa-483b-b38a-2ae6eb017e2d.png)

**Comment by tephenavies** [comment]
Use proxy/_5m (check max-age headers and other caching headers are appropriate).

Check that proxy without leading slash works with /story/ urls (map must have base url)

**Comment by mwu2018** [comment]
The issue is not only applied to config url but also to all catalogs that reference gcs bucket. E.g. the nationalmap catalog references https://terria-catalogs-public.storage.googleapis.com/nationalmap/dev.json that references https://terria-catalogs-public.storage.googleapis.com/nationalmap/catalog/land-cover-land-use/dev.json etc.
It means all requests (configs, catalogs, icons, images etc) to `terria-catalogs-public.storage.googleapis.com` should be proxied. Do we really want to support this?

**Comment by nf-s** [comment]
We can't add custom hostname to our bucket - as we would need to rename the bucket.

I don't think we should support this - IMO blocking `storage.googleapis.com` (or the AWS S3 equivalent) is ridiculous and breaks a lot of sites.

Let's leave this for the moment, we can revisit if this becomes a major problem
