### ISSUE TITLE
Add timezone override trait

### ISSUE THREAD

**Issue by sixlighthouses** [TerriaJS/terriajs#6817]
add trait to allow users to specify if datetimes are in UTC -- when the date attributes have no timezone

Related ticket 
https://app.zenhub.com/workspaces/terriajs-all-57511fce8d1d8954514d40d1/issues/gh/terriajs/product/285

**Comment by sixlighthouses** [comment]
draft PR  https://github.com/TerriaJS/terriajs/pull/6822

<img width="1274" alt="image" src="https://github.com/TerriaJS/terriajs/assets/1597830/4e0b91c4-e738-407a-b322-04a91ffc1b19">

**Comment by staffordsmith83** [comment]
UPDATE 19 July 2023: Staf and crispy to finish review.

**Comment by nf-s** [comment]
I don't think we should be modifying dates coming from web services. If services don't specify timezone in dates - then we assume UTC.

If users want to see dates as UTC instead of local timezone (which is the default web browser behaviour), then they can use the following trait. 

```json
{
    "dateFormat": "UTC:dd/mm/yyyy, HH:MM:ss Z"
{
```

If needed, we can revisit this if we come across "local" datasources than need a timezone adjustment (for example CSVs)

**Comment by nf-s** [comment]
I'm going to close this - as the problem this was trying to solve ended up being a opendatacube-ows problem

Context - https://github.com/TerriaJS/terriajs/discussions/6968
