### ISSUE TITLE
Align gltf model to 3d map

### ISSUE THREAD

**Issue by DerKorb** [TerriaJS/terriajs#6825]
I would like to indicate the extends of a planed powerline by extruding a rect along a polyline of long/lat vectors. 
What would be the best way to have that generated model align with the 3d base map?
My plan was to create a gltf with the model, but I am not sure how to get the correct height for each of the points.
It seems like the model is always rendered above the basemap, so I need to get the height correct all along the path and cannot just overextend the model below ground. 
I tried the heightReference modes but it looked like they do not change anything at all.

**Comment by na9da** [comment]
Hi @DerKorb,

Would something like this [Cesium sandcastle example](https://sandcastle.cesium.com/?src=Wall.html) work for the look you are trying to achieve? It is using a [WallGraphics](https://cesium.com/learn/cesiumjs/ref-doc/WallGraphics.html) entity for showing an extruded line. If so, it might be possible to define it as a CZML item and show it in Terria (happy to provide examples)

Otherwise, here is an [example configuration](https://gist.githubusercontent.com/na9da/fb1bf736532ad280314c9bc438653fe0/raw/9b26b185418b58a6d03185a15fe9fac5719944d4/ducky.json) for height referencing a glTF model in Terria and this is [how it looks](http://ci.terria.io/main/#https://gist.githubusercontent.com/na9da/fb1bf736532ad280314c9bc438653fe0/raw/9b26b185418b58a6d03185a15fe9fac5719944d4/ducky.json&share=s-3zCa8fZmofKh19Cz0k3RVjuRwC4).

**Comment by DerKorb** [comment]
Hey, thx for your reply. I toyed around with the example but unfortunately this is not what I need. The lines here are positioned relative to the WGS84 elipsoid. I am however using 3d terrain and need to position all of my vertices accordingly. My current way to do this would be to generate a gltf where for each point of my polyline I have to lookup the elevation at that coordinate and then apply earth curvature to the whole mesh so it fits snuggly to the 3d basemap but that is quite a complicated process. I was hoping there might be some way where I could just say this vertex is at long/lat so and so and 10m above ground. I think czml polylines allow for that, but only if height above ground is 0 and I cannot do anything except lines.

**Comment by DerKorb** [comment]
I took another look at the polygon sandcastle example and that would basically do it for me, if it was possible to automatically clamp the heights to the 3d terrain.

**Comment by DerKorb** [comment]
Found these links discussing the same idea:
https://github.com/CesiumGS/cesium/issues/4743
https://community.cesium.com/t/polygon-in-3d-mode-vs-terrain/2122/9

**Comment by na9da** [comment]
Polygons have an [extrudedHeightReference](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html?classFilter=polygon#extrudedHeightReference) property which can be seen in this [sandcastle example](https://sandcastle.cesium.com/?src=Geometry%20Height%20Reference.html). Will that work?

**Comment by DerKorb** [comment]
I solved it using polylineVolume and a nodejs script that gets elevation data for each coordinate.
