### ISSUE TITLE
Problem in rendering point cloud 3D model and WMS layer imagery

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#6940]
If a point cloud 3d model and wms layer are added in the same location, these two items will interfere each other. The results are
- The map might become less responsive.
- The point cloud model appears to be less dense.
- Data loading become very slow or pause.
- Some black stripes might appear on the screen when zooming in/out.

See example [here](https://eap.digitaltwin.terria.io/#share=s-8RV63GsDNS56JgDZ4d0S5ycoD25). You need to sign in first.

**Comment by nf-s** [comment]
This is due to how cesium loads and renders tiles - it will wait until all data for a given tile has been loaded before rendering.

There might be ways of tweaking it, but I am not sure.

For me, the issue really lies with performance of the underlying web services - if the WMS layer is slow to load, then everything else will be slow. I think it might be better to try to optimise these web services before looking into how Cesium handles network requests and rendering data

**Comment by nf-s** [comment]
Closing because issue with data
