### ISSUE TITLE
Latest TerriaJS version broke `/story/` prefix path

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#7081]
Test link

- http://ci.terria.io/main/story/DEACoastlines#configUrl=https://terria-catalogs-public.storage.googleapis.com/de-australia/map-config/prod.json

Notice in network tab that a few cesium resources will incorrectly use `http://ci.terria.io/main/story/build` as the baseHref

<img width="770" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/cd79a399-268d-4307-bb0e-79edc6d07b96">

This is most likely because of the latest cesium upgrade

**Comment by na9da** [comment]
There are some changes around how the approximateTerrainHeights.json and possibly other assets are fetched in the upgraded version of Cesium - following the splitting into sub modules. This might require changes in how we set the [cesiumBaseUrl](https://github.com/TerriaJS/terriajs/blob/bc01aeced5cd036f4b131dfd82a33789158e0614/lib/Models/Terria.ts#L709) when routing stories.

Previous code for [fetching approximateTerrainHeight.json](https://github.com/TerriaJS/cesium/blob/160d6f108c8bf606fd608df04d375fec5c3f7cb7/Source/Core/ApproximateTerrainHeights.js#L48).

Current code https://github.com/TerriaJS/cesium/blob/2a676e54bc82c667b8cc1c00785b14daaa85f4b2/packages/engine/Source/Core/ApproximateTerrainHeights.js#L47

**Comment by nf-s** [comment]
A temporary fix is to change the `baseUrl` option in TerriaMap `index.js` to be absolute (`"/build/TerriaJS"`)

https://github.com/TerriaJS/TerriaMap/blob/49d9f94e54d60798eec9ca95912f8ca91685a1ad/index.js#L3-L5

**Comment by tephenavies** [comment]
That's odd. This is meant to be dealt with using the `<base>` tag. CI correctly has:

```html
<base href="/main/">
```

so then requests made to `build/TerriaJS/` will be translated to `/main/build/TerriaJS`.

I think Cesium has added some relative URL handling that ignores that base url.

**Comment by nf-s** [comment]
Could this call here override it? 

https://github.com/TerriaJS/terriajs/blob/d46d093f823c466d5727c19f04e6639f9522483d/lib/Models/Terria.ts#L709

Which means that `getCesiumBaseUrl` will always return `baseResource` (set by `setBaseUrl`)

https://github.com/TerriaJS/cesium/blob/2a676e54bc82c667b8cc1c00785b14daaa85f4b2/packages/engine/Source/Core/buildModuleUrl.js#L37-L39

**Comment by tephenavies** [comment]
It seems:
* [setBaseUrl](https://github.com/CesiumGS/cesium/blob/59e1f74c85167b8468ac93c8d5cf3241f8f506e2/packages/engine/Source/Core/buildModuleUrl.js#L140) calls
* [getDerivedResource](https://github.com/CesiumGS/cesium/blob/59e1f74c85167b8468ac93c8d5cf3241f8f506e2/packages/engine/Source/Core/Resource.js#L668) which calls
* [parseUrl](https://github.com/CesiumGS/cesium/blob/59e1f74c85167b8468ac93c8d5cf3241f8f506e2/packages/engine/Source/Core/Resource.js#L422) with baseUrl being set to [`document.location.href.split("?")[0]`](https://github.com/CesiumGS/cesium/blob/59e1f74c85167b8468ac93c8d5cf3241f8f506e2/packages/engine/Source/Core/Resource.js#L2263).

Hence a relative URL is resolved relative to the `location`, rather than `baseURI`.

I'd prefer that Cesium used `document.baseURI` to define the URL in `DEFAULT`, but we can just send the correct absolute path instead. We can compute something like the following and use that for setBaseUrl:

```js
typeof document !== "undefined" ? new URL(this.cesiumBaseUrl, document.baseURI).href : this.cesiumBaseUrl
```
