### ISSUE TITLE
"esri-mapServer-group" groups does not honour "rectangle" set in "itemProperties"

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#724]
When specifying a group in an init file with "esri-mapServer-group" and using an "itemProperties" to specify a "rectangle" for all the child items, the rectangle does not appear to be applied to the child items. Trying to zoom to the layer does work, or occasionally causes Cesium to become unresponsive without logging an error in the console.

```
        {
          "name": "Rectangle",
          "type": "esri-mapServer-group",
          "url": "http://www.ga.gov.au/gisimg/rest/services/energy/Solar_Energy_DNI_Mean/MapServer",
          "itemProperties": {
            "info": [
              {
                "name": "info",
                "content": "info tag is inherited to the items"
              }
            ],
            "rectangle": [
              "100",
              "-5",
              "130",
              "-35"
            ]
          }
        }
```

**Comment by kring** [comment]
I initially thought the problem here was that your north and south latitudes are reversed, but that seems to be fine in both 2D and 3D.

The actual problem is that `itemProperties` were being assigned directly to the instance, without going through the normal JSON loading mechanism that would turn the degrees to radians and stick them in a `Rectangle` object instead of an array.
