### ISSUE TITLE
Tile Error: Got a 200 (OK) response from URL: domain.com/... but it could not be loaded as an image

### ISSUE THREAD

**Issue by irbian** [TerriaJS/terriajs#7384]
It happens on Safari 17.x on 2d

Reproducible in map.terria.io (see image for details)

![Image](https://github.com/user-attachments/assets/bafa7945-f2e9-4228-8f06-bbd7c020e80a)

First discovered on #4366

**Comment by zoran995** [comment]
Hi @irbian, thanks for reporting; I can't reproduce this on Safari 18.1 in 2D view, but it happens when changing from 2D to 3D viewer. Can you check if my observation is correct or if there are any other details on how to replicate this in only 2D

Here is the share URL I used for testing https://map.terria.io/#share=s-dlDBYJS3O00Dk72ntDRtKSbkcxW
- open the map in 2d
- ensure the layer is visible
- change to 3D view

For future reference, after a quick look into code, it seems like an error was thrown from the delayed update of the leaflet map while we have already moved to a 3D view

**Comment by irbian** [comment]
Looks like something was fixed in the interim, because we no longer can reproduce it either in Safari 17.6

That's for the better!
