### ISSUE TITLE
Add data custodian Attribution text to the map view footer

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#790]
We have many data custodians who only agree to give us data if we show attribution to their organisation name on the map.

We could add an `attributionText` key to the init file for a layer item, and when turned on add that text to the attribution text shown at the bottom of the map.

**Comment by hilarycinis** [comment]
That sounds reasonable enough, I'm having a look at several custodians, so as long as the attribution isn't going to contain too much.... can you help me work out in this example, which is the attribution - is it simply "AusHydro"?

![screen shot 2015-07-10 at 2 13 53 pm](https://cloud.githubusercontent.com/assets/6046521/8612083/1a63fe80-270e-11e5-9d67-d8f5e0cbc815.png)

**Comment by hilarycinis** [comment]
also, I'm not sure if you can either add a dark gradient under the footer text or make it another colour as its almost impossible to read. 

![screen shot 2015-07-10 at 2 18 23 pm](https://cloud.githubusercontent.com/assets/6046521/8612103/8f046248-270e-11e5-9820-bcb361902d51.png)

**Comment by meh9** [comment]
For AusHydro the data custodian is Geoscience Australia, so that's probably what we'd want to say there.

Basically, in most cases we'd want exactly the same as the Data Custodian text on the Info page, but in some cases like AREMI -> Boundaries -> "Cadastral Boundaries - Tasmania" we might want to have a different shorter text than the current "Land Information System Tasmania - Tasmanian Government", which is why I suggested a separate attribute in the config.

**Comment by chloeleichen** [comment]
@hilarycinis what about something like this: 

![footer](https://cloud.githubusercontent.com/assets/7508939/10152664/fc400a56-6697-11e5-9255-3243aa0b5bb1.png)

**Comment by kring** [comment]
@chloeleichen the style of the attribution text is a separate issue from @meh9's original feature request.  Mats wants to be able to specify attribution text in the init file description of a catalog item (see the `datasources` directory in NationalMap or AREMI).

To do that, you'll need to add the `attributionText` field to `CatalogItem.js`.  Then, to add the attribution to the map when the catalog item is enabled (see the `_enable` method in `CatalogItem`, take a look at how `developerAttribution` is handled in `TerriaViewer.js`.  You won't want do actually add this attribution there, but it shows you how it is done in Cesium and Leaflet.  It might be nice to add a new method to `GlobeOrMap`, `NoViewer`, `Cesium` and `Leaflet` to add an attribution.

@hilarycinis is out this week so let's leave the styling of the credits for another time.  IMO we don't want to make them _too_ obvious because then they'll distract from the map content.

**Comment by kring** [comment]
Fixed by #944.
