### ISSUE TITLE
Potentially redundant static resource path

### ISSUE THREAD

**Issue by keattang** [TerriaJS/terriajs#828]
Just wondering what the purpose of this line is? `imageryProvider : new SingleTileImageryProvider({ url: 'images/nicta.png' })`. It's causing me a 404 error because my static files can't be stored at the path given. This line `viewer.scene.imageryLayers.removeAll();` also seems to nullify its purpose. 

```
TerriaViewer.prototype._createCesiumViewer = function(container) {

    var that = this;

    var terrainProvider = that._terrainProvider;

    var options = {
        dataSources:  this.terria.dataSources,
        clock:  this.terria.clock,
        terrainProvider : terrainProvider,
        imageryProvider : new SingleTileImageryProvider({ url: 'images/nicta.png' }),
        scene3DOnly: true
    };

    // Workaround for Firefox bug with WebGL and printing:
    // https://bugzilla.mozilla.org/show_bug.cgi?id=976173
    if (FeatureDetection.isFirefox()) {
        options.contextOptions = {webgl : {preserveDrawingBuffer : true}};
    }

     //create CesiumViewer
    var viewer = new CesiumWidget(container, options);

    viewer.scene.imageryLayers.removeAll();
```

**Comment by kring** [comment]
It prevents the default `BingMapsImageryProvider` from being constructed.  That's a good thing because creating a `BingMapsImageryProvider` counts as a "use" of the Bing API, which is not free beyond a certain usage level.

Rather than using images/nicta.png, it could be a trivial image, base 64 encoded into a data URI, so no  network requests need to be made at all.

**Comment by keattang** [comment]
cool thanks ill make a pull request
