### ISSUE TITLE
CZML layers should not begin playing until loaded

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#889]
We have some moderately sized CZML layers which take several seconds to load. When turned on, the time slider immediately starts playing before the data is visible - this shouldn't begin until the data is rendered.

**Comment by rsignell-usgs** [comment]
I think the default behavior for time-dependent layers should be to load and show only the last (latest) layer.   Then the user could choose to select another time step or animate as desired. 

I've done an informal poll around the office and folks uniformly agree.   It might be interesting to poll other users for their thoughts on this.

**Comment by meh9** [comment]
@rsignell-usgs, do you mean that instead of automatically starting to animate from the oldest time stepping through to the newest time, it should once the data has loaded show the data for the most recent time instant and in a stopped animation state?

That does sound intuitive to me, and I think I do support that.

While what I believe you are saying deals with all timeseries dataformats that Terria can show, this bug deals specifically with problems using the CZML vector layer data format when it includes timeseries data, which has the problem that the timeseries control will start to play before the polygon data has been processed and displayed at all.

However, changing things to work the way you describe does get around this problem of course!

**Comment by rsignell-usgs** [comment]
@meh9, exactly: for any layer that has a time component, I think starting in a stopped animation state on the last frame would be desirable.   Thanks!

**Comment by axman6** [comment]
Starting at the last frame makes sense for historical data, but not prediction data, which is what our data is showing. We're discussing being able to set what the starting time is.

**Comment by rsignell-usgs** [comment]
How about starting with the time step closest to "now".  
That would work for both historical and prediction data, wouldn't it?

**Comment by Meeena** [comment]
I agree we should not auto animate the data. The user should explicitly 'play' the data. I also think it's a good idea to default to 'Now', as the starting point for the animation. However I think we should provide an option to have the start frame as the default.

**Comment by meh9** [comment]
With the release of Terria 1.0.43 it is now possible to make timeseries data not play by default:

https://github.com/NICTA/aremi-natmap/commit/84152e5b2357bfdb3ad4c6f2ee2e60eaee769823

Specifying which interval to start on requires more work.

**Comment by metanomy** [comment]
@meh9 Would it be possible to use a per-catalog item flag for play/not-play? This would allow us to autoplay for traditional historical data sets, but turn it off for data sets that are predictive in nature...
