### ISSUE TITLE
Support timelines without specific years/months/days

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#896]
Some layers that we have to show (currently WMS and CZML) have timeseries data that doesn't really work with the current time control.

In one case we have a dataset that has been averaged down to an arbitrary 24 hours - i.e. there isn't really a year/month/day attached to the 24 hours. However, in order to show it in Terria we have add a date to those 24 hours, and that date is part of what is displayed on the time slider. This gives the incorrect notion that the 24 hours are on some specific date, when we need the time slider to display just hours. The way to solve this one would probably be to specify that no date should display on the time slider.

In another case, we have the new Bureau of Meteorology Solar Climatology WMS services, e.g.:

http://neii.bom.gov.au/services/solarclim/wms/data/monClim_gloHorExp1Hou.nc?service=WMS&request=GetCapabilities

This has 12 months of 24 average hours per month, i.e. many years of 24 hour days for January have all been averaged down to 24 hours representing an average January day, and so on. 

In order to get a WMS time dimension that works, they have put the arbitrary year of 1993 on all timestamps, and the 24 hours span from the 15th to the 16th of the month. There is no data or timestamps outside of the 15/16 days of each month:

```
1993-01-15T16:00:00.000Z, 1993-01-15T17:00:00.000Z, [...], 1993-01-16T15:00:00.000Z,
1993-02-15T16:00:00.000Z, 1993-02-15T17:00:00.000Z, [...], 1993-02-16T15:00:00.000Z,
[...]
```

In this case, we need to specify that the time slider should not display the year (so this probably generalises together with not showing a date at all with the other case given above in this issue), and it should somehow put the 24 hours for each month next to each other on the time slider instead of what it does currently, which is leaving 30 days of no data between the single 24 hours of data for each month.

Showing data with specific timestamps, like specific individual datapoint observations, is all well and good and really useful. But the real utility of using Big Data comes from analysing that data, and aggregating it down into useful abstractions like averages etc. It is when displaying these aggregated processed versions that we need to be able to display the times that these aggregations are concerned with in a non-time-instant way.

**Comment by meh9** [comment]
If the time slider could have a dateformat string specified in the init file would solve the part of not showing the date or the year part of this issue.

**Comment by stevage** [comment]
Yeah I think what's needed here is:
1. Ability to specify how the time/date should be displayed
2. Ability to skip over empty time periods.

**Comment by meh9** [comment]
I agree, and in so much fewer words!

**Comment by meh9** [comment]
We have a need for the Skip Empty Time Periods (part of this issue)/Snap To Time With Data (#946) in order to show the two Bureau of Meteorology "Monthly-hourly climatology of hourly exposure" datasets which can then be integrated immediately. The Bureau just brought this up in our progress call with them.

**Comment by AlexGilleran** [comment]
So the good news is that doing both this and the snapping on click is actually pretty simple.

The bad news is that it can be pretty nasty for usability if there's a big gap in the timeline, because there's no way for the user to see that there's no data for where they're clicking, it appears as if the timeline is registering the click in the wrong place. It might not be a big problem for TMYs seeing how the data is pretty even, but if we end up with a dataset where, say, there's data for a year then no data for the next year that's gonna be an issue.

**Comment by meh9** [comment]
Any chance of having some form of indicator on the timeline of where there is data on the timeline?

**Comment by AlexGilleran** [comment]
Sure - easiest thing to do would be to use the ability to draw coloured bars under the timeline that we investigated for multiple-layers-on-one-timeline before:

![image](https://cloud.githubusercontent.com/assets/900555/13039395/755099ac-d3f2-11e5-80b7-3054ab8b9cba.png)

**Comment by stevage** [comment]
I have no idea how this is implemented, but perhaps a combination of a bar showing "there is data here", and somehow greying/fading out the background where there isn't data? So, simultaneously communicating:
- there is stuff _here_
- _this_ is a place you can't click

**Comment by AlexGilleran** [comment]
Yeah right now I've got the background of where you can't click as black and where you can click as thee current grey gradienty sort of colour, which works ok. Will post a screenshot when I manage to get it building properly again.

The other idea that @philipgrimmett came up with was having a vertically-centred red line where you can't click.

**Comment by stevage** [comment]
Cool, look forward to the screenshot!

**Comment by AlexGilleran** [comment]
![image](https://cloud.githubusercontent.com/assets/900555/13208992/d8b6da30-d972-11e5-849f-966bbe61cabe.png)

So:
- Regions with no data are black
- Clicks/drags on those regions will either go to the beginning or end of that region depending on which is closer
- When time is moving, those regions will be skipped
- The formats for the time on the timeline itself and the current time are independently specifiable

Problems:
- Is the black clear enough?
- If the regions with data are very small compared to the total time (12 days in 365 in this case) then equal amounts of time appear as different widths due to pixel rounding.

(@cam-grant @cam-grant @cam-grant)

**Comment by stevage** [comment]
Suggestions:
- make the the grey line indicating where the data is (I guess it's just the gap between the "no data black") brighter, maybe blue?
- make it a minimum width (eg 4 pixels), which may also solve the pixel rounding thing.

Does the visual indicator of the current time move smoothly, or jump? If it moves smoothly, perhaps there should be another indicator of what is currently being shown (ie, another indicator that does jump)?

**Comment by stevage** [comment]
Btw for some inspiration, see how [Strava shows something fairly similar](https://www.strava.com/activities/499257566/analysis) - how various segments correspond to intervals along a timeline.

**Comment by axman6** [comment]
Mats says you need to be logged in to see the thing you're talking about, can you add a screenshot?

**Comment by AlexGilleran** [comment]
Ah right, I thought I must just be too stupid to use Strava. Props for the brutal ride @stevage

**Comment by meh9** [comment]
From @stevage's Strava link above:

<img width="984" alt="screen shot 2016-02-22 at 15 01 28" src="https://cloud.githubusercontent.com/assets/5283003/13209188/38db7b6c-d975-11e5-8adc-069929ee2248.png">

**Comment by stevage** [comment]
Oh, sorry! I didn't know that. The bit I'm referring to is the "segments" bit between the two graphs.

**Comment by AlexGilleran** [comment]
![image](https://cloud.githubusercontent.com/assets/900555/13210101/bf0ec78e-d97f-11e5-9da7-1bde588bbea2.png)

This is what it looks like with a single red line through it

**Comment by AlexGilleran** [comment]
![image](https://cloud.githubusercontent.com/assets/900555/13210143/46620b7e-d980-11e5-8eaf-8db6d0569634.png)

This is what it looks like with blue in the data-filled intervals and black in the gaps as per @stevage's suggestion (or is it white and gold?!?!)

**Comment by stevage** [comment]
Yeah IMHO the second one makes much more sense - it draws your eye to the "good place". Though the blue should be lighter (like the colour of the double-arrow loop icon), and thicker.

**Comment by AlexGilleran** [comment]
I've done a PR with the most basic timeline (the first one I showed) so we can start to look at the code.

The problem with inserting the blue is that shouldn't that mean the timeline is usually blue? Otherwise we've got two different representations of "data is here".

Making them a minimum thickness makes sense visually but I'm a bit worried about breaking the continuum between the actual time and the visual representation of it. Should the expanded data intervals be purely visual (fake), so that while the visual interval is bigger, the clickable interval remains its actual, to-scale size and hence clicks towards its edges actually count as clicks on the data-less interval next to it, and move the cursor inwards to the actual start of the data? This means that it constantly seems to the user as if they're not able to seek to the very beginning of the interval with data.

Or should the entire we be expanding the intervals that we have data for to make it easier to scrub within them, but covering parts of the times with no data (this is likely to be super hard).

The other problem with both of these is that it'll make the intervals with data look bigger than they actually are, leaving the user to wonder why they can only view 24 hours of data when it looks like there should be enough for a few days.

**Comment by stevage** [comment]
Good points. I guess I was thinking of it as a clickable box representing the data, with an overhanging border (eg, 2px extra, so a 1-pixel data point takes 5px on screen). If the box itself is quite light (translucent?) but the border is dark, it also solves the problem of "the timeline is usually blue".

Will have a play with code.
