### ISSUE TITLE
when.js is really old

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#905]
I'm not sure the background here, but we seem to have `when.js` as a hard-copy inside our Cesium fork (as opposed to being installed through npm.js). Perhaps a result it's extremely old: version 1.7.1 compared to 3.7.3 on NPM. The latest version has a richer, more idiomatic interface.

Are we able to update, and use the NPM version?

**Comment by kring** [comment]
Right, we're using Cesium's version of when.js.  Because we frequently use promises returned by Cesium in TerriaJS code, I'm not sure what would happen if we mixed promise libraries.  Even if it works, it seems a bit inefficient.

I guess the real question is, why does Cesium use such an old version?  Well, @shunter tried to upgrade Cesium's version awhile back (probably over 18 months ago now) and it was difficult because of breaking changes in when.js.  It wasn't just API changes; we could deal with those.  If I remember correctly, the biggest problem was that when.js changed how `when` works when given something that is not a promise.  For example.

``` javascript
var valueOrPromise = someFunctionThatMightReturnAValueOrMightReturnAPromise(...);
when(valueOrPromise, function(value) {
    console.log('promise resolved');
});
console.log('when returned');
```

Cesium's current (old) version of when.js would print:

```
promise resolved
when returned
```

But the newest versions of when.js would print:

```
when returned
promise resolved
```

Basically, in the old versions of when.js, the callback given to `when` would be called immediately if given something that's not a promise.  But in the new versions, that callback would be deferred until later.  As in after the current JavaScript context returns control completely back to the browser, and then a new one would start to invoke the callback.

Arguably, the new behavior is better because it's more consistent.  But it makes a few things in Cesium less efficient (e.g. little things like imagery loading).  So, with the upgrade being difficult and having a negative effect on Cesium, we moved on to other more pressing matters.

So if we want to use the newer version in TerriaJS, we can see what the cost is of using two different versions (does it work at all?  how much bigger does it make a TerriaJS app?).  Or we can try again to upgrade Cesium.  If when.js has added a function in the past 18 or so months that lets you determine if a given thing is a promise or not, it should be possible to upgrade Cesium's version without the negative impact we saw before, with some amount of effort.

**Comment by stevage** [comment]
Hmm! Thanks for the background. In theory, When is supposed to be very compatible with other promise libraries, so potentially When in TerriaJS could be "compatible with" the old When in Cesium.

Or alternatively, if that particular behaviour is the only breaking difference, we could just have a shim in Cesium like:

```
function oldWhen(maybePromise, f) {
  if (maybePromise instanceof Promise) {
    return when(maybePromise, f);
  } else {
    return f();
  }
}
```

And then search-replace throughout Cesium?

**Comment by kring** [comment]
> if that particular behaviour is the only breaking difference, we could just have a shim in Cesium

Yes, but that's only possible if `Promise` is a publicly-visible type name, or if there's another way to determine if something is a promise, which there wasn't last I looked.  That's what I was referring to with "if when.js has added a function in the past 18 or so months that lets you determine if a given thing is a promise or not ..."

**Comment by shunter** [comment]
To add to what @kring said, the behavior of always resolving promises asynchronously is unfortunately mandated by the promises specification.  More background here: http://thanpol.as/javascript/promises-a-performance-hits-you-should-be-aware-of/  The version of when.js currently in use pre-dates that addition to the spec.

Rather than trying to check instanceof Promise, it might be sufficient to simply check for a `.then` method.  You could consult the implementation of `when.resolve` to see how it does this sort of check internally.

Also, we're not necessarily tied to the when.js implementation.  It was the best at the time (mid-2012), but the newer Bluebird library has a focus on performance that may provide benefits for our use case, where latency of promise resolution is a concern.

**Comment by stevage** [comment]
> it might be sufficient to simply check for a .then method.

Yeah, the when.js doc usually refers to "thenables" not promises explicitly. Their definition of thenable is "any object that provides a .then() method, even promises that aren't fully Promises/A+ compliant, such as jQuery's Deferred."

So the shim function would become:

```
function oldWhen(maybePromise, f) {
  if (typeof maybePromise.then === 'function') {
    return when(maybePromise, f);
  } else {
    return f(maybePromise);
  }
}
```

**Comment by kring** [comment]
:+1:

**Comment by kring** [comment]
If we really want to fix this, we should start by moving Cesium to a new promise library.  Closing this issue.
