### ISSUE TITLE
Better init file support for geoJSON datasets

### ISSUE THREAD

**Issue by SpacemanPaul** [TerriaJS/terriajs#910]
There's some really nice handling  in the init file for colouring features from a CSV layer - i.e. the "tableStyles" property lets you nominate a column from the CSV file as the `dataProperty` to determine the colour of regions, and other subproperties like `minDisplayValue`, `maxDisplayValue`, and `colorMap` provide finer control over how that colouring is applied.  Also, in the "Now Viewing" tab, other columns from the CSV file can be chosen to drive colouring, and a key/legend for the current colouring is displayed.

It would be nice if we could the same sort of thing with geoJSON layers - except instead of a column in the CSV file, it would be a property in the GeoJSON.  

The immediate use-case is nominating a particular property name that can be used by Terria to autocolour the features in the GeoJSON, and then to control the colour scale (e.g. by providing max and min display values and a colour map).

It would seem logical to make the API for this (i.e. the init file syntax) as close as possible to the existing API for CSV layers, and indeed most of what is currently being done for columns in a CSV file makes just as much sense in the context of properties of a geoJSON file.

Note that some of this can be done now using [Simplestyle](https://www.mapbox.com/guides/an-open-platform/#simplestyle).  The limitations with this approach are that you need to have control over the geoJSON file, and Terria does not render a key/legend under "Now Viewing".

**Comment by stevage** [comment]
Ok, to try to break this down a little bit, there's a few different needs here:

`1`. The ability to convert a property on a feature in a GeoJSON file into a visual representation. That is, given a point like:

```
    {
      "type": "Feature",
      "properties": {
        "population": 1000,
        "literacy": 0.95
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          143.7890625,
          -34.59704151614416
        ]
      }
```

You want to use either the 'population' or 'literacy' property to make the point change colour. (And, one could reasonably expect, why not change size etc as well.)

`2`. There is no legend shown for GeoJSON files. Mostly because showing a legend doesn't make sense when the colours are hardcoded into the GeoJSON file - we have no idea what they represent.

`3`. There's separately the question of using a GeoJSON file combined with a CSV file to allow user-defined region mapping. That is, the geometry would come from the GeoJSON file, the data from the CSV, and the styling from the init file. This feels like the better solution to me, I think.

**Comment by SpacemanPaul** [comment]
1. Yes, absolutely.  That's my most pressing request.
2. Currently that is correct.  However if 1. is implemented, a legend would become necessary.
3. That would be a clean approach, but it wouldn't handle the use case where you had geoJSON being returned by a 3rd party API with all relevant data already embedded as properties.  In that situation, it would be preferable to be able to simply style the geoJSON and render it directly.  (In the solution Steve suggests above, you would need to hit the API to generate a CSV file with the data, then hit it again to get the geometry data to combine with the CSV file.)

**Comment by kring** [comment]
Steve added support for specifying simplestyles in init files awhile ago.  Anything beyond that falls under "style vector data", i.e. #574.  Closing.
