### ISSUE TITLE
Pre-canned colour ramps in TableStyle

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#936]
For ParlMap (and generally) anyway, we need some pre-defined color ramps, for instance:

```
tableStyle: {
  colorRamp: "red-green"
}
```

(Hmm, on that front, it occurs to me that "red-green" could just be a shorthand for                 

```
"colorMap": [
                  {
                    "color": "red",
                    "offset": 0
                  },
                  {
                    "color": "green",
                    "offset": 1
                  }
]
```

**Comment by stevage** [comment]
Two examples of color ramp choices.

Tableau:

<img width="398" alt="screenshot 2015-10-09 10 54 40" src="https://cloud.githubusercontent.com/assets/678344/10382890/8b3dc1ec-6e74-11e5-81a6-03a661abe508.png">

CartoDB:

<img width="131" alt="screenshot 2015-10-09 10 57 12" src="https://cloud.githubusercontent.com/assets/678344/10382895/90ccad4e-6e74-11e5-88a5-f82b16f1a9d9.png">

**Comment by chloeleichen** [comment]
Added some predefined color ramps, what's the best way to test this?

**Comment by kring** [comment]
@stevage was this fixed by #1062?  Only partially?

**Comment by stevage** [comment]
Ok, so to update on this, I'm implementing support for ColorBrewer styles.  Currently the way this works is you have three ways you can specify a color map:
1. The old way: `colorMap: [ ... ]`
2. Shorthand `colorMapString` as above: `colorMapString: "red-white-green"`, `colorMapString: hsl(0,50%,40%)-#fff`
3. [Colorbrewer](http://colorbrewer2.org/) style: `colorMapString: "colorbrewer: 3-class Purples"` or `colorMapString: "colorBrewer: RdYlBu"`

Issues/questions:
1. Is "colorbrewer: " a reasonable prefix? Do we need a prefix? Are we likely to want to support other palettes in the future? It's kind of tempting to allow `colorMapString: "3-class BrBG"`
2. Currently there is no relationship between the "`3-class`" and the actual number of bins. Probably the most intuitive thing is:
- if you set `bins: 5` and `colorMapString: "BrBG"`, you actually get the 5-class version.
- if you don't set `bins` but set `colorMapString: "5-class BrBG"`, then it sets `bins: 5`
- and if you set X `bins` and `Y-class`, then you get `bins` samples from the Y-class gradient.

**Comment by kring** [comment]
I may not completely understand all of the issues here, so take my suggestions with a grain of salt... but here we go.

>  Is "colorbrewer: " a reasonable prefix? Do we need a prefix? Are we likely to want to support other palettes in the future? It's kind of tempting to allow colorMapString: "3-class BrBG"

It seems unlikely to me that we're going to add a bunch of other palettes, so I'm fine with skipping the prefix.  If we ever do add another palette, we can prefix that one (and potentially deprecate unprefixed palette names at the same time).  But will this be potentially ambiguous with color (not palette)  names?  I guess not, since colorbrewer doesn't have any palettes that overlap with color names, but it still seems potentially confusing.

A suggestion for your consideration:

Let's combine `colorMap` and the _current_ `colorMapString`.  They're just two ways of describing the same thing.  If it's an array, it's a colorMap, if it's a string it's colorMapString.  Then, let's make palettes a separate property.  `"colorMapPalette": "BrBG"`.

> Currently there is no relationship between the "3-class" and the actual number of bins.

Why allow the 'class' to be specified as part of the palette at all?  Having that exclusively set with a separate `bins` property seems ok with me.  Or is there a downside I haven't considered?
