### ISSUE TITLE
proxy URL for CKAN API contains double slash

### ISSUE THREAD

**Issue by florianm** [TerriaJS/terriajs#975]
As mentioned in https://github.com/datagovau/ckanext-cesiumpreview/issues/3#issuecomment-148624228 and https://github.com/NICTA/nationalmap/issues/120, I'm trying to load CKAN search results (containing several datasets with possibly spatial resources) into NM via URL parameters.

I've added my CKAN source with fq parameters, and somewhere near https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CkanCatalogGroup.js#L332, the proxy URL for my CKAN search URL gets a double slash at `//api/3/action` which breaks the URL. I'm not familiar enough with TerriaJS yet to figure out where this double slash comes from.

Would be ace if we could send any CKAN search result to NM through URL parameters alone!

**Comment by kring** [comment]
@florianm the extra slash is showing up when we query `data.gov.au`, too, though it doesn't break anything for that server.  It's not obvious to me either where the extra slash is coming from, but I'll check it out soon and let you know.  In the meantime, if happen to step through and figure out where it's coming from, let me know.  Thanks!

**Comment by maxious** [comment]
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CkanCatalogGroup.js#L332 calls cleanAndProxyUrl() which calls uri.toString() https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CkanCatalogGroup.js#L668 from https://github.com/medialize/URI.js which appends a slash to the end of the URL even if the trailing slash was missing from the URL string passed in because it was a raw hostname. Note that this slash is not added for subfolders eg. CKAN hosted in /data/ on a domain name. In this case, the original URL is honoured which could be just as problematic if the slash is added.

cleanAndProxyUrl() is specific/local to CkanCatalogGroup - perhaps it would be best to strip all trailing slashes in that function to ensure consistent behaviour.

> > this.url
> "http://catalogue.beta.data.wa.gov.au"
> > new URI(this.url).toString();
> "http://catalogue.beta.data.wa.gov.au/"
> > new URI("https://data.sa.gov.au/data").toString();
> "https://data.sa.gov.au/data"
> > new URI("https://data.sa.gov.au/data/").toString();
> "https://data.sa.gov.au/data/"
> > cleanAndProxyUrl(this, this.url)
> "proxy/_1d/http://catalogue.beta.data.wa.gov.au/"
> > cleanAndProxyUrl(this, this.url) + '/api/3/action/package_search?rows=100000'
> "proxy/_1d/http://catalogue.beta.data.wa.gov.au//api/3/action/package_search?rows=100000"

**Comment by stevage** [comment]
Sorry, I've known about this one for a while. Came across it when accessing a non-data.gov.au CKAN. I removed [one extra slash](https://github.com/TerriaJS/terriajs/commit/9ab4e5a667169a41a515b7aaed40b5cdf3c9a21f).

**Comment by kring** [comment]
@stevage ah ok that explains why I couldn't see where the slash was coming from when I looked at the code!

Based on what @maxious said, though, removing the slash before `api/` will break CKAN hosted anywhere other than the root of the hostname, unless the user explicitly includes the trailing slash in the URL.  That's certainly a less serious problem, but could be worth fixing.

**Comment by stevage** [comment]
Ah, you're right. And it is serious - my change actually breaks `data.sa.gov.au`, which for some reason hosts their API at `/data/api/...`

**Comment by kring** [comment]
You can fix it just by adding a slash to the end of the URL for `data.sa.gov.au` though right?

**Comment by stevage** [comment]
Pretty sure we fixed this somewhere.
