### ISSUE TITLE
Catalog changes breaks existing Share URL's

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#986]
We have partners that are embedding AREMI on their website as various iframes with specific layers turned on, which is great. Unfortunately, since the Share URL's use the name of the groups and layers as the key, whenever you change the structure or spelling of anything all existing Share URL's for layers in those parts of the catalog tree break. When these are iframes on somebody's website you effectively break their website...

This is a problem, since we do occasionally change the structure and names of things. Since we also have very close relationships with certain data custodians, they occasionally insist on changes as well.

For now, I've started writing custom init files hosted in a WWW S3 bucket and sending iframe blocks specifying the custom init file as a `#` URL, so that when we change anything I can then manually update those to reflect the new name or structure. However, it will be tedious to maintain these.

Possible solutions:
1. Bill suggested looking at SIRF to see if maybe we could do persistent identifiers: https://wiki.csiro.au/display/SIRF/The+SIRF+API
2. Some form of persistent UID in the init file/CKAN directory that never changes for a layer.
3. Our own URL shortening database where we can update the structure/layer names when they change.

Others?

**Comment by stevage** [comment]
What exactly is the change that's happening that's causing breakage? A resource name in CKAN? Which CKAN? Who owns that resource?

Maybe you could give some examples of these embedded maps? Just thinking that more context might be useful to work out the best way forward...

**Comment by stevage** [comment]
FWIW I'm thinking maybe instead of using the layer name as the only identifier we could support using the data URL in some cases. Presumably CKAN resource URLs change less often than their names?

**Comment by meh9** [comment]
So, I have no experience with CKAN, but I'm assuming that Terria just turns it into a JSON init structure like what we specify in init files, and that the Share feature will just use the `"name"` key like when init file shares are made. If that is the case then changing the display name in CKAN will cause this problem to occur.

For specific examples of the problems we've had in AREMI, the CEC has AREMI embedded and linked in various places, like here: http://www.cleanenergycouncil.org.au/policy-advocacy/arena/aremi-project.html

When we changed the name of the `Energy Infrastructure` category to `Electricity Infrastructure` every single iframe and share URL to any of the layers in that category stopped turning those layers on.

**Comment by meh9** [comment]
We've been considering giving each layer a persistent unique id/hash/whatever in the init file, so that when the name changes the id can stay the same. The Share feature would then use the id to share the layer.

This would mean that renaming and/or reorganising the catalog would not affect share URLs.

**Comment by axman6** [comment]
It would be nice if a tool (possibly @stevage's catalog editor) could go through and assign these IDs.

**Comment by kring** [comment]
Honestly maintaining unique IDs seems like a PITA to me.  Can we do it another way?  One idea off the top of my head: add a property to the JSON like this:

```
"name": "Some Group",
"type": "group",
"items": [
    {
        "name": "Some Item",
        "backwardCompatiblePaths": [
            ["Old Group Name", "Old Item Name"]
            ["Old Group Name", "Even Older Item Name"]
        ]
        ...
    }
]
```

Then, when resolving a share URL, TerriaJS first looks for an existing item in the same group with the same name.  Failing that, it looks for an item anywhere in the tree with an entry in `backwardCompatiblePaths` that matches the path of the item.

**Comment by axman6** [comment]
That puts a huge amount of work on the maintainer of the catalog :\

**Comment by kring** [comment]
It's not clear to me how having Steve's tool add IDs lets you avoid that work.  I guess if you assign the ID once, and then are really careful to only move things around by copying/pasting, rather than removing an old item and adding a new one somewhere else.  You'd have to do that in an editor, though, because Steve's tool doesn't currently let you move items around.

With what I proposed, you simply need to add/modify that property whenever you move or rename an item.  It it really a "huge amount" of work?

**Comment by axman6** [comment]
At the moment that's the only viable way for us to maintain things. Since we use templates it's pretty easy to ensure the ids stay with the layers, and their location can be moved at any time.

**Comment by kring** [comment]
How about this:

First, we add an `id` property, as you've proposed.  Then, we have a rule that says any catalog item without an explicit `id` gets one automatically.  We can build an automatic default ID from the item's path in the catalog tree.  This way we don't need to go through and add IDs to everything.  And forgetting to add an ID is not a problem, because we can refer to any item later by its previous automatic ID (even when moving or renaming it, which would otherwise give it a new automatic ID).

IMO this isn't a whole lot different from what I originally proposed, except that the property is `id` instead of `backwardCompatiblePaths`, and you can only have one of them.  And maybe the resolution is a tiny bit different.  But it sounds better now, right?

Nothing prevents you from going through all your catalog items and giving them IDs up front, if you want.  (well, except it makes the init file bigger and probably isn't an especially good use of your time! :) )

**Comment by stevage** [comment]
That seems like a reasonable solution to me. So:
1. CatalogItem gets a `matchKey()` function, which by default returns a string like `Generation/Current Power Generation - NEM/All generation types` (or maybe an array of keys in same cases?)
2. Certain catalog items may want to override this to add more robust matching (ie, using data URLs)
3. Catalog items can also have an actual `matchKey` string (or array of strings?) hardcoded in the catalog.
4. As an offline task, AREMI and other projects can "freeze" the catalog by generating and saving keys to all items. (I think that's a pretty easy piece of JQ).

I think we probably want to have arrays of keys, so that we can generate and share sensible keys ("New catalog/structure/mything") while also matching "Old catalog/stupid/structure/that/we're/embarrassed/about", and gently phasing out the latter.

**Comment by meh9** [comment]
These things sounds workable to me.

The three things off the top of my head that we would like to solve as simply as possible are:
1. Rename a layer.
2. Move a layer.
3. Rename a group.

We would much prefer something that we can set once and then not have to worry about after that. For example, if we were to change the name of a group, we would want to avoid having to update every layer below that group/branch more than once. We have renamed and moved groups several times in the past. Having something that we can magically set once and then never have to worry about again seems to work best for us, any solution supporting that workflow would be very happily accepted. :)

**Comment by stevage** [comment]
Cool. I think maybe:

`shareKeys: ["My Group/My Item", "My Old Group/My Item"]`

**Comment by AlexGilleran** [comment]
So I'm ready to start this, putting everything in the thread together:
- `CatalogItem` JSON can specify an `id` that becomes the canonical share key when using the share link from then on.
- `CatalogItem` JSON can also specify `shareKeys`, this is an array of keys that should also resolve to this `CatalogItem` when specified in a share link, to preserve backwards compatibility.
- Items in a `CatalogGroup` now have a `parent` property that is set to `this` on `CatalogGroup.add()` and deleted on `CatalogGroup.remove()`.
- `CatalogMember` has a `uniqueId` function that always returns a unique id for that CatalogMember - if there's an id specified in the JSON then it returns that, otherwise it returns the `uniqueId` of its parent plus its own `name`, joined by `/`. This means that in most cases `uniqueId` will be something like `Root Group/Group Name A/Group Name B/Item Name`.
- `CatalogItem` gets an `allShareKeys` function that returns an array of all possible keys that could have been used to share this item (`uniqueId` concatenated with `shareKeys`).

**Comment by meh9** [comment]
Sounds good to me!
