### ISSUE TITLE
Parsing exotic WMS GetFeatureInfo responses

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#987]
There are many WMS implementations that return `GetFeatureInfo` responses that Cesium currently does not handle. We need a way of adding handlers for these more exotic responses as we still need to display them.

Some examples follow.

The Bureau of Meteorology NEII (I think is a) THREDDS server only supports `image/png` and `text/xml` responses, the XML response looks like the below, and I believe this is the common THREDDS response type. This is the full response, no XML header or anything:

```
<FeatureInfoResponse>
    <longitude>122.58544921875</longitude>
    <latitude>-27.352252938063845</latitude>
    <iIndex>211</iIndex>
    <jIndex>346</jIndex>
    <gridCentreLon>122.60000151495376</gridCentreLon>
    <gridCentreLat>-27.350000482744875</gridCentreLat>
    <FeatureInfo>
        <value>20.984</value>
    </FeatureInfo>
</FeatureInfoResponse>
```

The URL for this is: http://neii.bom.gov.au/services/solarclim/wms/data/annClim_gloHorExp1Day.nc?format=image%2Fpng&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=mean_exposure&query_layers=mean_exposure&srs=EPSG%3A3857&bbox=12523442.714243278%2C-3757032.814272985%2C13775786.985667605%2C-2504688.542848654&x=229&y=135&width=256&height=256&info_format=text%2Fxml

The Landgate servers only support `text/plain` and `application/vnd.ogc.gml`. The responses are like:

```
GetFeatureInfo results:

Layer 'WP-004'
  Feature 61: 
    oid = '61'
    gid = '61'
    typ_cde = '32'
    voltage_kv = '132'
```

http://aremi.nicta.com.au/proxy/https://www2.landgate.wa.gov.au/ows/wmspublic?format=image%2Fpng&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=WP-004&query_layers=WP-004&srs=EPSG%3A3857&bbox=12836528.782099359%2C-4070118.8821290657%2C13149614.84995544%2C-3757032.814272985&x=91&y=53&width=256&height=256&info_format=text%2Fplain

```
<?xml version="1.0" encoding="ISO-8859-1"?>

<msGMLOutput 
     xmlns:gml="http://www.opengis.net/gml"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <WP-004_layer>
        <WP-004_feature>
            <gml:boundedBy>
                <gml:Box srsName="EPSG:3857">
                    <gml:coordinates>12913634.524551,-3826456.620988 12949056.789770,-3750553.215317</gml:coordinates>
                </gml:Box>
            </gml:boundedBy>
            <oid>61</oid>
            <gid>61</gid>
            <typ_cde>32</typ_cde>
            <voltage_kv>132</voltage_kv>
        </WP-004_feature>
    </WP-004_layer>
</msGMLOutput>
```

http://aremi.nicta.com.au/proxy/https://www2.landgate.wa.gov.au/ows/wmspublic?format=image%2Fpng&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=WP-004&query_layers=WP-004&srs=EPSG%3A3857&bbox=12836528.782099359%2C-4070118.8821290657%2C13149614.84995544%2C-3757032.814272985&x=91&y=53&width=256&height=256&info_format=application/vnd.ogc.gml

Since this is likely to come up again, being able to plug in a handler would be fantastic.

**Comment by stevage** [comment]
Supporting the text/plain format has the additional benefit of being a cure for #963.

**Comment by kring** [comment]
Terria has support for adding custom handling logic for unusual GetFeatureInfo formats.  It has to be done via code, though.  Check out the `getFeatureInfoFormats` property of `WebMapServiceCatalogItem`.

**Comment by kring** [comment]
Can we close this, and possible create separate issues to include built-in support for the formats listed here?

**Comment by meh9** [comment]
@kring says in a side channel:

Yep, there's a callback function parameter

https://cesiumjs.org/Cesium/Build/Documentation/GetFeatureInfoFormat.html

**Comment by meh9** [comment]
Btw, I'm not saying that we should try to understand the Landgate `text/plain` format, we should add a handler for the standard `application/vnd.ogc.gml` (why isn't this being caught by the existing Cesium handler for GML?)

However, if we do get a `text/plain` response, we should probably render it in a `<pre>...</pre>` tag or something to ensure that we preserve the newlines.

**Comment by RacingTadpole** [comment]
Looking at the [Landgate Fire & Rescue service](http://prototype.aremi.nicta.com/proxy/https://www2.landgate.wa.gov.au/ows/wmspublic?srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=DFES-016&bbox=12523442.714243278%2C-5009377.085697312%2C13775786.985667605%2C-3757032.814272985&width=256&height=256&query_layers=DFES-016&x=77&y=1&info_format=application%2Fvnd.ogc.gml) item: its feature info has `content-type:application/vnd.ogc.gml`. `WebMapServiceCatalogItem`'s `getFeatureInfoFormats` correctly interprets it as xml. But, because its outermost XML tag is the unknown name `msGMLOutput`, Cesium's `GetFeatureInfoFormat` renders it as "unknown" XML. This just shows the raw XML inside a `<pre>` tag.

**Comment by RacingTadpole** [comment]
OK, just continuing to note down the results of my digging here. As you noted, the Bureau of Meteorology NEII server returns a `<FeatureInfoResponse>` tag, which Cesium's `GetFeatureInfoFormat` interprets as meaning it is ESRI XML. Based on the [ArcGIS spec](http://help.arcgis.com/en/arcgisserver/10.0/help/arcgis_server_dotnet_help/index.html#//009300001663000000), this is meant to have `<Field>` tags inside, with `<FieldName>` and `<FieldValue>`. Since it has no such fields, it ends up with no description.

**Comment by RacingTadpole** [comment]
So, a question - how should we render the BoM NEII feature info? Only this part:

```
<FeatureInfo>
    <value>20.984</value>
</FeatureInfo>
```

? But what does the value mean?
